#!/usr/bin/env python3
"""render_services.py — content/services.json → src/pages/services/*.html

Writes the services index and the nine service pages as ordinary page
templates (see tools/README.md). Every piece of copy is emitted as a
{{content:services.…}} reference so the JSON stays the single source of
truth; the only baked-in text is what the mock builders derive from the
JSON's `hero_visual` / `visual` / `icon` spec strings (small CSS/SVG UI
mocks, never marketing copy) and the ↳ / + / × glyphs of the accordions.

Structure (Lance /product and /product/*, one to one — CONTRACT §3):
  index   hero · editorial image + platforms row · two grouped numbered lists ·
          sand "See it in action" (two reserved film slots) · closing CTA card
  page    split hero (crumb · h1 · intro · pill | mock panel) + platforms row ·
          centred statement + four count-up facts · six alternating feature blocks ·
          2×2 problems · sand four-step strip · white 2×3 comparison ·
          quote card + FAQ · CTA card

Aliases (items[].aliases) are NOT emitted as pages: every nav/footer/home
href already uses the short slugs (content/AUDIT.md #12), and a second page
per service would be duplicate content. Redirects, if ever wanted, belong
in vercel.json.

Stdlib only. Idempotent. Prints one line per file written.
"""
from __future__ import annotations

import json
import re
import html as _html
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content" / "services.json"
OUT_DIR = ROOT / "src" / "pages" / "services"
GENERATED = "<!-- generated by tools/render_services.py — edit content/services.json -->"

ARROW = ('<svg viewBox="0 0 12 12" width="11" height="11" aria-hidden="true"><path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" '
         'fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
TICK_SVG = '<svg viewBox="0 0 8 8" aria-hidden="true"><path d="M1.5 4.2l1.8 1.8L6.6 2.4"/></svg>'


def esc(s: str) -> str:
    return _html.escape(str(s), quote=True)


def c(path: str, fallback: str | None = None) -> str:
    """A {{content:services.<path>}} reference (with optional fallback)."""
    if fallback is not None:
        return "{{content:services." + path + "|" + fallback + "}}"
    return "{{content:services." + path + "}}"


def btn(label: str, href: str, extra: str = "") -> str:
    return (f'<a class="btn btn--light{(" " + extra) if extra else ""}" href="{href}">{label}'
            f'<span class="btn__ico">{ARROW}</span></a>')


def eyebrow_split(eyebrow_html: str, main_html: str, cls: str = "") -> str:
    return (f'<div class="page-split{(" " + cls) if cls else ""}">'
            f'<div class="page-split__aside"><p class="page-eyebrow">{eyebrow_html}</p></div>'
            f'<div class="page-split__main">{main_html}</div></div>')


# ---------------------------------------------------------------------------
# spec parsing (the `visual` / `hero_visual` strings)
# ---------------------------------------------------------------------------

def quoted_spans(spec: str) -> list[tuple[str, int, int]]:
    """Single-quoted strings, tolerant of apostrophes inside them ('DON'T', 'creator's')."""
    out = []
    i, n = 0, len(spec)
    openers = " ([:→,;/—-"
    closers = " ,.;:)]/—-\n"
    while i < n:
        ch = spec[i]
        if ch == "'" and (i == 0 or spec[i - 1] in openers):
            j = i + 1
            while j < n:
                if spec[j] == "'" and (j + 1 == n or spec[j + 1] in closers):
                    break
                j += 1
            if j < n:
                out.append((spec[i + 1:j], i, j + 1))
                i = j + 1
                continue
        i += 1
    return out


WORDNUM = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10}


def wordnum(w: str) -> int:
    w = w.lower()
    return WORDNUM.get(w, int(w) if w.isdigit() else 0)


def classify(spec: str) -> list[dict]:
    """Every quoted string with a kind and the marks the spec hangs on it."""
    toks = []
    for text, s, e in quoted_spans(spec):
        before = spec[max(0, s - 34):s]
        after = spec[e:e + 160]   # long enough to see a following parenthetical
        kind = "row"
        if re.search(r"(titled|[Hh]eader(?: row)?|heading|[Hh]eader:)\s*$", before):
            kind = "title"
        elif re.search(r"[Ff]ooter(?: line| chip| in grey|:)?\s*:?\s*$", before):
            kind = "footer"
        elif re.search(r"(chip|chips|tag|pill|labelled|label|stamp(?: outline)?(?: top-right)?(?: reading)?|strip reads|reads)\s*$", before) \
                or re.search(r"^\s*(chip|tag|pill|timing tag)\b", after) \
                or re.search(r"^\s*(and|,)\s*'", after) and re.search(r"(chip|chips|tag|labelled)\b[^.]{0,40}$", before):
            kind = "chip"
        elif re.search(r"(call bubble|bubble reading|bubble)\s*$", before):
            kind = "bubble"
        elif re.search(r"(note under|note under row \d+|notes line under row \d+|note:|small note)\s*[^']{0,12}$", before):
            kind = "note"
        elif re.search(r"(a second small card|a narrow status card|note card)[^']{0,20}$", before):
            kind = "row"
        if kind in ("row", "chip") and text.isupper() and len(text) <= 28 and kind == "row" and "·" not in text \
                and not re.search(r"\d", text):
            kind = "label"
        marks = set()
        a = after.lower()
        if text.endswith(" ✓") or "✓" in text or re.match(r"^\s*\((tick|tick, jam)\)", a) or re.match(r"^\s*\(jam", a) \
                or re.match(r"^\s*with a jam tick", a) or re.match(r"^\s*\(?tick", a):
            marks.add("tick")
        if re.match(r"^\s*\(empty", a):
            marks.add("empty")
        if re.match(r"^\s*\((current|jam, current)", a) or re.match(r"^\s*\(jam, current", a) or "(current" in a[:12]:
            marks.add("current")
        if "strikethrough" in a[:30] or "struck" in a[:20] or "strikethrough" in before.lower()[-24:] \
                or "struck-through" in before.lower()[-30:]:
            marks.add("strike")
        if re.match(r"^\s*in jam", a) or re.match(r"^\s*\(jam", a) or re.match(r"^\s*chip in jam", a) \
                or re.search(r"jam (chip|outline|tick)?\s*'?$", before.lower()):
            marks.add("jam")
        if "★" in text:
            marks.add("star")
        if "filled black" in a[:40] or re.search(r"filled black[^']{0,30}$", before.lower()):
            marks.add("ink")
        toks.append({"text": text.replace(" ✓", "").replace("✓", "").replace(" · ★", "").replace("★", "").strip(),
                     "kind": kind, "marks": marks, "before": before, "after": after})
    return toks


def tick(jam: bool = True) -> str:
    return f'<span class="mock-tick{"" if jam else " mock-tick--ink"}" aria-hidden="true">{TICK_SVG}</span>'


def chip(text: str, cls: str = "") -> str:
    return f'<span class="mock-chip{(" " + cls) if cls else ""}">{esc(text)}</span>'


def split_parts(text: str) -> list[str]:
    return [p.strip() for p in re.split(r"\s+·\s+", text) if p.strip()]


def row_html(tok: dict, i: int, opts: dict) -> str:
    text, marks = tok["text"], tok["marks"]
    cls = ["mock-row"]
    if "strike" in marks:
        cls.append("mock-row--strike")
    if tok["kind"] == "note":
        cls.append("mock-row--muted")
    parts = split_parts(text)
    n_html = ""
    head = parts[0] if parts else text
    m = re.match(r"^(\d{2})\s+(.+)$", head)
    mt = re.match(r"^(\d{1,2}:\d{2})\s+(.+)$", head)
    if m:
        n_html = f'<span class="mock-row__n">{m.group(1)}</span>'
        head = m.group(2)
    elif mt:
        n_html = f'<span class="mock-row__n" style="width:36px">{mt.group(1)}</span>'
        head = mt.group(2)
    elif opts.get("numbered"):
        n_html = f'<span class="mock-row__n">{i + 1:02d}</span>'
    lead = ""
    if opts.get("avatars"):
        lead = '<span class="mock-avatar" aria-hidden="true"></span>'
    if opts.get("checkboxes"):
        lead = tick() if "tick" in marks else '<span class="mock-ring" aria-hidden="true"></span>'
    if opts.get("files"):
        lead = ('<svg width="12" height="14" viewBox="0 0 12 14" fill="none" stroke="currentColor" stroke-width="1" '
                'style="flex-shrink:0;color:#a9a8a3" aria-hidden="true"><path d="M1 1h7l3 3v9H1z M8 1v3h3"/></svg>')
    vals = parts[1:]
    tail = []
    for v in vals:
        if opts.get("val_chips"):
            vc = "mock-chip--jam" if ("jam" in marks or "current" in marks) else ""
            tail.append(chip(v, vc))
        else:
            tail.append(f'<span class="mock-row__v">{esc(v)}</span>')
    if "tick" in marks and not opts.get("checkboxes"):
        tail.append(tick())
    if "star" in marks:
        tail.append('<span class="mock-star" aria-hidden="true">★</span>')
    if "empty" in marks:
        tail.append('<span class="mock-ring" aria-hidden="true"></span>')
    if "current" in marks and "tick" not in marks and not opts.get("val_chips"):
        tail.append('<span class="mock-dot mock-dot--jam" aria-hidden="true"></span>')
    if opts.get("cross") and "tick" not in marks:
        tail.append('<span class="mock-x" aria-hidden="true">×</span>')
    if opts.get("toggles"):
        tail.append('<span class="mock-toggle mock-toggle--on" aria-hidden="true"></span>')
    # "'window' row with a small segmented bar (7 · 30 · 60 · 365) and the 60 segment filled"
    mseg = re.match(r"^\s*(?:date\s+)?rows?\b[^.]{0,40}segmented bar\s*\(([^)]*)\)", tok["after"])
    if mseg:
        segs = [x.strip() for x in re.split(r"[·,]", mseg.group(1)) if x.strip()]
        mfill = re.search(r"the (\S+) segment filled", tok["after"])
        fill = mfill.group(1) if mfill else (segs[-1] if segs else "")
        tail.append('<span class="mock-seg" aria-hidden="true">'
                    + "".join(f'<i class="{"is-on" if sgm == fill else ""}">{esc(sgm)}</i>' for sgm in segs)
                    + "</span>")
    elif re.match(r"^\s*date rows?\b", tok["after"]) and not vals:
        tail.append('<span class="mock-row__v"><span class="mock-line mock-line--w45" style="display:block;width:56px"></span></span>')
    if "jam" in marks and "current" not in marks and "tick" not in marks and not opts.get("val_chips"):
        cls.append("mock-row--jam")
        if not tail:
            tail.append('<span class="mock-dot mock-dot--jam" aria-hidden="true"></span>')
    if "ink" in marks and tail:
        tail[-1] = tail[-1].replace("mock-chip", "mock-chip mock-chip--ink", 1)
    t_cls = "mock-row__t"
    return (f'<div class="{" ".join(cls)}" style="--i:{i}">{n_html}{lead}'
            f'<span class="{t_cls}">{esc(head)}</span>{"".join(tail)}</div>')


def stub_rows(n: int, marked: list[int], chip_text: str | None, numbered: bool = True, start: int = 0,
              checkboxes: bool = False, strike_rows: dict | None = None) -> str:
    out = []
    widths = ["mock-line--w80", "mock-line--w60", "mock-line", "mock-line--w45", "mock-line--w80", "mock-line--w60", "mock-line", "mock-line--w45"]
    for k in range(n):
        idx = k + 1
        is_marked = idx in marked
        n_html = f'<span class="mock-row__n">{idx:02d}</span>' if numbered else ""
        lead = ""
        if checkboxes:
            lead = tick() if is_marked else '<span class="mock-ring" aria-hidden="true"></span>'
        body = f'<span class="mock-row__t"><span class="mock-line {widths[k % 8]}{" mock-line--dark" if is_marked else ""}" style="display:block;max-width:{78 if is_marked else 64}%"></span></span>'
        if strike_rows and idx in strike_rows:
            body = f'<span class="mock-row__t" style="text-decoration:line-through;color:var(--grey)">{esc(strike_rows[idx])}</span>'
        tail = ""
        if is_marked:
            if chip_text:
                tail += chip(chip_text, "mock-chip--jam")
            if not checkboxes:
                tail += tick()
        out.append(f'<div class="mock-row{"" if is_marked else " mock-row--muted"}" style="--i:{start + k}">{n_html}{lead}{body}{tail}</div>')
    return "".join(out)


def find_marked_rows(spec: str) -> list[int]:
    m = re.search(r"rows? \(?(\d{2})(?: and (\d{2}))?\)?", spec)
    if not m:
        m = re.search(r"\((\d{2}) and (\d{2})\)", spec)
    if not m:
        return []
    return [int(x) for x in m.groups() if x]


ROW_NOUN = r"(?:rows?|beats?|steps?|lines?|items?|entries|permissions|sources?|takes?|stages?)"


def find_row_count(spec: str) -> int:
    """'Three rows', 'five beats', '8 lines' → the intended row count."""
    m = re.search(r"\b(Eight|Five|Six|Seven|Four|Three|Two|eight|five|six|seven|four|three|two)\s+"
                  r"(?:numbered |short |small |stacked |note |stage |source |grey |rows? with |section )?" + ROW_NOUN + r"\b", spec)
    if m:
        return wordnum(m.group(1))
    m = re.search(r"\b(\d)\s+" + ROW_NOUN + r"\b", spec)
    return int(m.group(1)) if m else 0


def paren_enum(spec: str) -> list[tuple[str, str]]:
    """A parenthesised enumeration of numbered steps —
    '(01 Problem, 02 Discovery, 03 Demo, 04 Payoff, 05 Call to action)' —
    which Lance-style specs use instead of quoting every row. Returns
    [(number, label), …] when the parenthesis holds three or more of them."""
    for m in re.finditer(r"\(([^()]{12,220})\)", spec):
        parts = [p.strip() for p in m.group(1).split(",") if p.strip()]
        pairs = []
        for p in parts:
            mm = re.match(r"^(\d{2})\s+(.{2,40})$", p)
            if not mm:
                pairs = []
                break
            pairs.append((mm.group(1), mm.group(2).strip()))
        if len(pairs) >= 3:
            return pairs
    return []


def paren_tag_list(spec: str) -> list[str]:
    """The quoted tag run that follows such a list: ('0–3s', '3–8s', …)."""
    m = re.search(r"\(\s*('(?:[^']|'\w)*'(?:\s*,\s*'(?:[^']|'\w)*')*)\s*(?:,\s*…)?\s*\)", spec)
    if not m:
        return []
    return [t.strip().strip("'") for t in re.findall(r"'([^']*)'", m.group(1))]


def extend_tags(tags: list[str], n: int) -> list[str]:
    """'0–3s', '3–8s', …  →  continue the run to n tags (the spec's own '…').
    Only extends duration ranges; anything else is returned untouched."""
    if len(tags) >= n or len(tags) < 2:
        return tags
    rng = re.compile(r"^(\d+)\s*[–-]\s*(\d+)\s*s$")
    ms = [rng.match(t) for t in tags]
    if not all(ms):
        return tags
    a, b = int(ms[-1].group(1)), int(ms[-1].group(2))
    step = b - a
    out = list(tags)
    while len(out) < n:
        a, b = b, b + step
        out.append(f"{a}–{b}s")
    return out


def dims(spec: str, default=(400, 300)) -> tuple[int, int]:
    m = re.search(r"(\d{3})×(\d{3})", spec)
    return (int(m.group(1)), int(m.group(2))) if m else default


# ---------------------------------------------------------------------------
# mock builders
# ---------------------------------------------------------------------------

def card_open(title: str | None, right: str | None = None, cls: str = "", width: int | None = None, rec: bool = False) -> str:
    style = f' style="--w:{min(width, 560)}px"' if width else ""
    head = ""
    if title or right:
        r = ""
        if right:
            r = f'<span class="mock-head__r">{esc(right)}</span>'
        elif rec:
            r = '<span class="mock-head__r"><span class="mock-dot mock-dot--jam"></span>REC</span>'
        head = f'<div class="mock-head"><span class="mock-head__t">{esc(title or "")}</span>{r}</div>'
    return f'<div class="mock-card{(" " + cls) if cls else ""}"{style}>{head}'


def card_close(footer_toks: list[dict], extra_foot: str = "") -> str:
    foot = ""
    if footer_toks or extra_foot:
        inner = "".join(chip(t["text"]) if "chip" in t["before"].lower()[-14:] else f'<span>{esc(t["text"])}</span>'
                        for t in footer_toks)
        foot = f'<div class="mock-foot">{inner}{extra_foot}</div>'
    return f"{foot}</div>"


def chips_row(toks: list[dict], default_jam_first: bool = False) -> str:
    if not toks:
        return ""
    out = []
    for k, t in enumerate(toks):
        cls = "mock-chip--jam" if ("jam" in t["marks"] or "current" in t["marks"]) else ""
        if "ink" in t["marks"]:
            cls = "mock-chip--ink"
        if "tick" in t["marks"]:
            out.append(f'<span class="mock-chip {cls}">{tick()}{esc(t["text"])}</span>')
        else:
            out.append(chip(t["text"], cls))
    return f'<div class="mock-chips">{"".join(out)}</div>'


def phone_html(spec: str, lg: bool, tc_seed: int, toks: list[dict]) -> str:
    s = spec.lower()
    inner = ['<span class="mock-phone__rec">REC</span>']
    m = re.search(r"(\d{2}):(\d{2}):(\d{2})", spec)
    seed = tc_seed
    if m:
        seed = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3))
    inner.append(f'<span class="mock-phone__tc" data-tc="{seed}">{seed // 3600:02d}:{(seed // 60) % 60:02d}:{seed % 60:02d}</span>')
    if "figure" in s:
        inner.append('<span class="mock-phone__figure" aria-hidden="true"><svg viewBox="0 0 100 120" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round">'
                     '<circle cx="50" cy="30" r="13"/><path d="M28 78c2-18 10-26 22-26s20 8 22 26"/><path d="M14 92h72M22 92v22M78 92v22"/>'
                     '<rect x="56" y="70" width="16" height="22" rx="2"/></svg></span>')
    if "level meter" in s or "meter" in s:
        inner.append('<span class="mock-phone__meter" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span>')
    bub = [t for t in toks if t["kind"] == "bubble"]
    if bub:
        inner.append(f'<span class="mock-call">{esc(bub[0]["text"])}</span>')
    return f'<div class="mock-phone{" mock-phone--lg" if lg else ""}" aria-hidden="true">{"".join(inner)}</div>'


def list_card(spec: str, toks: list[dict], width: int | None, opts: dict, cls: str = "") -> str:
    """The workhorse: header · labels · rows · chips · footer."""
    titles = [t for t in toks if t["kind"] == "title"]
    title = titles[0]["text"] if titles else None
    right = titles[1]["text"] if len(titles) > 1 else None
    s = spec.lower()
    rec = "rec dot" in s and "phone" not in s
    out = [card_open(title, right, cls, width, rec=rec)]
    if "masked" in s and "code" in s:                       # a code field sits at the top of the card
        out.append('<div class="mock-code" aria-hidden="true"><span>' + "</span><span>".join(["\u2022" * 4] * 3) + "</span></div>")
    i = 0
    rows_open = False
    pending_chips: list[dict] = []
    body_toks = [t for t in toks if t["kind"] not in ("title", "footer", "bubble")]
    # explicit "N rows" with no quoted rows → skeleton rows
    quoted_rows = [t for t in body_toks if t["kind"] == "row"]
    n_stub = find_row_count(spec) if len(quoted_rows) <= 1 else 0
    marked = find_marked_rows(spec)
    # "(01 Problem, 02 Discovery, …)" — a numbered enumeration the spec writes in
    # parentheses instead of quotes. Real labels beat skeleton lines.
    enum = paren_enum(spec) if len(quoted_rows) <= 2 else []
    if enum:
        tags = extend_tags(paren_tag_list(spec), len(enum))
        out.append('<div class="mock-rows">')
        for k, (num, label) in enumerate(enum):
            tag = f'<span class="mock-row__v">{esc(tags[k])}</span>' if k < len(tags) else ""
            out.append(f'<div class="mock-row mock-row--stack" style="--i:{k}">'
                       f'<span class="mock-row__n">{esc(num)}</span>'
                       f'<span class="mock-row__t">{esc(label)}</span>{tag}'
                       f'<span class="mock-row__d"><span class="mock-line {["mock-line--w80","mock-line--w60","mock-line","mock-line--w45"][k % 4]}"></span></span></div>')
        out.append("</div>")
        i = len(enum)
        n_stub = 0
        drop = {t["text"] for t in quoted_rows} | set(tags)
        body_toks = [t for t in body_toks if t["text"] not in drop]
    chip_for_marked = None
    strike: dict = {}
    for t in body_toks:
        if t["kind"] == "chip" and re.search(r"(carry|gain|with) a jam tick and a\s*$", t["before"]):
            chip_for_marked = t["text"]
        if t["kind"] == "chip" and "strike" in t["marks"]:
            strike[len(strike) + 1] = t["text"]
    if n_stub and "grid" not in s:
        if "strikethrough" in s and quoted_rows:
            strike = {n_stub: quoted_rows[0]["text"]}
            quoted_rows = []
        out.append('<div class="mock-rows">')
        out.append(stub_rows(n_stub, marked, chip_for_marked, numbered=True, checkboxes="checkbox" in s, strike_rows=strike))
        out.append("</div>")
        i = n_stub
        body_toks = [t for t in body_toks if t["kind"] != "row" and t["text"] != chip_for_marked]
    for t in body_toks:
        if t["kind"] == "label":
            if pending_chips:
                out.append(chips_row(pending_chips)); pending_chips = []
            if rows_open:
                out.append("</div>"); rows_open = False
            out.append(f'<p class="mock-label">{esc(t["text"])}</p>')
        elif t["kind"] in ("row", "note"):
            if pending_chips:
                out.append(chips_row(pending_chips)); pending_chips = []
            if not rows_open:
                out.append('<div class="mock-rows">'); rows_open = True
            out.append(row_html(t, i, opts)); i += 1
        elif t["kind"] == "chip":
            if rows_open and not pending_chips:
                out.append("</div>"); rows_open = False
            pending_chips.append(t)
    if rows_open:
        out.append("</div>")
    if pending_chips:
        out.append(chips_row(pending_chips))
    if "signature line" in s:
        out.append('<div class="mock-sig"><span class="mock-sig__line" aria-hidden="true"></span><span class="mock-dot mock-dot--jam" aria-hidden="true"></span><span>signed</span></div>')
    if "stamp" in s:
        st = [t for t in toks if "stamp" in t["before"].lower()]
        if st:
            out.append(f'<span class="mock-stamp" aria-hidden="true">{esc(st[0]["text"])}</span>')
    footers = [t for t in toks if t["kind"] == "footer"]
    out.append(card_close(footers))
    return "".join(out)


def steps_card(spec: str, toks: list[dict], width: int | None) -> str:
    titles = [t for t in toks if t["kind"] == "title"]
    rows = [t for t in toks if t["kind"] == "row"]
    steps = rows[:4] if len(rows) >= 3 else rows
    rest = rows[len(steps):]
    out = [card_open(titles[0]["text"] if titles else None, None, "", width)]
    out.append('<div class="mock-steps">')
    for k, t in enumerate(steps):
        m = t["marks"]
        if "tick" in m:
            mark = tick(jam=("jam" in m or "current" in m or k == len(steps) - 2))
        elif "current" in m or "jam" in m:
            mark = '<span class="mock-dot mock-dot--jam" aria-hidden="true"></span>'
        else:
            mark = '<span class="mock-ring" aria-hidden="true"></span>'
        cls = "mock-step" + (" mock-step--current" if ("current" in m or "jam" in m) else "")
        out.append(f'<div class="{cls}" style="--i:{k}">{mark}<span class="mock-step__l">{esc(t["text"])}</span></div>')
    out.append("</div>")
    if rest:
        out.append('<div class="mock-rows" style="margin-top:12px">')
        for k, t in enumerate(rest):
            out.append(row_html(t, k + 4, {"val_chips": False}))
        out.append("</div>")
    chips = [t for t in toks if t["kind"] == "chip"]
    out.append(chips_row(chips))
    notes = [t for t in toks if t["kind"] == "note"]
    if notes:
        out.append(f'<p class="mock-strip" style="text-align:left;margin-top:10px">{esc(notes[0]["text"])}</p>')
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def track_card(spec: str, toks: list[dict], width: int | None, hero: bool = False) -> str:
    s = spec.lower()
    titles = [t for t in toks if t["kind"] == "title"]
    title = titles[0]["text"] if titles else None
    out = [card_open(title, None, "mock-card--wide" if hero else "", width)]
    clips = [t for t in toks if t["kind"] == "row" and not re.search(r"(caption|toggle|export)", t["before"].lower()[-40:])]
    caps = [t for t in toks if re.search(r"caption[^']{0,30}$", t["before"].lower())]
    out.append('<div class="mock-track"><div class="mock-track__ruler" aria-hidden="true">' + "<i></i>" * 9 + "</div>")
    out.append('<div class="mock-track__row">')
    k = 0
    cut_after = {1, 3} if "scissor" in s else set()
    for t in clips:
        if re.search(r"(toggle|captions ·)", t["text"].lower()):
            continue
        cls = "mock-clip"
        if "strike" in t["marks"]:
            cls += " mock-clip--strike"
        if "jam" in t["marks"]:
            cls += " mock-clip--jam"
        if "beats" in t["text"].lower() and "–" in t["text"]:
            cls += " mock-clip--w3"
        elif "hook" in t["text"].lower() and hero:
            cls += " mock-clip--w2"
        star = ' <span class="mock-star">★</span>' if "star" in t["marks"] else ""
        out.append(f'<span class="{cls}" style="--i:{k}">{esc(t["text"])}{star}</span>')
        if k in cut_after:
            out.append('<span class="mock-cut" aria-hidden="true"><span class="mock-cut__l">dead air</span></span>')
        k += 1
    out.append("</div>")
    if "caption" in s:
        out.append('<div class="mock-track__row mock-track__row--thin">')
        if caps:
            out.append(f'<span class="mock-clip mock-clip--cap mock-clip--w2" style="--i:{k}">{esc(caps[0]["text"])}</span>')
            k += 1
        for j in range(3):
            out.append(f'<span class="mock-clip mock-clip--cap" style="--i:{k + j}"><span class="mock-line mock-line--w60" style="width:60%"></span></span>')
        out.append("</div>")
    out.append("</div>")
    tog = [t for t in toks if "toggle" in t["before"].lower()[-16:] or t["text"].lower().startswith("captions")]
    if tog:
        out.append(f'<div class="mock-row mock-row--wrap" style="--i:{k + 3};border-top:0"><span class="mock-row__t">{esc(tog[0]["text"])}</span><span class="mock-toggle mock-toggle--on" aria-hidden="true"></span></div>')
    if "export bar" in s:
        chips = [t for t in toks if t["kind"] == "chip"]
        out.append('<div class="mock-export"><div class="mock-bar"><span class="mock-bar__fill" style="--p:100%"></span></div>')
        out.append('<div class="mock-export__chips">' + "".join(chip(t["text"]) for t in chips[:3]) + "</div></div>")
    else:
        out.append(chips_row([t for t in toks if t["kind"] == "chip"]))
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def grid_card(spec: str, toks: list[dict], width: int | None) -> str:
    s = spec.lower()
    titles = [t for t in toks if t["kind"] == "title"]
    m = re.search(r"(\d)×(\d) grid", spec)
    rows_n, cols_n = (int(m.group(1)), int(m.group(2))) if m else (2, 3)
    out = [card_open(titles[0]["text"] if titles else None, None, "", width)]
    rowlabels, collabels, cells = [], [], []
    mode = "cells"
    for t in toks:
        if t["kind"] == "title":
            continue
        b = t["before"].lower()
        if "row labels" in b or (mode == "rows" and re.match(r"^\s*(,|and)\s*$", b[-6:])):
            mode = "rows"; rowlabels.append(t["text"]); continue
        if "column labels" in b or (mode == "cols" and re.match(r"^\s*(,|and)\s*$", b[-6:])):
            mode = "cols"; collabels.append(t["text"]); continue
        if t["kind"] == "footer":
            continue
        cells.append(t)
    if rowlabels and collabels:
        out.append(f'<div class="mock-grid mock-grid--labels" style="--cols:{len(collabels)}">')
        out.append('<span class="mock-tile mock-tile--head"></span>')
        for cl in collabels:
            out.append(f'<span class="mock-tile mock-tile--head">{esc(cl)}</span>')
        filled = [t for t in cells if "filled" in t["before"].lower() or "shot" in t["text"].lower()]
        label = filled[0]["text"] if filled else "shot"
        k = 0
        total = len(rowlabels) * len(collabels)
        nfill = 6 if total == 9 else total - 2
        jam_at = 4
        for r, rl in enumerate(rowlabels):
            out.append(f'<span class="mock-tile mock-tile--rowhead">{esc(rl)}</span>')
            for cc in range(len(collabels)):
                idx = r * len(collabels) + cc
                if idx < nfill or (idx == total - 1 and nfill >= total):
                    dot = '<span class="mock-dot mock-dot--jam" aria-hidden="true"></span>' if idx == jam_at else ""
                    out.append(f'<span class="mock-tile" style="--i:{k}">{esc(label)}{dot}</span>')
                else:
                    out.append(f'<span class="mock-tile mock-tile--empty" style="--i:{k}"></span>')
                k += 1
        out.append("</div>")
    else:
        tiles = [t for t in cells if t["kind"] in ("row", "chip", "label")]
        out.append(f'<div class="mock-grid" style="--cols:{cols_n}">')
        jam_idx = {1, 4} if "jam dot" in s else set()
        for k, t in enumerate(tiles[: rows_n * cols_n]):
            dot = '<span class="mock-dot mock-dot--jam" aria-hidden="true"></span>' if k in jam_idx else ""
            sub = '<span class="mock-tile__s"><span class="mock-line mock-line--w80" style="display:block;height:5px"></span></span>' if "example" in s else ""
            out.append(f'<span class="mock-tile" style="--i:{k}">{esc(t["text"])}{dot}{sub}</span>')
        out.append("</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def seals_card(spec: str, toks: list[dict], width: int | None) -> str:
    labels = [t for t in toks if t["kind"] in ("row", "chip", "label")][:3]
    out = [card_open(None, None, "", width), '<div class="mock-seals">']
    for k, t in enumerate(labels):
        out.append(f'<div class="mock-seal" style="--i:{k}"><span class="mock-seal__ring" aria-hidden="true"></span><span>{esc(t["text"])}</span></div>')
    out.append("</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def cols_card(spec: str, toks: list[dict], width: int | None, opts: dict) -> str:
    s = spec.lower()
    titles = [t for t in toks if t["kind"] == "title"]
    out = [card_open(titles[0]["text"] if titles else None, None, "", width)]
    cols: list[dict] = []
    for t in toks:
        if t["kind"] in ("title", "footer", "bubble"):
            continue
        if t["kind"] == "label":
            cols.append({"label": t["text"], "items": []}); continue
        if not cols:
            cols.append({"label": None, "items": []})
        cols[-1]["items"].append(t)
    if "identical text" in s and len(cols) >= 2:
        shared = cols[0]["items"] or cols[1]["items"]
        cols[0]["items"] = shared; cols[1]["items"] = shared
    eq = "equals sign" in s
    style = ' style="grid-template-columns:1fr auto 1fr"' if eq else ""
    out.append(f'<div class="mock-cols{" mock-cols--eq" if eq else ""}"{style}>')
    k = 0
    for ci, col in enumerate(cols[:2]):
        out.append("<div>")
        if col["label"]:
            out.append(f'<p class="mock-label">{esc(col["label"])}</p>')
        if "phone frame" in s and ci == 0:
            bub = [t for t in toks if t["kind"] == "bubble"]
            call = f'<span class="mock-call" style="position:static;display:block;margin-top:8px">{esc(bub[0]["text"])}</span>' if bub else ""
            out.append(f'<div class="mock-phone" style="width:96px;margin:4px 0 8px">{call}</div>')
        if "two line-drawn figures" in s and ci == 1 and not col["items"]:
            out.append('<svg viewBox="0 0 160 100" width="140" height="88" fill="none" stroke="#a9a8a3" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
                       '<circle cx="40" cy="28" r="9"/><path d="M26 70c1-16 6-24 14-24s13 8 14 24M40 70v24M33 94h14"/>'
                       '<circle cx="86" cy="30" r="9"/><path d="M72 72c1-16 6-24 14-24s13 8 14 24M86 72v22M79 94h14"/>'
                       '<rect x="122" y="18" width="16" height="30" rx="3"/><path d="M130 48v30M118 92l12-14 12 14"/></svg>')
        out.append('<div class="mock-rows">')
        cross = "cross" in s and (col["label"] or "").upper().startswith("DON")
        ticks = "tick" in s and (col["label"] or "").upper() in ("DO", "MUST SAY")
        for t in col["items"]:
            tt = dict(t); tt["marks"] = set(t["marks"])
            if ticks:
                tt["marks"].add("tick")
            out.append(row_html(tt, k, {"cross": cross, **opts})); k += 1
        if not col["items"] and "line" in s:
            n = 3 if "three lines" in s else 2
            out.append(stub_rows(n, [1, 2, 3] if ticks else [], None, numbered=False, start=k))
            if cross:
                out.append("")
            k += n
        out.append("</div></div>")
        if eq and ci == 0:
            out.append('<span class="mock-eq" aria-hidden="true">=</span>')
    out.append("</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


KIT_ICONS = {
    "phone": '<svg viewBox="0 0 26 26"><rect x="9" y="2" width="8" height="15" rx="1.5"/><path d="M13 17v6M9 24h8M11 5h4"/></svg>',
    "ring": '<svg viewBox="0 0 26 26"><circle cx="13" cy="10" r="7"/><circle cx="13" cy="10" r="3.5"/><path d="M13 17v6M9 24h8"/></svg>',
    "mic": '<svg viewBox="0 0 26 26"><rect x="10" y="2" width="6" height="11" rx="3"/><path d="M7 11a6 6 0 0 0 12 0M13 17v6M9 24h8"/></svg>',
    "window": '<svg viewBox="0 0 26 26"><rect x="4" y="3" width="18" height="20" rx="1"/><path d="M13 3v20M4 13h18"/></svg>',
    "desk": '<svg viewBox="0 0 26 26"><path d="M2 10h22M5 10v12M21 10v12M9 10V6h8v4"/></svg>',
    "product": '<svg viewBox="0 0 26 26"><path d="M8 8h10v14H8zM10 8V5h6v3"/></svg>',
}


def kit_card(spec: str, toks: list[dict], width: int | None) -> str:
    s = spec.lower()
    titles = [t for t in toks if t["kind"] == "title"]
    out = [card_open(titles[0]["text"] if titles else None, None, "", width), '<div class="mock-kit">']
    items = []
    for name, key in (("A phone on a tripod", "phone"), ("Ring light", "ring"), ("Lapel mic", "mic")):
        if key == "phone" and "phone on" in s or key == "ring" and "ring light" in s or key == "mic" and "lapel mic" in s:
            items.append((name, key))
    if "window light" in s:
        items = [i for i in items if i[1] != "ring"] + [("Window light", "window")]
    for k, (name, key) in enumerate(items):
        out.append(f'<div class="mock-kit__row" style="--i:{k}"><span class="mock-kit__ico" aria-hidden="true">{KIT_ICONS[key]}</span><span class="mock-row__t">{esc(name)}</span>{tick()}</div>')
    strikes = [t for t in toks if "strike" in t["marks"]]
    for t in strikes:
        out.append(f'<div class="mock-kit__row mock-kit__row--strike" style="--i:{len(items)}"><span class="mock-kit__ico" aria-hidden="true">{KIT_ICONS["desk"]}</span><span class="mock-row__t">{esc(t["text"])}</span></div>')
    out.append("</div>")
    out.append(chips_row([t for t in toks if t["kind"] == "chip" and "strike" not in t["marks"]]))
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def bars_card(spec: str, toks: list[dict], width: int | None) -> str:
    s = spec.lower()
    titles = [t for t in toks if t["kind"] == "title"]
    out = [card_open(titles[0]["text"] if titles else None, None, "", width)]
    rows = [t for t in toks if t["kind"] in ("row",)]
    chips = [t for t in toks if t["kind"] == "chip"]
    tags = [t for t in chips if re.match(r"^~?\d", t["text"])]
    if "level bars" in s:
        out.append('<div class="mock-bars">')
        for k, (label, cls, p) in enumerate((("Voice", "", "82%"), ("Music", "mock-bar__fill--grey", "34%"))):
            out.append(f'<div class="mock-bars__row" style="--i:{k}"><span>{label}</span><span class="mock-bar mock-bar--tall"><span class="mock-bar__fill {cls}" style="--p:{p}"></span></span></div>')
        out.append("</div>")
        lic = [t for t in chips if "licens" in t["text"].lower()]
        out.append(chips_row(lic))
        wave = [t for t in chips if t not in lic]
        if wave:
            out.append('<div class="mock-cols" style="grid-template-columns:repeat(3,1fr);margin-top:8px">')
            for k, t in enumerate(wave[:3]):
                out.append(f'<div><span class="mock-wave" aria-hidden="true">' + "<i></i>" * 12 + f'</span><span class="mock-tile__s">{esc(t["text"])}</span></div>')
            out.append("</div>")
    elif "debrief" in s or "table" in s:
        out.append('<div class="mock-bars">')
        pats = ["problem-first", "POV", "comparison", "curiosity"]
        widths = ["78%", "46%", "62%", "34%"]
        n = 4
        for k in range(n):
            out.append(f'<div class="mock-bars__row" style="--i:{k};grid-template-columns:20px 96px 1fr auto"><span class="mock-row__n">{k + 1:02d}</span>{chip(pats[k % 4])}'
                       f'<span class="mock-bar"><span class="mock-bar__fill mock-bar__fill--grey" style="--p:{widths[k % 4]}"></span></span>'
                       + (chip(chips[0]["text"], "mock-chip--jam") if (k == 0 and chips and "carry" in chips[0]["text"]) else "<span></span>") + "</div>")
        out.append("</div>")
    else:
        # keep spec order: 'TikTok', 'Reels', 'Shorts' are one run even when the
        # classifier calls the last of them a row rather than a chip
        want = max(find_row_count(spec), 3)
        labels = [t for t in toks if t["kind"] in ("row", "chip") and t not in tags][:want]
        if not labels:
            labels = rows or [t for t in chips if t not in tags]
        marks = ["38%", "52%", "30%"]
        out.append('<div class="mock-bars">')
        for k, t in enumerate(labels[:3]):
            tag = f'<span class="mock-row__v">{esc(tags[k]["text"])}</span>' if k < len(tags) else "<span></span>"
            as_chip = t["kind"] == "chip" or sum(1 for x in labels if x["kind"] == "chip") >= 2
            lab = chip(t["text"], "mock-chip--ink" if ("ink" in t["marks"] or k == 0 and "filled black" in s) else "") if as_chip else f'<span>{esc(t["text"])}</span>'
            out.append(f'<div class="mock-bars__row" style="--i:{k}">{lab}<span class="mock-bar"><span class="mock-bar__fill mock-bar__fill--grey" style="--p:100%"></span><span class="mock-bar__mark" style="--p:{marks[k % 3]}"></span></span>{tag}</div>')
        out.append("</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def timeline_bar_card(spec: str, toks: list[dict], width: int | None) -> str:
    labels = [t for t in toks if t["kind"] in ("row", "chip", "label")]
    out = [card_open(None, None, "", width)]
    out.append('<div style="padding:18px 0 8px"><div class="mock-bar mock-bar--tall" style="overflow:visible"><span class="mock-bar__fill" style="--p:58%"></span>'
               '<span class="mock-bar__mark" style="--p:52%;height:18px;top:-4px"></span>'
               '<span style="position:absolute;left:60%;right:0;top:3px;border-top:1px dashed var(--k20)"></span></div>')
    out.append('<div class="mock-seg__l" style="margin-top:10px">' + "".join(f"<span>{esc(t['text'])}</span>" for t in labels[:4]) + "</div></div>")
    rest = labels[4:]
    if rest:
        out.append('<div class="mock-rows">' + "".join(row_html(t, k, {}) for k, t in enumerate(rest)) + "</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def flow_card(spec: str, toks: list[dict], width: int | None) -> str:
    titles = [t for t in toks if t["kind"] == "title"]
    nodes = [t for t in toks if t["kind"] in ("row", "chip", "label")]
    out = [card_open(titles[0]["text"] if titles else None, None, "", width), '<div class="mock-flow">']
    for k, t in enumerate(nodes):
        cls = "mock-flow__node" + (" mock-flow__node--jam" if "jam" in t["marks"] else "")
        if k:
            out.append('<span class="mock-flow__arrow" aria-hidden="true">→</span>')
        if t["kind"] == "chip":
            out.append(chip(t["text"]))
        else:
            out.append(f'<span class="{cls}">{esc(t["text"])}</span>')
    out.append("</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def feed_card(spec: str, toks: list[dict], width: int | None) -> str:
    s = spec.lower()
    out = [card_open(None, None, "", width), '<div class="mock-feed">']
    handle = next((t for t in toks if t["text"].startswith("@")), None)
    out.append(f'<div class="mock-feed__head"><span class="mock-avatar" aria-hidden="true"></span><span>{esc(handle["text"]) if handle else "@creator"}</span></div>')
    label = next((t for t in toks if "paid partnership" in t["text"].lower()), None)
    if label:
        out.append(f'<p class="mock-label" style="margin:0">{esc(label["text"])}</p>')
    if "video area" in s or "9:16" in s:
        out.append('<div class="mock-feed__video" aria-hidden="true"></div>')
    caption = next((t for t in toks if t["text"].lower().endswith("#ad")), None)
    out.append(f'<div class="mock-lines"><span class="mock-line mock-line--w80"></span>'
               + (f'<span style="font-size:12px;color:var(--grey)">{esc(caption["text"])}</span>' if caption else '<span class="mock-line mock-line--w45"></span>') + "</div>")
    if "heart" in s:
        out.append('<div class="mock-feed__icons" aria-hidden="true"><svg viewBox="0 0 18 18"><path d="M9 15s-6-3.6-6-8a3 3 0 0 1 6-1 3 3 0 0 1 6 1c0 4.4-6 8-6 8z"/></svg>'
                   '<svg viewBox="0 0 18 18"><path d="M3 4h12v8H8l-3 3v-3H3z"/></svg><svg viewBox="0 0 18 18"><path d="M3 14l12-6L3 2v4l8 2-8 2z"/></svg></div>')
    out.append(chips_row([t for t in toks if t["kind"] == "chip" and t is not label]))
    out.append("</div>")
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def thumbs_card(spec: str, toks: list[dict], width: int | None, opts: dict) -> str:
    s = spec.lower()
    titles = [t for t in toks if t["kind"] == "title"]
    out = [card_open(titles[0]["text"] if titles else None, None, "", width)]
    labels = [t for t in toks if re.search(r"(labelled|the first labelled|then)\s*$", t["before"]) or re.match(r"^\s*(,|and)\s*$", t["before"][-5:]) and t["kind"] == "chip"]
    if "four small phone frames" in s:
        labels = [t for t in toks if t["kind"] in ("chip", "row")][:4]
    if not labels:
        labels = [t for t in toks if t["kind"] == "chip"][:2]
    out.append('<div class="mock-thumbs">')
    for k, t in enumerate(labels):
        cls = "mock-thumb mock-thumb--lg" + (" mock-thumb--jam" if k == 0 and "jam outline" in s else "")
        out.append(f'<span class="{cls}" aria-hidden="true"><span class="mock-thumb__l">{esc(t["text"])}</span></span>')
    out.append("</div>")
    rest = [t for t in toks if t not in labels and t["kind"] not in ("title", "footer")]
    if any(t["kind"] == "label" for t in rest):
        out.append(cols_card(spec, [t for t in toks if t not in labels and t["kind"] != "title"], None, opts).split('class="mock-card"', 1)[1].split(">", 1)[1].rsplit("</div>", 1)[0])
    out.append(card_close([t for t in toks if t["kind"] == "footer"]))
    return "".join(out)


def creator_stack(spec: str, toks: list[dict], width: int | None) -> str:
    """Casting hero: three creator cards with avatar, name · city, three chips."""
    name = next((t for t in toks if "·" in t["text"] and t["kind"] == "row"), None)
    chips = [t for t in toks if t["kind"] == "chip"][:3]
    short = next((t for t in toks if "shortlisted" in t["text"].lower()), None)
    out = ['<div class="mock-stage mock-stage--col" style="gap:10px">']
    for k in range(3):
        label = (name["text"] if name else "creator A · London").replace("creator A", f"creator {'ABC'[k]}")
        parts = split_parts(label)
        sl = chip(short["text"], "mock-chip--jam") if (short and k < 2) else ""
        out.append(f'<div class="mock-card" style="--w:300px;padding:14px 16px"><div class="mock-row" style="--i:{k};border-top:0;min-height:0;padding:0"><span class="mock-avatar" aria-hidden="true"></span>'
                   f'<span class="mock-row__t">{esc(parts[0])}</span><span class="mock-row__v">{esc(" · ".join(parts[1:]))}</span>{sl}</div>'
                   f'<div class="mock-chips" style="padding-bottom:0">{"".join(chip(t["text"]) for t in chips)}</div></div>')
    strip = next((t for t in toks if "strip" in t["before"].lower()[-20:]), None)
    if strip:
        out.append(f'<p class="mock-strip">{esc(strip["text"])}</p>')
    out.append("</div>")
    return "".join(out)


def build_mock(spec: str, hero: bool = False) -> str:
    """Pick a mock component for a spec string and render it into a .page-panel."""
    s = spec.lower()
    toks = classify(spec)
    w, h = dims(spec, (420, 420) if hero else (400, 300))
    opts = {
        "val_chips": "status chip" in s or "chip on the right" in s,
        "avatars": ("avatar" in s and "phone" not in s and "in-feed" not in s and "caption preview" not in s) or "roster list" in s,
        "checkboxes": "checkbox" in s,
        "files": "file list" in s or "file icon" in s,
        "toggles": "toggle drawn" in s,
        "numbered": ("numbered row" in s or "numbered stub" in s) and "rows 0" not in s,
    }
    parts: list[str] = []
    side_re = re.compile(r"(To its right|Beside it|To the right)\b", re.I)
    main_spec, side_spec = spec, None
    m = side_re.search(spec)
    if m:
        main_spec, side_spec = spec[:m.start()], spec[m.start():]
    main_toks = classify(main_spec)
    strip = next((t for t in toks if re.search(r"(strip reads|strip:)\s*$", t["before"].lower())), None)
    ticker = [t for t in toks if "ticker" in spec.lower() and spec.lower().index("ticker") < t["before"].__len__() + spec.lower().index(t["text"].lower()) if t["text"].lower() in spec.lower()] if "ticker" in s else []

    if "creator cards sliding" in s:
        return f'<div class="page-panel">{creator_stack(spec, toks, w)}</div>'

    if "phone frame" in s and ("rec" in s or "timecode" in s) and not ("split" in s):
        phone = phone_html(main_spec, hero, 14, main_toks)
        side = ""
        if side_spec:
            st = classify(side_spec)
            side = list_card(side_spec, st, 320 if hero else 250, {"val_chips": False}, "mock-card--sm" if not hero else "")
        elif [t for t in toks if t["kind"] == "row"]:
            side = list_card(spec, toks, 250, {"val_chips": False}, "mock-card--sm")
        return f'<div class="page-panel"><div class="mock-stage">{phone}{side}</div></div>'

    if "caption block" in s and "phone frame" in s:
        cap = next((t for t in toks if t["kind"] in ("row", "bubble") and len(t["text"]) > 12), None)
        chips = [t for t in toks if t["kind"] == "chip"]
        inner = (f'<div class="mock-phone mock-phone--lg" aria-hidden="true" style="width:170px"><span class="mock-phone__zone mock-phone__zone--top"></span>'
                 f'<span class="mock-phone__zone mock-phone__zone--side"></span><span class="mock-phone__caption">{esc(cap["text"]) if cap else ""}</span></div>')
        return f'<div class="page-panel"><div class="mock-stage mock-stage--col">{inner}{chips_row(chips)}</div></div>'

    if "in-feed ad" in s or "caption preview" in s:
        card = feed_card(main_spec, main_toks, w)
        side = ""
        if side_spec:
            side = list_card(side_spec, classify(side_spec), 260, {"val_chips": False}, "mock-card--sm")
        return f'<div class="page-panel"><div class="mock-stage">{card}{side}</div></div>'

    # \btrack\b, not "track" — "Tracked on the brief" must not claim this branch
    if re.search(r"\btracks?\b", s) or ("timeline" in s and ("clip" in s or "blocks" in s)):
        card = track_card(main_spec, main_toks, w, hero)
        return f'<div class="page-panel"><div class="mock-stage">{card}</div></div>'

    if "timeline bar" in s or ("segment" in s and "timeline" in s):
        return f'<div class="page-panel"><div class="mock-stage">{timeline_bar_card(spec, toks, w)}</div></div>'

    if "progress row" in s or ("timeline" in s and "tick" in s) or ("small timeline" in s):
        return f'<div class="page-panel"><div class="mock-stage">{steps_card(spec, toks, w)}</div></div>'

    if "grid" in s and "×" in spec:
        return f'<div class="page-panel"><div class="mock-stage">{grid_card(spec, toks, w)}</div></div>'

    if "seals" in s:
        return f'<div class="page-panel"><div class="mock-stage">{seals_card(spec, toks, w)}</div></div>'

    if "kit list" in s:
        return f'<div class="page-panel"><div class="mock-stage">{kit_card(spec, toks, w)}</div></div>'

    if "level bars" in s or "timing bar" in s or "thin bar" in s or "relative bars" in s or "horizontal bar" in s:
        return f'<div class="page-panel"><div class="mock-stage">{bars_card(spec, toks, w)}</div></div>'

    if "flow" in s and "→" in spec:
        return f'<div class="page-panel"><div class="mock-stage">{flow_card(spec, toks, w)}</div></div>'

    if "reference thumbnails" in s or "four small phone frames" in s:
        return f'<div class="page-panel"><div class="mock-stage">{thumbs_card(spec, toks, w, opts)}</div></div>'

    if "split in two" in s or "split:" in s or "two columns" in s or "two column blocks" in s or "split" in s:
        return f'<div class="page-panel"><div class="mock-stage">{cols_card(spec, toks, w, opts)}</div></div>'

    # highlighted sentence cards (THE ONE THING / hook line)
    extra_top = ""
    if "highlight" in s:
        first_label = next((t for t in toks if t["kind"] == "label"), None)
        serif = "serif" in s
        tag = next((t for t in toks if t["kind"] == "chip" and re.match(r"^~?\d", t["text"])), None)
        tag_html = f' <span class="mock-chip" style="margin-left:8px">{esc(tag["text"])}</span>' if tag else ""
        hl = (f'<p class="mock-hl{" mock-hl--serif" if serif else ""}"><span class="mock-line mock-line--w80 mock-line--dark" style="display:inline-block;width:70%;height:{8 if serif else 6}px;vertical-align:middle"></span>{tag_html}</p>')
        extra_top = (f'<p class="mock-label">{esc(first_label["text"])}</p>' if first_label else "") + hl
        toks = [t for t in toks if t is not first_label and t is not tag]
    card = list_card(main_spec, [t for t in toks if t in main_toks or t["kind"] == "footer"] if side_spec else toks, w, opts)
    if extra_top:
        card = card.replace('</div>', '</div>' + extra_top, 1) if '<div class="mock-head">' in card else card.replace('>', '>' + extra_top, 1)
    side = ""
    if side_spec:
        side = list_card(side_spec, classify(side_spec), 260 if hero else 220, {"val_chips": False}, "mock-card--sm")
    below = ""
    if "ticker" in s:
        tick_toks = [t for t in classify(spec[s.index("ticker"):])]
        below = '<div class="mock-ticker" aria-hidden="true">' + "".join(f"<span>{esc(t['text'])}</span>" for t in tick_toks[:4]) + "</div>"
        card = card  # ticker lines are not part of the card
    if strip:
        below += f'<p class="mock-strip">{esc(strip["text"])}</p>'
    stage_cls = "mock-stage mock-stage--col" if (below and not side) else "mock-stage"
    if below and side:
        return f'<div class="page-panel"><div class="mock-stage mock-stage--col"><div class="mock-stage" style="padding:0">{card}{side}</div>{below}</div></div>'
    return f'<div class="page-panel"><div class="{stage_cls}">{card}{side}{below}</div></div>'


# ---------------------------------------------------------------------------
# problems icons: line drawings composed from keywords (viewBox 320×200)
# ---------------------------------------------------------------------------

def _bubble(x, y, w, h, tail="bl", lines=2, dotted=False):
    r = 10
    p = [f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}"/>']
    if tail == "bl":
        p.append(f'<path d="M{x + 18} {y + h}v14l14-14"/>')
    else:
        p.append(f'<path d="M{x + w - 32} {y + h}v14l-14-14"/>')
    if dotted:
        p.append(f'<path d="M{x + 18} {y + h / 2}h{w - 36}" stroke-dasharray="3 5"/>')
    else:
        for i in range(lines):
            p.append(f'<path d="M{x + 18} {y + 18 + i * 12}h{w - 36 - i * 22}"/>')
    return "".join(p)


def _doc(x, y, w, h, lines=3, fold=True):
    p = []
    if fold:
        p.append(f'<path d="M{x} {y}h{w - 18}l18 18v{h - 18}H{x}z"/><path d="M{x + w - 18} {y}v18h18"/>')
    else:
        p.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6"/>')
    for i in range(lines):
        p.append(f'<path d="M{x + 16} {y + 30 + i * 14}h{w - 32 - (i % 2) * 16}"/>')
    return "".join(p)


def _phone(x, y, w, h, r=10):
    return (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}"/><path d="M{x + w / 2 - 8} {y + 8}h16"/>'
            f'<path d="M{x + w / 2 - 8} {y + h - 7}h16"/>')


def _clock(cx, cy, r):
    return (f'<circle cx="{cx}" cy="{cy}" r="{r}"/><path d="M{cx} {cy - r * .6}v{r * .6}h{r * .45}"/>'
            f'<path d="M{cx} {cy - r}v4M{cx} {cy + r}v-4M{cx - r} {cy}h4M{cx + r} {cy}h-4"/>')


def _warning(cx, cy, s):
    return (f'<path d="M{cx} {cy - s}l{s} {s * 1.7}H{cx - s}z"/><path d="M{cx} {cy - s * .3}v{s * .5}"/>'
            f'<circle cx="{cx}" cy="{cy + s * .45}" r="1.2" fill="currentColor"/>')


def _calendar(x, y, w, h, cross=False, circle=False):
    p = [f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6"/><path d="M{x} {y + 20}h{w}"/><path d="M{x + 18} {y - 8}v14M{x + w - 18} {y - 8}v14"/>']
    for r in range(3):
        for cc in range(5):
            p.append(f'<circle cx="{x + 16 + cc * (w - 32) / 4}" cy="{y + 36 + r * 16}" r="1" fill="currentColor"/>')
    if cross:
        cx, cy = x + 16 + 2 * (w - 32) / 4, y + 52
        p.append(f'<path d="M{cx - 7} {cy - 7}l14 14M{cx + 7} {cy - 7}l-14 14"/>')
    return "".join(p)


def _lines(x, y, w, n, gap=11):
    return "".join(f'<path d="M{x} {y + i * gap}h{w}"/>' for i in range(n))


def _check(cx, cy, r, ticked=True):
    p = f'<circle cx="{cx}" cy="{cy}" r="{r}"/>'
    if ticked:
        p += f'<path d="M{cx - r * .45} {cy}l{r * .3} {r * .3}l{r * .6} -{r * .6}"/>'
    return p


def _arrow(x1, y1, x2, y2):
    import math
    a = math.atan2(y2 - y1, x2 - x1)
    h = 8
    return (f'<path d="M{x1} {y1}L{x2} {y2}"/><path d="M{x2 - h * math.cos(a - .5)} {y2 - h * math.sin(a - .5)}L{x2} {y2}'
            f'L{x2 - h * math.cos(a + .5)} {y2 - h * math.sin(a + .5)}"/>')


def _play(cx, cy, s):
    return f'<path d="M{cx - s * .5} {cy - s * .7}v{s * 1.4}l{s * 1.1} -{s * .7}z"/>'


def _question(cx, cy, s):
    return (f'<path d="M{cx - s * .5} {cy - s * .4}a{s * .5} {s * .5} 0 1 1 {s * .7} {s * .5}c-{s * .2} {s * .15}-{s * .2} {s * .3}-{s * .2} {s * .45}"/>'
            f'<circle cx="{cx}" cy="{cy + s * .95}" r="1.2" fill="currentColor"/>')


def _face(cx, cy, r):
    return f'<circle cx="{cx}" cy="{cy - r * .35}" r="{r * .38}"/><path d="M{cx - r * .8} {cy + r}c{r * .1}-{r * .7} {r * .4}-{r * .95} {r * .8}-{r * .95}s{r * .7} {r * .25} {r * .8} {r * .95}"/>'


def _profile(cx, cy, r):
    return f'<circle cx="{cx}" cy="{cy}" r="{r}"/>{_face(cx, cy + r * .1, r * .62)}'


ICONS = [
    ("dotted line", lambda: _bubble(100, 52, 120, 74, "bl", dotted=True)),
    ("warning triangle", lambda: _doc(112, 40, 84, 104, 3) + _warning(212, 60, 16)),
    ("three overlapping phone frames", lambda: _phone(96, 52, 52, 96) + _phone(132, 40, 60, 108) + _phone(176, 60, 46, 84)),
    ("contract page with a clock", lambda: _doc(112, 40, 84, 104, 3) + _clock(210, 128, 22)),
    ("skip arrow", lambda: _phone(118, 44, 66, 112) + _arrow(150, 120, 214, 56) + f'<path d="M214 56v18M214 56h-18"/>'),
    ("identical short lines", lambda: _lines(112, 44, 96, 8, 13)),
    ("small script page inside", lambda: _bubble(94, 44, 132, 96, "bl", lines=0) + _doc(140, 62, 40, 56, 2, fold=False)),
    ("scissors", lambda: f'<rect x="76" y="70" width="168" height="60"/>' + "".join(f'<rect x="{84 + i * 40}" y="78" width="30" height="44"/>' for i in range(4)) + f'<path d="M104 60l24 74M128 60l-24 74"/><circle cx="98" cy="140" r="6"/><circle cx="134" cy="140" r="6"/>'),
    ("mismatched second frame", lambda: _phone(92, 44, 60, 112) + _face(122, 96, 20) + f'<rect x="170" y="62" width="64" height="76" rx="4" stroke-dasharray="4 5"/>' + _face(202, 96, 20)),
    ("invoice pages fanned", lambda: "".join(f'<g transform="rotate({-16 + i * 8} 160 150)">{_doc(128, 50, 64, 90, 3)}</g>' for i in range(5))),
    ("empty signature line", lambda: _doc(112, 40, 96, 110, 2) + f'<path d="M128 126h64"/><path d="M130 122c8-6 10 4 16-4s10 6 16-2" stroke-dasharray="2 3"/>'),
    ("crossed-out day", lambda: _calendar(104, 56, 112, 90, cross=True)),
    ("question mark beside", lambda: _phone(104, 44, 70, 116) + _play(139, 102, 20) + _question(214, 92, 18)),
    ("one unticked line", lambda: _doc(104, 40, 112, 116, 0, fold=False) + "".join(_check(124, 62 + i * 24, 7, ticked=(i != 2)) + f'<path d="M140 {62 + i * 24}h56"/>' for i in range(4))),
    ("crossed-out sound wave", lambda: f'<rect x="132" y="44" width="28" height="56" rx="14"/><path d="M118 88a28 28 0 0 0 56 0M146 116v22M130 138h32"/><path d="M196 62a26 26 0 0 1 0 44M186 74a12 12 0 0 1 0 20"/><path d="M182 58l32 52"/>'),
    ("unlabelled file icons", lambda: f'<path d="M84 72h44l12 12h96v64H84z"/>' + "".join(f'<path d="M{110 + i * 40} 132v-30h20l8 8v22z"/>' for i in range(3))),
    ("play triangle inside a circle", lambda: f'<circle cx="150" cy="100" r="44"/>' + _play(150, 100, 22) + _clock(206, 128, 18)),
    ("open padlock", lambda: f'<rect x="96" y="92" width="56" height="44" rx="6"/><path d="M108 92V78a16 16 0 0 1 32 0"/><circle cx="124" cy="114" r="4"/>' + _profile(202, 100, 30)),
    ("arrow pointing at the gap", lambda: _doc(112, 40, 92, 110, 0) + _lines(128, 68, 60, 2, 14) + f'<path d="M128 110h60" stroke-dasharray="3 4"/>' + _lines(128, 124, 60, 1) + _arrow(238, 110, 194, 110)),
    ("tag icon crossed out", lambda: _bubble(92, 46, 136, 88, "bl", lines=0) + f'<path d="M136 74l22-2 22 22-20 20-22-22z"/><circle cx="152" cy="84" r="3"/><path d="M128 120l64-56"/>'),
    ("blank line where a list should be", lambda: _doc(112, 40, 96, 116, 0) + _lines(128, 66, 60, 2, 14) + f'<path d="M128 100h64" stroke-dasharray="3 4"/><path d="M128 114h64" stroke-dasharray="3 4"/>'),
    ("no date circled", lambda: _calendar(104, 56, 112, 90)),
    ("not-equal sign", lambda: _doc(74, 52, 70, 92, 3) + _doc(178, 52, 70, 92, 3) + f'<path d="M148 90h26M148 104h26M166 84l-10 26"/>'),
    ("speech bubble containing a question mark", lambda: _profile(120, 100, 32) + _bubble(166, 56, 72, 54, "bl", lines=0) + _question(202, 74, 14)),
    ("envelope", lambda: f'<rect x="96" y="60" width="120" height="80" rx="6"/><path d="M96 66l60 46 60-46"/>' + f'<circle cx="216" cy="62" r="18"/>' + _question(216, 54, 10)),
    ("heart and a bar chart", lambda: _phone(92, 40, 128, 120, 12) + f'<path d="M124 106s-16-9-16-20a8 8 0 0 1 16-2 8 8 0 0 1 16 2c0 11-16 20-16 20z"/><path d="M106 78l36 36"/>' + f'<path d="M164 116V96M180 116V84M196 116V100M156 116h48"/>'),
    ("three tiles in a row", lambda: "".join(f'<rect x="{80 + i * 60}" y="70" width="48" height="60" rx="6"{" stroke-width=\"2\"" if i == 1 else ""}/>' for i in range(3)) + f'<circle cx="164" cy="100" r="6"/>'),
    ("document going into a folder", lambda: _doc(96, 40, 56, 72, 2) + _arrow(160, 76, 188, 76) + f'<path d="M188 70h28l8 8h44v58h-80z"/>'),
    ("presentation slide", lambda: f'<rect x="80" y="52" width="120" height="80" rx="4"/><path d="M96 72h60M96 88h44M140 132v18M124 150h32"/>' + f'<circle cx="228" cy="80" r="12"/><path d="M212 140c1-22 8-32 16-32s15 10 16 32"/><path d="M244 110l14-8"/>'),
    ("overflowing", lambda: f'<path d="M100 60h120v70H128l-14 14v-14h-14z"/><path d="M116 78h140M116 94h130M116 110h122"/>'),
    ("name badge", lambda: f'<rect x="92" y="64" width="112" height="72" rx="8"/><path d="M132 64v-12h32v12"/><circle cx="118" cy="100" r="10"/><path d="M140 94h44M140 108h30"/>' + _clock(222, 128, 18) + f'<path d="M216 152h12" stroke-dasharray="2 2"/>'),
    ("lower-third", lambda: _phone(118, 40, 84, 124, 12) + f'<rect x="124" y="118" width="72" height="18" rx="2"/><path d="M130 127h40"/><path d="M124 140h72"/>'),
    ("starburst", lambda: _phone(118, 44, 84, 116, 12) + f'<path d="M198 56l6-16 6 16 16 6-16 6-6 16-6-16-16-6z"/>'),
    ("hidden behind the interface", lambda: _phone(118, 44, 84, 116, 12) + f'<rect x="126" y="120" width="68" height="16" rx="2" stroke-dasharray="3 4"/><path d="M124 130h72M130 148h30M150 60h30"/>'),
    ("six identical copies", lambda: "".join(f'<g transform="translate({i * 22} {i * 6})">{_doc(84, 44, 52, 66, 2)}</g>' for i in range(6))),
    ("circular arrow", lambda: f'<path d="M190 100a40 40 0 1 1-12-28"/>' + _arrow(178, 66, 186, 74) + f'<path d="M144 92h6v16M143 108h14"/>'),
    ("phone", lambda: _phone(118, 44, 84, 116, 12)),
    ("document", lambda: _doc(112, 40, 96, 116, 3)),
    ("bubble", lambda: _bubble(100, 52, 120, 74, "bl")),
]


def problem_icon(desc: str) -> str:
    d = desc.lower()
    body = None
    for key, fn in ICONS:
        if key in d:
            body = fn()
            break
    if body is None:
        body = _doc(112, 40, 96, 116, 3)
    return (f'<svg class="page-icon page-problem__icon" viewBox="0 0 320 200" aria-hidden="true" focusable="false">'
            f'{body}<path d="M40 178h240"/></svg>')


# ---------------------------------------------------------------------------
# page templates
# ---------------------------------------------------------------------------

def head(meta: list[tuple[str, str]]) -> str:
    lines = [f"<!-- {k}: {v} -->" for k, v in meta]
    lines.append(GENERATED)
    lines += ["{{include:partials/head.html}}", "{{include:partials/nav.html}}", "{{include:partials/icons.html}}"]
    return "\n".join(lines) + "\n"


TAIL = "{{include:partials/page-cta.html}}\n</main>\n{{include:partials/footer.html}}\n{{include:partials/scripts.html}}\n"


def render_index(data: dict) -> str:
    idx = data["index"]
    meta = [
        ("title", c("index.title")),
        ("description", c("index.description")),
        ("nav", "light"), ("nav-fill", "bg-white"), ("body-class", "svc svc--index"),
        ("cta-h2", c("index.cta_card.h2")), ("cta-p", c("index.cta_card.p")),
        ("cta-label", c("index.cta_card.button.label")), ("cta-href", c("index.cta_card.button.href")),
    ]
    out = [head(meta), '<main class="page svc svc--index" data-theme="light">']
    # hero
    out.append('<section class="page-section page-section--hero"><div class="page-hero"><div class="page-hero__copy">')
    out.append(f'<p class="page-eyebrow page-eyebrow--caps page-hero__eyebrow">{c("index.eyebrow")}</p>')
    out.append(f'<h1 class="page-hero__title">{c("index.h1")}</h1>')
    out.append(f'<p class="page-hero__intro">{c("index.intro")}</p>')
    out.append(f'<div class="page-hero__cta">{btn(c("index.cta.label"), c("index.cta.href"))}</div>')
    out.append("</div></div></section>")
    # image + platforms
    out.append('<section class="page-section page-section--image">')
    out.append(f'<img class="page-image" src="{c("index.image.src")}" alt="{c("index.image.alt")}" width="1864" height="1048" decoding="async" fetchpriority="high">')
    out.append("{{include:partials/platforms-row.html}}")
    out.append("</section>")
    # groups
    out.append('<section class="page-section page-section--list">')
    for g, group in enumerate(idx["groups"]):
        out.append('<div class="page-group">')
        out.append(eyebrow_split(c(f"index.groups.{g}.eyebrow"), f'<h2 class="page-h2">{c(f"index.groups.{g}.h2")}</h2>', "page-list__head"))
        out.append('<ul class="page-list">')
        for k, item in enumerate(group["items"]):
            p = f"index.groups.{g}.items.{k}"
            out.append(f'<li><a class="page-list__row" href="/services/{item["slug"]}">'
                       f'<span class="page-list__n">{c(p + ".n")}</span>'
                       f'<h3 class="page-list__name">{c(p + ".name")}</h3>'
                       f'<p class="page-list__blurb">{c(p + ".blurb")}</p>'
                       f'<span class="page-list__explore arrow-link arrow-link--nudge">{c(p + ".explore")}{ARROW}</span></a></li>')
        out.append("</ul></div>")
    out.append("</section>")
    # films (reserved slots)
    out.append('<section class="page-section page-section--sand">')
    out.append(eyebrow_split(c("index.films.eyebrow"), f'<h2 class="page-h2">{c("index.films.h2")}</h2>'))
    out.append('<div class="page-media">')
    for k, film in enumerate(idx["films"]["items"]):
        p = f"index.films.items.{k}"
        out.append('<div class="page-media__card">'
                   f'<div class="page-media__frame reserved reserved--card" role="img" aria-label="{c(p + ".title")} — {c(p + ".note")}">'
                   '<div class="reserved__area"><span class="reserved__phone reserved__phone--lg" aria-hidden="true"></span></div>'
                   f'<span class="tag-soon">{c(p + ".note")}</span></div>'
                   f'<div class="page-media__meta"><div><p class="page-media__eyebrow">{c(p + ".eyebrow")}</p><h3 class="page-media__title">{c(p + ".title")}</h3></div>'
                   f'<span class="page-media__action arrow-link" aria-disabled="true">{c(p + ".action")}{ARROW}</span></div></div>')
    out.append("</div></section>")
    out.append(TAIL)
    return "\n".join(out)


def render_page(data: dict, i: int, item: dict) -> str:
    p = f"items.{i}"
    meta = [
        ("title", c(p + ".title")),
        ("description", c(p + ".description")),
        ("nav", "light"), ("nav-fill", "bg-white"), ("body-class", f"svc svc--{item['slug']}"),
        ("cta-h2", c(p + ".cta.h2")), ("cta-p", c(p + ".cta.p")),
        ("cta-label", c(p + ".cta.button.label")), ("cta-href", c(p + ".cta.button.href")),
    ]
    out = [head(meta), f'<main class="page svc svc--{item["slug"]}" data-theme="light">']
    # hero
    out.append('<section class="page-section page-section--hero-split"><div class="page-hero page-hero--split"><div class="page-hero__copy">')
    out.append(f'<p class="page-hero__crumb"><a href="/services">{{{{content:nav.left.0.label|Services}}}}</a><span aria-hidden="true">/</span>'
               f'<span class="page-hero__crumb-current">{c(p + ".eyebrow")}</span></p>')
    out.append(f'<h1 class="page-hero__title">{c(p + ".h1")}</h1>')
    out.append(f'<p class="page-hero__intro">{c(p + ".intro")}</p>')
    out.append(f'<div class="page-hero__cta">{btn(c("cta_button.label"), c("cta_button.href"))}</div>')
    out.append('</div><div class="page-hero__visual" aria-hidden="true">')
    out.append(build_mock(item["hero_visual"], hero=True))
    out.append("</div></div>")
    out.append('<div class="page-hero__platforms">{{include:partials/platforms-row.html}}</div></section>')
    # statement + facts
    out.append('<section class="page-section page-section--stats page-stats">')
    out.append(f'<h2 class="page-h2 page-stats__h2">{c(p + ".statement")}</h2><div class="page-stats__row">')
    for k, fact in enumerate(item["facts"]):
        fp = f"{p}.facts.{k}"
        num = str(fact["num"]).strip()
        if re.fullmatch(r"\d+", num):
            num_html = f'<span data-count="{int(num)}">{c(fp + ".num")}</span>'
        else:
            num_html = f'<span>{c(fp + ".num")}</span>'
        out.append(f'<div class="page-stat"><p class="page-stat__num">{num_html}<span>{c(fp + ".suffix")}</span></p>'
                   f'<p class="page-stat__label">{c(fp + ".label")}</p></div>')
    out.append("</div></section>")
    # features
    out.append('<section class="page-section page-section--features"><div class="page-features">')
    for k, feat in enumerate(item["features"]):
        fp = f"{p}.features.{k}"
        flip = " page-feature--flip" if k % 2 == 1 else ""
        out.append(f'<div class="page-feature{flip}"><div class="page-feature__text">')
        out.append(f'<h2 class="page-h2 page-feature__h2">{c(fp + ".title")}</h2><p class="page-feature__p">{c(fp + ".body")}</p>')
        out.append('<div class="page-feature__bullets">')
        for b in range(len(feat["bullets"])):
            bp = f"{fp}.bullets.{b}"
            out.append(f'<details class="page-bullet"{" open" if b == 0 else ""}><summary class="page-bullet__btn"><span class="page-bullet__mark" aria-hidden="true">↳</span>'
                       f'<span>{c(bp + ".title")}</span></summary><p class="page-bullet__body">{c(bp + ".body")}</p></details>')
        out.append("</div>")
        if feat.get("related"):
            out.append(f'<div class="page-feature__related"><a class="page-link" href="{c(fp + ".related.href")}">{c(fp + ".related.label")}</a></div>')
        out.append('</div><div class="page-feature__visual" aria-hidden="true">')
        out.append(build_mock(feat["visual"]))
        out.append("</div></div>")
    out.append("</div></section>")
    # problems
    out.append('<section class="page-section page-section--problems"><div class="page-problems">')
    out.append(f'<div class="page-problems__head"><h2 class="page-h2">{c(p + ".problems_head.h2")}</h2><p class="page-p">{c(p + ".problems_head.p")}</p></div>')
    out.append('<div class="page-problems__grid">')
    for k, prob in enumerate(item["problems"]):
        pp = f"{p}.problems.{k}"
        out.append(f'<div class="page-problem"><div class="page-panel page-problem__tile">{problem_icon(prob["icon"])}</div>'
                   f'<h3 class="page-problem__title">{c(pp + ".title")}</h3><p class="page-problem__body">{c(pp + ".body")}</p></div>')
    out.append("</div></div></section>")
    # steps (sand)
    out.append('<section class="page-section page-section--sand section--sand-s">')
    out.append(eyebrow_split(c(p + ".steps_head.eyebrow"), f'<h2 class="page-h2">{c(p + ".steps_head.h2")}</h2>', "page-split--steps"))
    out.append('<ol class="page-steps">')
    for k in range(len(item["steps"])):
        sp = f"{p}.steps.{k}"
        out.append(f'<li class="page-step"><span class="page-step__n">{k + 1:02d}</span><h3 class="page-step__title">{c(sp + ".title")}</h3><p class="page-step__body">{c(sp + ".body")}</p></li>')
    out.append("</ol></section>")
    # comparison — WHITE on Lance: every ref/pages/product_*.jpg has exactly one
    # sand band on a detail page (the steps strip); the hood grid sits on white.
    out.append('<section class="page-section page-section--compare">')
    out.append(eyebrow_split(c(p + ".comparison_head.eyebrow"),
                             f'<h2 class="page-h2">{c(p + ".comparison_head.h2")}</h2><p class="page-p">{c(p + ".comparison_head.p")}</p>', "page-split--compare"))
    out.append('<div class="page-compare">')
    for k, cell in enumerate(item["comparison"]):
        cp = f"{p}.comparison.{k}"
        link = f'<a class="page-link page-compare__link" href="{c(cp + ".link.href")}">{c(cp + ".link.label")}</a>' if cell.get("link") else ""
        out.append(f'<div class="page-compare__cell"><p class="page-compare__label">{c(cp + ".label")}</p><p class="page-compare__value">{c(cp + ".value")}</p>'
                   f'<p class="page-compare__body">{c(cp + ".body")}</p>{link}</div>')
    out.append("</div></section>")
    # quote + FAQ
    out.append('<section class="page-section page-section--faq">')
    q = item["quote"]
    qp = f"{p}.quote"
    if q.get("kind") == "reserved":
        out.append('<figure class="page-quote page-quote--reserved"><div class="page-quote__body">'
                   f'<blockquote class="page-quote__text">{c(qp + ".text")}</blockquote>'
                   f'<figcaption class="page-quote__attr"><span class="tag-soon">{c(qp + ".name")}</span></figcaption></div>'
                   '<div class="page-quote__media"><span class="reserved__phone reserved__phone--lg" aria-hidden="true"></span></div></figure>')
    else:
        out.append('<figure class="page-quote"><div class="page-quote__body">'
                   f'<blockquote class="page-quote__text">“{c(qp + ".text")}”</blockquote>'
                   f'<figcaption class="page-quote__attr"><p class="page-quote__name">{c(qp + ".name")}</p>'
                   f'<p class="page-quote__role">{c(qp + ".role")} · {c(qp + ".meta")}</p></figcaption></div>'
                   f'<div class="page-quote__media"><img src="{c(qp + ".image.src")}" alt="{c(qp + ".image.alt")}" width="620" height="450" loading="lazy" decoding="async"></div></figure>')
    faq_items = []
    for k in range(len(item["faq"])):
        fq = f"{p}.faq.{k}"
        faq_items.append(f'<details class="page-faq__item"{" open" if k == 0 else ""}><summary class="page-faq__q"><span class="page-faq__mark" aria-hidden="true">↳</span>'
                         f'<span class="page-faq__label">{c(fq + ".q")}</span><span class="page-faq__toggle" aria-hidden="true"></span></summary>'
                         f'<p class="page-faq__a">{c(fq + ".a")}</p></details>')
    out.append(eyebrow_split(c(p + ".faq_head.eyebrow"), f'<h2 class="page-h2">{c(p + ".faq_head.h2")}</h2><div class="page-faq">{"".join(faq_items)}</div>'))
    out.append("</section>")
    out.append(TAIL)
    return "\n".join(out)


def main() -> int:
    data = json.loads(CONTENT.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    target = OUT_DIR / "index.html"
    target.write_text(render_index(data), encoding="utf-8")
    written.append(target)
    for i, item in enumerate(data["items"]):
        target = OUT_DIR / f"{item['slug']}.html"
        target.write_text(render_page(data, i, item), encoding="utf-8")
        written.append(target)
    # remove stale generated pages (a renamed slug) so dist never carries a ghost
    keep = {t.name for t in written}
    for old in OUT_DIR.glob("*.html"):
        if old.name not in keep and GENERATED in old.read_text(encoding="utf-8", errors="ignore"):
            old.unlink()
            print("removed", old.relative_to(ROOT))
    for t in written:
        print("wrote", t.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
