#!/usr/bin/env python3
"""
render_rights_work_book.py — writes the /rights, /work and /book page
templates from content/rights.json, work.json and book.json.

The templates reference copy with {{content:…}} placeholders so the JSON
stays the single source of truth; the renderer only decides *how many* cells,
questions, tiles and cards to stamp out (build.py has no loops) and which
line-drawn icon / platform glyph each item gets. One string is copied
literally because build.py cannot split it: the two-line /work heading
(work.hero.h1 split after work.hero.h1_break_after) — everything else is a
reference. Idempotent; run by build.py before the pages are expanded.

Honesty rules these pages follow (SPEC §8 ranks 2 and 7, §6.7, §9): no
reserved or placeholder proof slots, no invented brand names, no seals or
badge graphics, no count-ups, no background image on /book. Every booking
link is .btn--cta or .cta-link, goes to /book and carries data-cta.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
PAGES = ROOT / "src" / "pages"

GENERATED = "<!-- generated by tools/render_rights_work_book.py — edit content/{name}.json -->"

BASE_URL = "https://hypjam.com"
ORG_ID = BASE_URL + "/#org"  # the Organization node owned by the sitewide schema — reference it, never redefine it here


def T(path: str, fallback=None) -> str:
    """A {{content:…}} placeholder for build.py."""
    if fallback is not None:
        return "{{content:%s|%s}}" % (path, fallback)
    return "{{content:%s}}" % path


def load(name: str) -> dict:
    return json.loads((CONTENT / f"{name}.json").read_text(encoding="utf-8"))


def jsonld(obj) -> str:
    """A literal (already-resolved) JSON-LD <script> tag — no {{content:…}} tokens inside,
    so values pulled from content/*.json can't break JSON escaping (mirrors render_blog.py)."""
    return '<script type="application/ld+json">' + json.dumps(obj, ensure_ascii=False).replace("</", "<\\/") + "</script>"


def breadcrumb(*crumbs) -> dict:
    """crumbs: (name, path) pairs after Home, e.g. breadcrumb(("Work", "/work"))."""
    items = [{"@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL + "/"}]
    for i, (name, path) in enumerate(crumbs, start=2):
        items.append({"@type": "ListItem", "position": i, "name": name, "item": BASE_URL + path})
    return {"@type": "BreadcrumbList", "itemListElement": items}


ARROW = ('<svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true">'
         '<path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" fill="none" stroke="currentColor" '
         'stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
ARROW_11 = ARROW.replace('width="12" height="12"', 'width="11" height="11"')
EXTERNAL = ('<svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true">'
            '<path d="M4.5 2H2v8h8V7.5M7 2h3v3M10 2 5.5 6.5" fill="none" stroke="currentColor" '
            'stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
CHEVRON = ('<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">'
           '<path d="M6 3.2 10.6 8 6 12.8" fill="none" stroke="currentColor" stroke-width="1.4" '
           'stroke-linecap="round" stroke-linejoin="round"/></svg>')
PLUS = ('<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">'
        '<path d="M8 2.5v11M2.5 8h11" fill="none" stroke="currentColor" stroke-width="1.2" '
        'stroke-linecap="round"/></svg>')



def btn(label: str, href: str, cls: str = "btn", ico: str = ARROW_11, cta: str = "") -> str:
    data = f' data-cta="{cta}"' if cta else ""
    return f'<a href="{href}" class="{cls}"{data}>{label}<span class="btn__ico">{ico}</span></a>'


# 24px monoline icons for the rights grid (rights.json grid.cells[].icon)
ICONS = {
    "document":  '<path d="M6 2.5h8l4.5 4.5v14.5H6z"/><path d="M14 2.5V7h4.5"/><path d="M9 12h6M9 15.5h6M9 19h4"/>',
    "signature": '<path d="M3 17.5c2.4-6.2 4-9.5 5.4-9.5 1.6 0 .6 7.5 2.1 7.5 1.6 0 2.9-8.5 4.4-8.5 1.5 0 .5 7.5 2.4 7.5 1.4 0 2.5-1.7 3.7-3.2"/><path d="M3 21h18"/>',
    "tag":       '<path d="M3.5 12.5v-8a1 1 0 0 1 1-1h8l8 8-9 9z"/><circle cx="8" cy="8" r="1.5"/>',
    "checklist": '<rect x="3" y="3.5" width="6" height="6" rx="1"/><path d="m4.8 6.6 1.3 1.3L8.4 5.4"/><path d="M12 6.5h9"/><rect x="3" y="14.5" width="6" height="6" rx="1"/><path d="m4.8 17.6 1.3 1.3 2.3-2.5"/><path d="M12 17.5h9"/>',
    "lock":      '<rect x="4.5" y="10.5" width="15" height="10.5" rx="1.5"/><path d="M8 10.5V7.5a4 4 0 0 1 8 0v3"/><circle cx="12" cy="16" r="1.2"/>',
    "folder":    '<path d="M3 6.5A1.5 1.5 0 0 1 4.5 5H9l2 2h8.5A1.5 1.5 0 0 1 21 8.5v10a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 18.5z"/><path d="M3 10.5h18"/>',
}

# platform ids used in work.json / book.json → sprite glyph (src/partials/icons.html #p-*)
GLYPH = {
    "tiktok": "p-tiktok", "reels": "p-instagram", "ig-reels": "p-instagram", "ig-stories": "p-instagram",
    "shorts": "p-youtube", "yt-shorts": "p-youtube", "snapchat": "p-snapchat", "snap-ads": "p-snapchat",
    "pinterest": "p-pinterest", "pinterest-video": "p-pinterest", "meta-ads": "p-meta", "meta-partnership": "p-meta",
    "tiktok-in-feed": "p-tiktok", "tiktok-spark": "p-tiktok",
}


def glyph(pid: str, cls: str = "") -> str:
    sym = GLYPH.get(pid)
    if not sym:
        return ""
    return f'<svg class="{cls}" viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><use href="#{sym}"/></svg>'


# ---------------------------------------------------------------------------
# /rights
# ---------------------------------------------------------------------------

def rights_page(d: dict) -> str:
    hero, grid, q = d["hero"], d["grid"], d["questions"]

    ld = jsonld({
        "@context": "https://schema.org",
        "@graph": [
            breadcrumb(("Rights", "/rights")),
            {
                "@type": "WebPage",
                "name": hero["h1"],
                "url": BASE_URL + "/rights",
                "description": d["meta"]["description"],
                "inLanguage": "en-GB",
                "publisher": {"@id": ORG_ID},
            },
        ],
    })

    # the four practices as plain text (label + one line). Never drawn as seals or badges:
    # a seal can read as a trust mark (DMCC Act 2024 Sch. 20 para 3).
    practices = []
    for i, _ in enumerate(hero.get("practices", [])):
        practices.append(
            f'        <li class="rights-hero-item"><p class="rights-hero-item-t">{T(f"rights.hero.practices.{i}.label")}</p>'
            f'<p class="rights-hero-item-d">{T(f"rights.hero.practices.{i}.desc")}</p></li>')

    cells = []
    for i, c in enumerate(grid["cells"]):
        icon = ICONS.get(c.get("icon", ""), ICONS["document"])
        cells.append(f'''      <li class="rights-how-cell">
        <div class="rights-how-text">
          <h3 class="rights-how-title t-eyebrow-lg">{T(f"rights.grid.cells.{i}.title")}</h3>
          <span class="dash" aria-hidden="true"></span>
          <p class="rights-how-body">{T(f"rights.grid.cells.{i}.body")}</p>
        </div>
        <svg class="rights-how-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">{icon}</svg>
      </li>''')

    items = []
    for i, it in enumerate(q["items"]):
        link = ""
        if it.get("link"):
            link = (f'\n            <a class="arrow-link rights-acc-link" href="{T(f"rights.questions.items.{i}.link.href")}">'
                    f'{T(f"rights.questions.items.{i}.link.label")}{ARROW}</a>')
        items.append(f'''      <div class="rights-acc-item" data-acc-item>
        <h3 class="rights-acc-h"><button type="button" class="rights-acc-btn" id="rights-acc-b{i}" aria-expanded="false" aria-controls="rights-acc-p{i}" data-acc-btn><span class="rights-acc-q">{T(f"rights.questions.items.{i}.q")}</span><span class="rights-acc-ico" aria-hidden="true">{PLUS}</span></button></h3>
        <div class="rights-acc-panel" id="rights-acc-p{i}" role="region" aria-labelledby="rights-acc-b{i}" data-acc-panel>
          <div class="rights-acc-panel-in">
            <p class="rights-acc-a">{T(f"rights.questions.items.{i}.a")}</p>{link}
          </div>
        </div>
      </div>''')

    nl = "\n"
    return f'''<!-- title: {T("rights.meta.title")} -->
<!-- description: {T("rights.meta.description")} -->
<!-- nav: light -->
<!-- nav-fill: bg-sand-m -->
<!-- body-class: page-rights -->
<!-- head-extra: {ld} -->
{GENERATED.format(name="rights")}
{{{{include:partials/head.html}}}}
{{{{include:partials/nav.html}}}}
{{{{include:partials/icons.html}}}}
<main class="rights-page">

  <!-- hero · sand-m, h1 two lines · p 18/24 grey max-w 600 · the booking button · the four practices as plain text -->
  <section class="rights-hero" data-nav="light" data-nav-fill="bg-sand-m" data-theme="sand-m">
    <div class="rights-hero-inner">
      <h1 class="rights-hero-h1 t-display t-balance">{T("rights.hero.h1")}</h1>
      <p class="rights-hero-sub">{T("rights.hero.sub")}</p>
      {btn(T("rights.hero.cta.label"), T("rights.hero.cta.href"), "btn btn--lg btn--cta rights-hero-cta", ARROW, "rights-hero")}
      <div class="rights-hero-practices">
        <p class="rights-hero-k" id="rights-hero-k">{T("rights.hero.practices_label")}</p>
        <ul class="rights-hero-list" aria-labelledby="rights-hero-k">
{nl.join(practices)}
        </ul>
      </div>
    </div>
  </section>

  <!-- how · the reference site: flex flex-col gap-20 bg-black px-page pb-7 pt-16 · 3×2 hairline grid, cells 327 tall -->
  <section id="rights-how" class="rights-how" data-nav="dark" data-nav-fill="bg-black" data-theme="dark">
    <h2 class="rights-how-h2 t-h2">{T("rights.grid.h2")}</h2>
    <ul class="rights-how-grid">
{nl.join(cells)}
    </ul>
  </section>

  <!-- questions · the reference site: flex gap-12 bg-black px-page py-[120px] max-bp:flex-col · left h2 + p + pill, right accordion -->
  <section class="rights-q" data-nav="dark" data-nav-fill="bg-black" data-theme="dark">
    <div class="rights-q-intro">
      <h2 class="rights-q-h2 t-h2">{T("rights.questions.h2")}</h2>
      <p class="rights-q-p t-body">{T("rights.questions.p")}</p>
      <div class="rights-q-cta">
        <a class="cta-link" href="{T("rights.questions.cta.href")}" data-cta="rights">{T("rights.questions.cta.label")}</a>
        <p class="rights-q-micro">{T("rights.questions.cta.micro")}</p>
      </div>
    </div>
    <div class="rights-acc" data-rights-acc>
{nl.join(items)}
    </div>
  </section>

  <!-- the closing CTA strip ("{T("rights.cta.h2")}" + "{T("rights.cta.button.label")}") is carried by the footer partial (foot-top), as on the reference site -->
</main>
<script>
/* /rights accordion · one item open at a time · height animates via grid-template-rows (43-rights.css) */
(function () {{
  var root = document.querySelector('[data-rights-acc]');
  if (!root) return;
  var items = Array.prototype.slice.call(root.querySelectorAll('[data-acc-item]'));
  function set(item, open) {{
    var b = item.querySelector('[data-acc-btn]');
    if (open) item.classList.add('is-open'); else item.classList.remove('is-open');
    if (b) b.setAttribute('aria-expanded', open ? 'true' : 'false');
  }}
  items.forEach(function (item) {{
    var b = item.querySelector('[data-acc-btn]');
    if (!b) return;
    b.addEventListener('click', function () {{
      var open = !item.classList.contains('is-open');
      items.forEach(function (o) {{ if (o !== item) set(o, false); }});
      set(item, open);
    }});
  }});
}})();
</script>
{{{{include:partials/footer.html}}}}
{{{{include:partials/scripts.html}}}}
'''


# ---------------------------------------------------------------------------
# /work
# ---------------------------------------------------------------------------

def work_page(d: dict) -> str:
    hero, ads, facts, plat, fm = d["hero"], d["ads"], d["facts"], d["platforms"], d["formats"]

    # CollectionPage, not ItemList: the grid is example ads and illustrative format tiles,
    # never dressed up as products or client case studies.
    ld = jsonld({
        "@context": "https://schema.org",
        "@graph": [
            breadcrumb(("Work", "/work")),
            {
                "@type": "CollectionPage",
                "name": hero["h1"],
                "url": BASE_URL + "/work",
                "description": d["meta"]["description"],
                "inLanguage": "en-GB",
                "publisher": {"@id": ORG_ID},
            },
        ],
    })

    # the two-line heading: split literally after h1_break_after (build.py cannot split a string)
    h1 = hero["h1"]
    brk = hero.get("h1_break_after", "")
    if brk and f" {brk} " in f" {h1} ":
        head, _, tail = h1.partition(f"{brk} ")
        line1, line2 = (head + brk).strip(), tail.strip()
    else:
        line1, line2 = h1, ""
    # block spans on desktop, inline below 1024px where a forced break chops the line badly
    h1_html = f'<span class="work-hero-l">{line1}</span>' + (
        f' <span class="work-hero-l">{line2}</span>' if line2 else "")

    # the example ads: poster only until pressed (the inline script below swaps in <video controls>)
    cards = []
    for i, _ in enumerate(ads["items"]):
        p = f"work.ads.items.{i}"
        eager = 'loading="eager" fetchpriority="high"' if i < 2 else 'loading="lazy"'
        cards.append(f'''      <li class="work-ad" id="ad-{T(p + ".id")}">
        <button type="button" class="work-ad-play" data-video="{T(p + ".video")}" aria-label="{T(p + ".play")}">
          <img class="work-ad-poster" src="{T(p + ".poster")}" alt="{T(p + ".alt")}" width="360" height="640" {eager} decoding="async" draggable="false">
          <span class="work-ad-ico" aria-hidden="true"><svg viewBox="0 0 12 12" width="12" height="12"><path d="M3.5 2.2v7.6L9.5 6z" fill="currentColor"/></svg></span>
        </button>
        <p class="work-ad-cap"><span class="work-ad-format">{T(p + ".format")}</span><span class="work-ad-credit">{T(p + ".credit")}</span></p>
      </li>''')

    fact_cells = []
    for i, _ in enumerate(facts["cells"]):
        p = f"work.facts.cells.{i}"
        fact_cells.append(f'''      <li class="work-fact">
        <p class="work-fact-v">{T(p + ".value")}</p>
        <p class="work-fact-l">{T(p + ".label")}</p>
      </li>''')

    groups = []
    for gi, g in enumerate(plat["groups"]):
        tiles = []
        large = gi == 0
        for ti, t in enumerate(g["tiles"]):
            p = f"work.platforms.groups.{gi}.tiles.{ti}"
            gl = glyph(t.get("id", ""), "work-plat-glyph") if large else ""
            tiles.append(f'        <li class="work-plat-tile{"" if large else " work-plat-tile--sm"}"><span class="work-plat-tile-in">{gl}<span class="work-plat-text">{T(p + ".text")}</span></span></li>')
        groups.append(f'''    <div class="work-plat-group">
      <p class="work-plat-label">{T(f"work.platforms.groups.{gi}.label")}</p>
      <ul class="{"work-plat-row" if large else "work-plat-grid"}">
{chr(10).join(tiles)}
      </ul>
    </div>''')

    formats = []
    for i, f in enumerate(fm["formats"]):
        p = f"work.formats.formats.{i}"
        tags = "".join(f'<li class="work-tag">{T(p + f".tags.{k}")}</li>' for k in range(len(f.get("tags", []))))
        formats.append(f'''      <li class="work-format" id="format-{f["id"]}">
        <h3 class="work-format-name t-h3">{T(p + ".name")}</h3>
        <p class="work-format-blurb">{T(p + ".blurb")}</p>
        <ul class="work-format-tags" aria-label="Tags">{tags}</ul>
      </li>''')

    fmt_index = {f["id"]: k for k, f in enumerate(fm["formats"])}
    samples = []
    for i, s in enumerate(fm["samples"]):
        p = f"work.formats.samples.{i}"
        k = fmt_index.get(s.get("format_id"))
        fmt_link = (f'<a class="arrow-link work-sample-format" href="#format-{s["format_id"]}">{T(f"work.formats.formats.{k}.name")}{ARROW}</a>'
                    if k is not None else "")
        samples.append(f'''      <li class="work-sample">
        <div class="work-sample-top"><span class="work-sample-cat">{T(p + ".category")}</span><span class="work-sample-chip">{T(p + ".status")}</span></div>
        <p class="work-sample-hook t-story-quote t-hanging">“{T(p + ".hook")}”</p>
        <p class="work-sample-creator">{T(p + ".creator_brief")}</p>
        <p class="work-sample-note">{T(p + ".note")}</p>
        {fmt_link}
      </li>''')

    nl = "\n"
    return f'''<!-- title: {T("work.meta.title")} -->
<!-- description: {T("work.meta.description")} -->
<!-- nav: dark -->
<!-- nav-fill: bg-black -->
<!-- body-class: page-work -->
<!-- cta-h2: {T("work.cta.h2")} -->
<!-- cta-p: {T("work.cta.p")} -->
<!-- cta-label: {T("work.cta.button.label")} -->
<!-- cta-href: {T("work.cta.button.href")} -->
<!-- head-extra: {ld} -->
{GENERATED.format(name="work")}
{{{{include:partials/head.html}}}}
{{{{include:partials/nav.html}}}}
{{{{include:partials/icons.html}}}}
<main class="work-page">

  <!-- hero · black · the heading and the honest line, then the example ads as a static grid:
       no carousel, no auto-advance, a poster until pressed -->
  <section class="work-hero" data-nav="dark" data-nav-fill="bg-black" data-theme="dark" aria-labelledby="work-h1">
    <div class="work-hero-head">
      <h1 class="work-hero-h1 t-h1" id="work-h1">{h1_html}</h1>
      <div class="work-hero-aside">
        <p class="work-hero-honest">{T("work.hero.honest")}</p>
        <p class="work-hero-cta"><a class="cta-link" href="{T("work.hero.cta.href")}" data-cta="work">{T("work.hero.cta.label")}</a><span class="work-hero-micro">{T("work.hero.cta.micro")}</span></p>
      </div>
    </div>
    <p class="work-ads-k t-eyebrow" aria-hidden="true">{T("work.ads.label")}</p>
    <ul class="work-ads" aria-label="{T("work.ads.list_label")}" data-work-ads>
{nl.join(cards)}
    </ul>
  </section>

  <!-- the three contract clauses · static text, never a count-up -->
  <section class="work-facts" data-nav="light" data-nav-fill="bg-white" data-theme="light" aria-labelledby="work-facts-h2">
    <div class="work-sec-head">
      <p class="work-sec-k t-eyebrow">{T("work.facts.label")}</p>
      <h2 class="t-h2" id="work-facts-h2">{T("work.facts.h2")}</h2>
      <p class="work-sec-p t-body">{T("work.facts.p")}</p>
    </div>
    <ul class="work-facts-grid">
{nl.join(fact_cells)}
    </ul>
  </section>

  <!-- formats · hypjam's own: six formats, then illustrative sample hooks labelled by category -->
  <section class="work-formats" data-nav="light" data-nav-fill="bg-sand-s" data-theme="sand">
    <div class="work-formats-head">
      <p class="eyebrow">{T("work.formats.eyebrow")}</p>
      <h2 class="work-formats-h2 t-h2">{T("work.formats.h2")}</h2>
      <p class="work-formats-intro t-body">{T("work.formats.intro")}</p>
    </div>
    <ul class="work-format-grid">
{nl.join(formats)}
    </ul>
    <div class="work-samples">
      <p class="work-plat-label">{T("work.formats.samples_label")}</p>
      <ul class="work-sample-grid">
{nl.join(samples)}
      </ul>
    </div>
  </section>

  <!-- platforms · label + row of large tiles, label + grid; names set typographically -->
  <section class="work-platforms" data-nav="light" data-nav-fill="bg-white" data-theme="light">
{nl.join(groups)}
  </section>

{{{{include:partials/page-cta.html}}}}
</main>
<script>
/* /work example ads · pressing a poster swaps in the real video (controls, sound) so nothing
   heavy downloads until asked; starting one clip pauses any other playing on the page */
(function () {{
  var root = document.querySelector('[data-work-ads]');
  if (!root) return;
  var vids = [];
  function pauseOthers(cur) {{ vids.forEach(function (v) {{ if (v !== cur && !v.paused) v.pause(); }}); }}
  Array.prototype.forEach.call(root.querySelectorAll('.work-ad-play[data-video]'), function (btn) {{
    btn.addEventListener('click', function () {{
      var src = btn.getAttribute('data-video');
      if (!src) return;
      var img = btn.querySelector('img');
      var v = document.createElement('video');
      v.className = 'work-ad-video';
      v.src = src;
      if (img) {{ v.poster = img.currentSrc || img.src; v.setAttribute('aria-label', img.alt); }}
      v.controls = true; v.playsInline = true; v.setAttribute('playsinline', ''); v.preload = 'auto';
      v.addEventListener('play', function () {{ pauseOthers(v); }});
      vids.push(v);
      pauseOthers(v);
      btn.parentNode.replaceChild(v, btn);
      var p = v.play(); if (p && p.catch) p.catch(function () {{}});
      v.focus();
    }});
  }});
}})();
</script>
{{{{include:partials/footer.html}}}}
{{{{include:partials/scripts.html}}}}
'''


# ---------------------------------------------------------------------------
# /book
# ---------------------------------------------------------------------------

def book_page(d: dict) -> str:
    left, right = d["left"], d["right"]

    # ReserveAction because booking genuinely happens in the embedded cal.com calendar
    # — the target is cal.com's own booking URL, not the ?embed= src.
    ld = jsonld({
        "@context": "https://schema.org",
        "@graph": [
            breadcrumb(("Book", "/book")),
            {
                "@type": "ContactPage",
                "name": left["h1"],
                "url": BASE_URL + "/book",
                "description": d["meta"]["description"],
                "inLanguage": "en-GB",
                "publisher": {"@id": ORG_ID},
                "potentialAction": {
                    "@type": "ReserveAction",
                    "name": "Book a 30-minute call with Avi",
                    "target": {
                        "@type": "EntryPoint",
                        "urlTemplate": left["embed"]["url"],
                        "actionPlatform": [
                            "http://schema.org/DesktopWebPlatform",
                            "http://schema.org/MobileWebPlatform",
                        ],
                    },
                },
            },
        ],
    })

    expect = "".join(f'\n            <li>{T(f"book.left.expect.items.{i}")}</li>' for i in range(len(left["expect"]["items"])))

    # rights as plain-text practices: drawn "seals" can read as accreditation marks
    # (DMCC Act 2024 Sch. 20 para 3), so /book shows no badge graphics.
    rights = [f'          <li>{T(f"book.right.rights.items.{i}.label")}</li>' for i in range(len(right["rights"]["items"]))]
    facts = "".join(f'<li>{T(f"book.left.facts.{i}")}</li>' for i in range(len(left.get("facts", []))))
    after = "".join(f'\n            <li>{T(f"book.left.after.items.{i}")}</li>' for i in range(len(left.get("after", {}).get("items", []))))

    nl = "\n"
    return f'''<!-- title: {T("book.meta.title")} -->
<!-- description: {T("book.meta.description")} -->
<!-- nav: light -->
<!-- nav-fill: bg-sand-s -->
<!-- body-class: page-book -->
<!-- head-extra: <link rel="preconnect" href="https://cal.com"><link rel="preconnect" href="https://app.cal.com" crossorigin>{ld} -->
{GENERATED.format(name="book")}
{{{{include:partials/head.html}}}}
{{{{include:partials/icons.html}}}}
<main class="book-page" data-theme="sand">

  <!-- the reference site's get-started header: lockup left, one small line right, 60px, no nav -->
  <header class="book-header">
    <a href="{T("book.header.logo.href", "/")}" class="book-logo" aria-label="hypjam home"><img src="{T("book.header.logo.file")}" alt="{T("book.header.logo.alt", "hypjam")}" width="860" height="262" decoding="async"></a>
    <a href="{T("book.header.right.href")}" class="book-header-link">{T("book.header.right.label")}</a>
  </header>

  <!-- One column, calendar-first. /book exists to get a call booked and let the
       visitor leave, so the calendar is the page; everything else sits under it. -->
  <section class="book-main">

    <div class="book-intro">
      <h1 class="book-h1 t-display">{T("book.left.h1")}</h1>
      <p class="book-sub">{T("book.left.sub")}</p>
      <ul class="book-facts" aria-label="{T("book.left.facts_label")}">{facts}</ul>
      <p class="book-creator">{T("book.left.creator.text")} <a href="{T("book.left.creator.href")}">{T("book.left.creator.link_label")}</a></p>
    </div>

    <!-- the cal.com embed is rendered straight into the page: no click gate, and it
         works with JavaScript off. 45-book.js only resizes it to cal.com's own height. -->
    <div class="book-embed" data-book-embed data-height="{T("book.left.embed.height_min", "860")}">
      <div class="book-frame" data-book-frame data-lenis-prevent>
        <iframe class="book-iframe" src="{T("book.left.embed.src")}" title="{T("book.left.embed.title")}"
                loading="eager" allow="payment" referrerpolicy="strict-origin-when-cross-origin"></iframe>
      </div>
      <p class="book-fallback"><a href="{T("book.left.embed.fallback.href")}" target="_blank" rel="noopener">{T("book.left.embed.fallback.label")}{EXTERNAL}</a></p>
    </div>

    <div class="book-after">
      <div class="book-expect">
        <h2 class="book-expect-label t-eyebrow">{T("book.left.expect.label")}</h2>
        <ul class="book-expect-list">{expect}
        </ul>
        <h2 class="book-expect-label book-expect-label--next t-eyebrow">{T("book.left.after.label")}</h2>
        <ul class="book-expect-list">{after}
        </ul>
      </div>

      <!-- the founder's quote on plain black with a jam glow drawn in CSS (SPEC S5): never a frame from a clip, never an image -->
      <figure class="book-quote-mini">
        <blockquote class="book-quote-mini-text">&ldquo;{T("book.right.quote.text")}&rdquo;</blockquote>
        <figcaption class="book-quote-mini-cap">
          <img class="book-quote-mini-mark" src="{T("book.right.quote.mark")}" alt="" width="28" height="28" loading="lazy" decoding="async">
          <span><span class="book-quote-mini-name">{T("book.right.quote.name")}</span><span class="book-quote-mini-role">{T("book.right.quote.role")}</span></span>
        </figcaption>
      </figure>
    </div>

    <div class="book-foot">
      <p class="book-note">{T("book.left.privacy.text")} <a href="{T("book.left.privacy.href")}">{T("book.left.privacy.link_label")}</a>.</p>
      <div class="book-rights">
        <h2 class="book-rights-label">{T("book.right.rights.label")}</h2>
        <ul class="book-rights-list">
{nl.join(rights)}
        </ul>
      </div>
    </div>

  </section>
</main>
{{{{include:partials/scripts.html}}}}
'''


def main() -> int:
    PAGES.mkdir(parents=True, exist_ok=True)
    for name, fn in (("rights", rights_page), ("work", work_page), ("book", book_page)):
        html = fn(load(name))
        target = PAGES / f"{name}.html"
        if not target.is_file() or target.read_text(encoding="utf-8") != html:
            target.write_text(html, encoding="utf-8")
        print("wrote", target.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
