#!/usr/bin/env python3
"""render_solutions.py — content/solutions.json → src/pages/solutions/*.html

Writes the solutions index and the nine solution pages as ordinary page
templates (see tools/README.md). Every piece of marketing copy is emitted as
a {{content:solutions.…}} reference so the JSON stays the single source of
truth. The only text baked into the HTML is what the mock builders lift out
of the JSON's own `mocks.<name>.spec` strings (quoted spans) and the ↳ / + /
× / → glyphs the accordions and links are drawn with.

Structure (Lance /solutions, /solutions/front-of-house and
/solutions/independent, one to one — CONTRACT §3):

  index        hero · editorial image + platforms row · "By goal" 3×2 card
               grid · "By brand" 3×1 card grid on sand · closing CTA card
  goal page    split hero (crumb · h1 · intro · pill | mock panel) + platforms
               row · centred statement + three facts · sand "the services
               behind it" four-column row · four alternating feature blocks ·
               2×2 problems · sand steps · sand "under the hood" · quote card
               (the HQ room line drawing) + FAQ · related · CTA card
  brand page   full-viewport still hero · three facts · "where hypjam fits"
               2×2 · full-width still band · sand steps · reserved quote +
               FAQ · related · CTA card

Shared blocks come from src/css/40-pages.css (.page-*, .mock-*, owned by the
services agent); only the solutions-specific ones (.sol-*) live in
src/css/42-solutions.css.

Stdlib only. Idempotent. Prints one line per file written.
"""
from __future__ import annotations

import json
import re
import html as _html
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content" / "solutions.json"
DRAWING = ROOT / "src" / "drawing" / "hq.svg"
OUT_DIR = ROOT / "src" / "pages" / "solutions"
GENERATED = "<!-- generated by tools/render_solutions.py — edit content/solutions.json -->"
BASE_URL = "https://hypjam.vercel.app"
ORG_ID = BASE_URL + "/#org"  # Organization node defined once in partials/head.html (schema-global agent)

ARROW = ('<svg viewBox="0 0 12 12" width="11" height="11" aria-hidden="true"><path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" '
         'fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
ARROW_SM = ('<svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true"><path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" '
            'fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg>')
TICK_SVG = '<svg viewBox="0 0 8 8" aria-hidden="true"><path d="M1.5 4.2l1.8 1.8L6.6 2.4"/></svg>'

# CONTRACT §8 — the five room bounding boxes on the 44001×21918 canvas.
ROOMS = {
    1: ("#1-front-of-house", 4026, 15716, 8720, 4856),
    2: ("#2-back-of-house", 3796, 7408, 7603, 3552),
    3: ("#3-sales", 27045, 3959, 13189, 4840),
    4: ("#4-food-and-beverage", 27531, 17562, 12703, 4351),
    5: ("#5-management", 6749, 3021, 8669, 3983),
}


def esc(s) -> str:
    return _html.escape(str(s), quote=True)


def c(path: str, fallback: str | None = None) -> str:
    """A {{content:solutions.<path>}} reference (with an optional fallback)."""
    if fallback is not None:
        return "{{content:solutions." + path + "|" + fallback + "}}"
    return "{{content:solutions." + path + "}}"


def btn(label: str, href: str, extra: str = "") -> str:
    cls = "btn btn--light" + ((" " + extra) if extra else "")
    return f'<a class="{cls}" href="{href}">{label}<span class="btn__ico">{ARROW}</span></a>'


def btn_dark(label: str, href: str) -> str:
    return (f'<a class="btn btn--dark btn--jam" href="{href}">{label}'
            f'<span class="btn__ico">{ARROW}</span></a>')


def split(eyebrow_html: str, main_html: str, cls: str = "") -> str:
    return (f'<div class="page-split{(" " + cls) if cls else ""}">'
            f'<div class="page-split__aside"><p class="page-eyebrow">{eyebrow_html}</p></div>'
            f'<div class="page-split__main">{main_html}</div></div>')


# ---------------------------------------------------------------------------
# spec strings: the quoted spans are the mock's copy, kept in the JSON
# ---------------------------------------------------------------------------

# An opening/closing quote never touches a letter or digit, so a possessive
# ("the card's hook line") does not swallow the span that follows it.
_QUOTED = re.compile(r"(?<![A-Za-z0-9])'([^']*)'(?![A-Za-z0-9])")


def quoted(spec: str) -> list[str]:
    """The single-quoted spans of a mock spec, in order — the mock's copy."""
    return [s.strip() for s in _QUOTED.findall(spec or "") if s.strip()]


def q(spans: list[str], i: int, fallback: str = "") -> str:
    return esc(spans[i]) if 0 <= i < len(spans) else esc(fallback)


# ---------------------------------------------------------------------------
# line-icon primitives — original drawings, 320×200 viewBox, 1px grey strokes
# ---------------------------------------------------------------------------

def rrect(x, y, w, h, r=6, extra=""):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}"{extra}/>'


def phone(x, y, w, h, r=10):
    return (rrect(x, y, w, h, r) +
            f'<path d="M{x + w / 2 - 7} {y + 6}h14"/>')


def play(cx, cy, s=14):
    return f'<path d="M{cx - s * .45} {cy - s * .6}l{s * 1.05} {s * .6}l{-s * 1.05} {s * .6}z"/>'


def doc(x, y, w, h, lines=3, fold=True):
    out = (f'<path d="M{x} {y}h{w - 14}l14 14v{h - 14}H{x}z"/>' if fold
           else rrect(x, y, w, h, 3))
    if fold:
        out += f'<path d="M{x + w - 14} {y}v14h14"/>'
    for i in range(lines):
        out += f'<path d="M{x + 12} {y + 30 + i * 16}h{w - 30}"/>'
    return out


def envelope(x, y, w, h):
    return rrect(x, y, w, h, 5) + f'<path d="M{x + 2} {y + 5}l{w / 2 - 2} {h * .55}l{w / 2 - 2} {-h * .55}"/>'


def clock(cx, cy, r):
    return f'<circle cx="{cx}" cy="{cy}" r="{r}"/><path d="M{cx} {cy - r * .55}V{cy}h{r * .5}"/>'


def tick_circle(cx, cy, r):
    return (f'<circle cx="{cx}" cy="{cy}" r="{r}"/>'
            f'<path d="M{cx - r * .45} {cy}l{r * .35} {r * .38}l{r * .62} {-r * .72}"/>')


def arrow(x1, y1, x2, y2, head=7):
    import math
    a = math.atan2(y2 - y1, x2 - x1)
    p1 = (x2 - head * math.cos(a - .5), y2 - head * math.sin(a - .5))
    p2 = (x2 - head * math.cos(a + .5), y2 - head * math.sin(a + .5))
    return (f'<path d="M{x1:.0f} {y1:.0f}L{x2:.0f} {y2:.0f}"/>'
            f'<path d="M{p1[0]:.1f} {p1[1]:.1f}L{x2:.0f} {y2:.0f}L{p2[0]:.1f} {p2[1]:.1f}"/>')


def textlines(x, y, w, n, gap=12):
    return "".join(f'<path d="M{x} {y + i * gap}h{w if i < n - 1 else w * .62:.0f}"/>' for i in range(n))


def note(cx, cy, s=1.0):
    return (f'<path d="M{cx} {cy}v{-26 * s}l{16 * s} {-5 * s}v{26 * s}"/>'
            f'<ellipse cx="{cx - 5 * s}" cy="{cy + 4 * s}" rx="{6 * s}" ry="{4.5 * s}"/>'
            f'<ellipse cx="{cx + 11 * s}" cy="{cy}" rx="{6 * s}" ry="{4.5 * s}"/>')


def clapper(x, y, w, h):
    return (rrect(x, y + 12, w, h - 12, 3) +
            f'<path d="M{x} {y + 12}l{4} {-9}l{w * .28:.0f} {-3}l{-4} {9}z"/>'
            f'<path d="M{x + w * .28:.0f} {y + 12}l{4} {-9}l{w * .28:.0f} {-3}l{-4} {9}z"/>'
            f'<path d="M{x + w * .56:.0f} {y + 12}l{4} {-9}l{w * .28:.0f} {-3}l{-4} {9}z"/>')


def hand(x, y):
    """A simple line-drawn hand holding something, anchored bottom-left."""
    return (f'<path d="M{x} {y}c0 -18 10 -30 26 -30h18"/>'
            f'<path d="M{x + 6} {y - 6}c-2 -12 4 -20 14 -20"/>'
            f'<path d="M{x + 18} {y - 28}v-12M{x + 28} {y - 30}v-16M{x + 38} {y - 30}v-12"/>')


def eye(cx, cy, w=26, h=14):
    return (f'<path d="M{cx - w} {cy}c{w * .45} {-h} {w * 1.55} {-h} {w * 2} 0'
            f'c{-w * .45} {h} {-w * 1.55} {h} {-w * 2} 0z"/><circle cx="{cx}" cy="{cy}" r="{h * .38:.1f}"/>')


def digit3(x, y, s=14):
    """A stroked '3' so the clapperboard can be lettered without a font."""
    return (f'<path d="M{x} {y}c{s * .5} {-s * .45} {s * .95} {-s * .1} {s * .5} {s * .34}'
            f'c{s * .6} {s * .2} {s * .2} {s * .95} {-s * .55} {s * .6}"/>')


def slider(x, y, w, knob):
    return f'<path d="M{x} {y}h{w}"/><circle cx="{x + w * knob:.0f}" cy="{y}" r="6"/>'


def _icon_launch():
    return (phone(128, 28, 66, 118, 12) + play(161, 87, 17) +
            '<path d="M104 60h16M96 87h24M104 114h16"/>')


def _icon_loop():
    out = "".join(rrect(64 + (i % 5) * 30, 44 + (i // 5) * 24, 22, 16, 3) for i in range(20))
    out += '<path d="M248 90a28 28 0 1 1-24 13"/><path d="M239 81l10 9l-10 9"/>'
    return out


def _icon_trend():
    return ('<path d="M80 132l34-28l30 20l32-42l40-22"/>' + arrow(200, 66, 222, 58) +
            note(104, 94, .8))


def _icon_ring_light():
    return ('<circle cx="160" cy="82" r="50"/><circle cx="160" cy="82" r="40"/>' +
            phone(148, 62, 24, 40, 5) + '<path d="M160 132v22M136 160h48M160 154l-16 6M160 154l16 6"/>')


def _icon_grid_test():
    out = ""
    for i in range(9):
        x, y = 108 + (i % 3) * 40, 34 + (i // 3) * 46
        out += rrect(x, y, 30, 38, 4)
        if i in (1, 5):
            out += f'<path d="M{x + 9} {y + 20}l5 5l10 -12"/>'
        if i == 6:
            out += f'<circle cx="{x + 26}" cy="{y + 5}" r="3.5"/>'
    return out


def _icon_retention():
    return (envelope(100, 52, 120, 76) + play(160, 78, 15) +
            '<path d="M220 90c26 4 30 36 4 46H140"/>' + arrow(160, 136, 138, 136))


def _icon_calendar_pin():
    return (rrect(108, 52, 112, 92, 4) + '<path d="M108 76h112M132 52V40M196 52V40"/>' +
            '<circle cx="164" cy="112" r="15"/>' +
            '<path d="M164 22a11 11 0 0 1 11 11c0 8-11 19-11 19s-11-11-11-19a11 11 0 0 1 11-11z"/><circle cx="164" cy="33" r="3.5"/>')


def _icon_one_to_many():
    out = phone(72, 46, 62, 104, 10)
    for i in range(3):
        out += phone(222, 34 + i * 48, 28, 40, 5)
    out += arrow(144, 98, 212, 56) + arrow(144, 98, 212, 102) + arrow(144, 98, 212, 148)
    return out


def _icon_speech_script():
    return ('<path d="M84 46h150v72H128l-20 20v-20H84z"/>' + textlines(100, 68, 116, 3, 16) +
            clapper(196, 92, 78, 56))


def _icon_signed_doc():
    return (doc(100, 32, 110, 130, 0) + textlines(116, 66, 76, 2, 16) +
            tick_circle(214, 138, 18))


def _icon_fading_curve():
    return ('<path d="M76 138c26 0 40-72 68-72s34 44 54 52"/>'
            '<path d="M198 118c16 6 24 14 42 16" stroke-dasharray="5 6"/>' + clock(256, 100, 20))


def _icon_one_invoice():
    out = "".join(f'<g transform="rotate({-14 + i * 7} 110 140)">{doc(84, 50, 52, 92, 3)}</g>' for i in range(5))
    return out + arrow(158, 100, 186, 100) + doc(196, 50, 62, 92, 2) + tick_circle(250, 136, 13)


def _icon_variants():
    out = ""
    for i in range(3):
        x = 74 + i * 62
        out += phone(x, 40, 48, 104, 9)
        out += f'<path d="M{x + 10} {112 + i * 6}h{28 - i * 6}"/><path d="M{x + 10} {124}h{18 + i * 8}"/>'
    return out


def _icon_read_back():
    out = doc(68, 62, 62, 82, 3)
    for i, h in enumerate((30, 56, 40, 68)):
        out += f'<path d="M{170 + i * 26} 144v-{h}"/>'
    out += '<path d="M156 148h108"/>'
    out += '<path d="M248 72c8-28-18-44-46-40" stroke-dasharray="0"/>' + arrow(214, 34, 198, 40)
    return out


def _icon_clock_wave():
    out = clock(122, 92, 46)
    for i, h in enumerate((16, 28, 20, 34, 14)):
        out += f'<path d="M{178 + i * 14} {92 - h}v{h * 2}"/>'
    out += '<path d="M250 92h26" stroke-dasharray="4 6"/>'
    return out


def _icon_phone_handheld():
    return ('<g transform="rotate(-8 168 92)">' + phone(136, 30, 64, 112, 11) +
            '<path d="M146 116h44"/><path d="M146 128h28"/></g>' + hand(94, 168))


def _icon_week_strip():
    out = '<path d="M60 92h200"/>'
    for i in range(7):
        x = 62 + i * 32
        out += rrect(x, 76, 28, 32, 4)
        if i in (1, 3, 6):
            out += play(x + 14, 92, 11)
    return out


def _icon_bent_arrow():
    return (rrect(136, 78, 54, 46, 4) + '<path d="M136 92h54M158 78v-8h10v8"/>' +
            '<path d="M96 66v66c0 14 12 24 26 24h84c14 0 26-10 26-24V66"/>' + arrow(232, 82, 232, 60))


def _icon_take_counter():
    return (clapper(94, 44, 150, 108) + digit3(196, 108, 20) +
            '<path d="M118 116h56M118 132h34"/>' + tick_circle(258, 132, 15))


def _icon_eye_line():
    return (phone(112, 52, 78, 110, 12) + eye(151, 106, 22, 13) +
            '<path d="M160 88c14-18 34-26 52-28" stroke-dasharray="3 5"/><circle cx="222" cy="56" r="13"/><circle cx="222" cy="56" r="5"/>')


def _icon_short_clock():
    return (clock(122, 92, 46) + '<path d="M122 46a46 46 0 0 1 40 68" stroke-width="2.2"/>' +
            phone(204, 46, 56, 94, 10) + play(232, 93, 14))


def _icon_cut_line():
    out = doc(92, 34, 112, 128, 0) + textlines(108, 66, 80, 4, 20)
    out += '<path d="M100 118l92-22"/>'
    out += '<circle cx="216" cy="132" r="8"/><circle cx="216" cy="156" r="8"/><path d="M210 128l-28-22M210 160l-28-22"/>'
    return out


def _icon_one_axis():
    return (slider(92, 56, 136, .78) + slider(92, 94, 136, .18) + slider(92, 132, 136, .12) +
            f'<circle cx="{92 + 136 * .78:.0f}" cy="56" r="3" fill="currentColor" stroke="none"/>')


def _icon_labelled_grid():
    out = ""
    for i in range(9):
        x, y = 78 + (i % 3) * 42, 32 + (i // 3) * 44
        out += rrect(x, y, 32, 36, 4, ' stroke-width="2.2"' if i == 4 else "")
    out += '<path d="M162 96h56"/><path d="M218 96h34"/><circle cx="256" cy="96" r="4"/>'
    return out


def _icon_deck_to_brief():
    return (rrect(62, 48, 106, 76, 4) + '<path d="M78 108V88M96 108V74M114 108V96M132 108V80M72 112h84"/>' +
            arrow(178, 92, 204, 92) + doc(214, 48, 60, 92, 3))


def _icon_noisy_bars():
    out = "".join(f'<path d="M{108 + i * 34} 142v-{62 + (i % 2) * 6}"/>' for i in range(4))
    out += '<path d="M96 78h100" stroke-dasharray="4 6"/><path d="M94 148h120"/>'
    out += '<path d="M232 66a11 11 0 1 1 11 11v10"/><circle cx="243" cy="98" r="2.5" fill="currentColor" stroke="none"/>'
    return out


def _icon_box_play():
    return ('<path d="M92 84h136v70H92z"/><path d="M92 84l18-22h100l18 22"/><path d="M160 62v22"/>' +
            phone(142, 44, 36, 62, 7) + play(160, 76, 13))


def _icon_mail_thumb():
    return (envelope(92, 60, 136, 84) + '<path d="M92 66l68 46 68-46"/>' +
            phone(142, 34, 36, 56, 6) + play(160, 62, 12))


def _icon_faq_bubbles():
    return ('<path d="M64 48h108v56H98l-16 16v-16H64z"/>'
            '<path d="M124 76h108v56h-58l-16 16v-16h-34z"/>'
            '<path d="M110 62a9 9 0 1 1 9 9v8"/><circle cx="119" cy="86" r="2.5" fill="currentColor" stroke="none"/>'
            '<path d="M186 100l7 8l14 -16"/>')


def _icon_licence_channels():
    out = doc(88, 32, 116, 130, 0)
    for i in range(4):
        y = 62 + i * 24
        out += f'<path d="M104 {y}l5 5l9 -10"/><path d="M128 {y + 2}h58"/>'
    out += envelope(216, 110, 62, 42)
    return out


ICONS = {
    "launch": _icon_launch, "loop": _icon_loop, "trend": _icon_trend,
    "ring-light": _icon_ring_light, "grid-test": _icon_grid_test, "retention": _icon_retention,
    "calendar-pin": _icon_calendar_pin, "one-to-many": _icon_one_to_many,
    "speech-script": _icon_speech_script, "signed-doc": _icon_signed_doc,
    "fading-curve": _icon_fading_curve, "one-invoice": _icon_one_invoice,
    "variants": _icon_variants, "read-back": _icon_read_back, "clock-wave": _icon_clock_wave,
    "phone-handheld": _icon_phone_handheld, "week-strip": _icon_week_strip,
    "bent-arrow": _icon_bent_arrow, "take-counter": _icon_take_counter,
    "eye-line": _icon_eye_line, "short-clock": _icon_short_clock, "cut-line": _icon_cut_line,
    "one-axis": _icon_one_axis, "labelled-grid": _icon_labelled_grid,
    "deck-to-brief": _icon_deck_to_brief, "noisy-bars": _icon_noisy_bars,
    "box-play": _icon_box_play, "mail-thumb": _icon_mail_thumb,
    "faq-bubbles": _icon_faq_bubbles, "licence-channels": _icon_licence_channels,
}

MISSING_ICONS: set[str] = set()


def icon_svg(name: str, cls: str) -> str:
    fn = ICONS.get(name)
    if fn is None:
        MISSING_ICONS.add(name or "?")
        fn = lambda: doc(112, 36, 96, 120, 3)  # noqa: E731
    return (f'<svg class="page-icon {cls}" viewBox="0 0 320 200" aria-hidden="true" focusable="false">'
            f'{fn()}<path d="M40 178h240"/></svg>')


# ---------------------------------------------------------------------------
# mock builders — the twelve named UIs in solutions.json → .mock-* markup
# ---------------------------------------------------------------------------

def tick(jam: bool = True) -> str:
    return f'<span class="mock-tick{"" if jam else " mock-tick--ink"}" aria-hidden="true">{TICK_SVG}</span>'


def chip(text: str, cls: str = "") -> str:
    return f'<span class="mock-chip{(" " + cls) if cls else ""}">{text}</span>'


def card(body: str, head: str = "", width: str = "") -> str:
    cls = "mock-card" + ((" " + width) if width else "")
    return f'<div class="{cls}">{head}{body}</div>'


def stage(inner: str, col: bool = False) -> str:
    return f'<div class="mock-stage{" mock-stage--col" if col else ""}">{inner}</div>'


def m_conversation(spans, ov, base):
    sender = ov.get("sender") or base.get("sender")
    message = ov.get("message") or base.get("message")
    label = ov.get("label") or base.get("label")
    phone_ico = ('<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 3.5h3l1.5 4-2 1.5a11 11 0 0 0 6 6l1.5-2 4 1.5v3'
                 'a2 2 0 0 1-2 2A15.5 15.5 0 0 1 4.5 5.5a2 2 0 0 1 2-2z"/></svg>')
    wire = ('<svg viewBox="0 0 92 72" preserveAspectRatio="none" aria-hidden="true">'
            '<path d="M2 18C34 18 46 40 90 40"/></svg>')
    return ('<div class="sol-conv">'
            '<div class="sol-conv__left">'
            f'<p class="sol-conv__meta">{phone_ico}<span>{sender}</span></p>'
            f'<p class="sol-conv__bubble">{message}</p>'
            '</div>'
            f'<div class="sol-conv__wire" aria-hidden="true">{wire}</div>'
            '<div class="sol-conv__right">'
            '<span class="sol-conv__mark"><img src="/assets/brand/logos/hypjam-icon.svg" alt="" width="44" height="44" loading="lazy" decoding="async"></span>'
            f'<span class="sol-conv__label">{label}</span>'
            '</div></div>')


def row(label: str, value: str, cls: str = "") -> str:
    return (f'<div class="mock-row{(" " + cls) if cls else ""}">'
            f'<span class="sol-row-k">{label}</span><span class="sol-row-v">{value}</span></div>')


def m_brief_card(spans, ov, base):
    head = (f'<div class="mock-head"><span class="mock-head__t">'
            f'<span class="mock-dot mock-dot--jam"></span> {q(spans, 0, "Brief · your brand")}</span>'
            f'<span class="mock-head__r">{q(spans, 1, "in progress")}</span></div>')
    chips = "".join(chip(p) for p in ("TikTok", "Reels", "Shorts"))
    body = ('<div class="mock-rows">'
            + row("Product", q(spans, 2))
            + row("Goal", q(spans, 3))
            + f'<div class="mock-row"><span class="sol-row-k">Platforms</span><span class="mock-chips">{chips}</span></div>'
            + row("Budget band", q(spans, 4))
            + row("Hooks", q(spans, 5))
            + '</div>')
    return stage(card(body, head, "sol-wide"))


def m_hook_list(spans, ov, base):
    lines = spans[2:10] if len(spans) >= 10 else spans[2:]
    picked = {1, 6}
    rows = []
    for i, line in enumerate(lines):
        extra = ""
        if i in picked:
            extra = tick() + chip("picked for the shoot", "mock-chip--jam")
        rows.append(f'<div class="mock-row{" mock-row--jam" if i in picked else ""}">'
                    f'<span class="mock-row__n">{i + 1:02d}</span>'
                    f'<span class="mock-row__t">{esc(line)}</span>{extra}</div>')
    return stage(card(f'<div class="mock-rows">{"".join(rows)}</div>', "", "sol-wide sol-hooks"))


AVATAR = ('<svg viewBox="0 0 56 56" aria-hidden="true"><circle cx="28" cy="28" r="26"/>'
          '<circle cx="28" cy="22" r="8"/><path d="M13 47a16 16 0 0 1 30 0"/></svg>')


def m_casting_board(spans, ov, base):
    tags = [q(spans, 1), q(spans, 2), q(spans, 3)]
    handle = q(spans, 0, "@—")
    cards = []
    for i, t in enumerate(tags):
        pick = (f'<span class="mock-chip mock-chip--jam sol-castcard__pick">{q(spans, 4, "shortlisted")}</span>'
                if i == 1 else "")
        cards.append(f'<div class="sol-castcard{" sol-castcard--pick" if i == 1 else ""}">'
                     f'<span class="sol-castcard__av" aria-hidden="true">{AVATAR}</span>'
                     f'<span class="sol-castcard__handle">{handle}</span>'
                     f'<span class="sol-castcard__tags">{t}</span>{pick}</div>')
    return f'<div class="sol-castcards">{"".join(cards)}</div>'


FIGURE = ('<svg viewBox="0 0 80 120" aria-hidden="true" preserveAspectRatio="xMidYMid meet" fill="none" '
          'stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'
          '<circle cx="40" cy="26" r="15"/><path d="M11 118c0-22 13-36 29-36s29 14 29 36"/>'
          '<path d="M59 92l13-14"/><rect x="61" y="58" width="21" height="19" rx="2"/></svg>')


def m_phone_rec(spans, ov, base):
    ph = ('<div class="mock-phone mock-phone--lg">'
          f'<span class="mock-phone__rec">{q(spans, 0, "REC 00:12:07").split(" ")[0]}</span>'
          '<span class="mock-phone__tc" data-tc="727">00:12:07</span>'
          f'<span class="mock-phone__figure" aria-hidden="true">{FIGURE}</span>'
          f'<span class="mock-phone__caption">{q(spans, 1)}</span>'
          '<span class="mock-phone__meter" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span>'
          '</div>')
    takes = ('<div class="mock-rows">'
             f'<div class="mock-row mock-row--strike"><span class="mock-row__t">{q(spans, 2)}</span></div>'
             f'<div class="mock-row"><span class="mock-row__t">{q(spans, 3).replace(" ✓", "")}</span>{tick()}</div>'
             f'<div class="mock-row mock-row--muted"><span class="mock-row__t">{q(spans, 4)}</span>'
             '<span class="mock-ring"></span></div></div>')
    return stage(ph + card(takes, '<div class="mock-head"><span class="mock-head__t">Takes</span></div>', "mock-card--sm"))


def m_timeline(spans, ov, base):
    clips = "".join(f'<span class="mock-clip{" mock-clip--w2" if i in (1, 2) else ""}">{q(spans, i)}</span>'
                    for i in range(4))
    track = ('<div class="mock-track">'
             '<div class="mock-track__ruler" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>'
             '<p class="mock-label">video</p>'
             f'<div class="mock-track__row">{clips}</div>'
             '<p class="mock-label">captions</p>'
             f'<div class="mock-track__row mock-track__row--thin">'
             f'<span class="mock-clip mock-clip--cap mock-clip--jam">{q(spans, 4, "CC")}</span>'
             '<span class="mock-clip mock-clip--cap"></span></div>'
             '<p class="mock-label">sound</p>'
             '<div class="mock-wave" aria-hidden="true">' + "<i></i>" * 34 + '</div>'
             '</div>')
    export = ('<div class="mock-export"><div class="mock-bar mock-bar--tall"><span class="mock-bar__fill mock-bar__fill--jam"></span></div>'
              '<div class="mock-export__chips">' + "".join(chip(p) for p in ("TikTok", "Reels", "Shorts")) + '</div></div>')
    return stage(card(track + export, "", "sol-wide"))


def m_spark_toggle(spans, ov, base):
    tabs = (f'<div class="sol-tabs"><span class="sol-tab sol-tab--on">{q(spans, 0, "TikTok")}</span>'
            f'<span class="sol-tab">{q(spans, 1, "Meta")}</span></div>')
    body = ('<div class="mock-rows">'
            f'<div class="mock-row"><span class="mock-avatar" aria-hidden="true"></span>'
            f'<span class="mock-row__t">{q(spans, 2, "@—")}</span><span class="mock-row__v">{q(spans, 3)}</span></div>'
            f'<div class="mock-row"><span class="mock-row__t">{q(spans, 4)}</span>'
            '<span class="mock-toggle mock-toggle--on" aria-hidden="true"></span></div>'
            f'<div class="mock-row"><span class="mock-row__t">{q(spans, 5)}</span>'
            f'<span class="mock-chip mock-chip--jam">{q(spans, 7, "ready")}</span></div>'
            '</div>')
    return stage(card(tabs + body))


def m_rights_sheet(spans, ov, base):
    head = f'<div class="mock-head"><span class="mock-head__t">{q(spans, 0)}</span></div>'
    body = ('<div class="mock-rows">'
            f'<div class="mock-row"><span class="sol-row-k">Organic</span>{tick()}</div>'
            f'<div class="mock-row"><span class="sol-row-k">Paid</span>{tick()}</div>'
            f'<div class="mock-row"><span class="sol-row-k">Whitelisting</span>{tick()}</div>'
            + row("Window", q(spans, 1)) + row("Territory", q(spans, 2)) + '</div>'
            f'<div class="mock-sig"><span class="mock-sig__line"></span>'
            f'<span>{q(spans, 3)}</span><span class="sol-stamp" aria-hidden="true"></span></div>')
    return stage(card(body, head))


def m_report_grid(spans, ov, base):
    cols = [s.strip() for s in q(spans, 0, "hook 02 · hook 07 · hook 05").split("·")]
    rows_h = [s.strip() for s in q(spans, 1, "@— · @— · @—").split("·")]
    shade = ["", " sol-cell--2", " sol-cell--3", " sol-cell--2", "", " sol-cell--3", " sol-cell--3", " sol-cell--2", ""]
    cells = ['<div class="mock-tile mock-tile--head"></div>']
    cells += [f'<div class="mock-tile mock-tile--head">{h}</div>' for h in cols]
    for r in range(3):
        cells.append(f'<div class="mock-tile mock-tile--rowhead">{rows_h[r] if r < len(rows_h) else "@—"}</div>')
        for col in range(3):
            i = r * 3 + col
            if i == 4:
                cells.append(f'<div class="mock-tile mock-tile--jam"><span class="mock-tile__s">{q(spans, 2, "run this")}</span></div>')
            else:
                cells.append(f'<div class="mock-tile{shade[i]}"></div>')
    grid = f'<div class="mock-grid mock-grid--labels">{"".join(cells)}</div>'
    foot = f'<div class="mock-foot">{q(spans, 3)}</div>'
    return stage(card(grid + foot, "", "sol-wide"))


def m_founder_take(spans, ov, base):
    ph = ('<div class="mock-phone">'
          f'<span class="mock-phone__figure" aria-hidden="true">{FIGURE}</span>'
          f'<span class="mock-phone__caption">{q(spans, 0, "take 3")}</span></div>')
    lines = [x for x in (q(spans, 2), q(spans, 5)) if x]
    body = ('<div class="mock-ticker">' + "".join(f'<span>{x}</span>' for x in lines) + '</div>'
            if len(lines) > 1 else f'<p class="sol-take__line">{lines[0] if lines else ""}</p>')
    prompt = ('<p class="mock-label">' + q(spans, 1, "Hook") + '</p>' + body +
              f'<div class="mock-foot mock-foot--bare">{q(spans, 3)}</div>')
    return stage(ph + f'<div class="mock-card mock-card--sm sol-take">{prompt}</div>')


def m_trend_board(spans, ov, base):
    names = [s.strip() for s in q(spans, 0, "sound 01/02/03").replace("sound ", "").split("/")]
    rows = []
    for i, n in enumerate(names[:3]):
        extra = (f'<span class="mock-row__v">{q(spans, 1)}</span>'
                 f'<span class="mock-star" aria-hidden="true">↑</span>'
                 f'{chip(q(spans, 3, "brief sent"), "mock-chip--jam")}') if i == 1 else \
                f'<span class="mock-row__v">{q(spans, 1)}</span>'
        rows.append('<div class="mock-row">'
                    '<span class="mock-wave" aria-hidden="true">' + "<i></i>" * 12 + '</span>'
                    f'<span class="mock-row__t">sound {n}</span>{extra}</div>')
    mini = (f'<span class="sol-mini-phone" aria-hidden="true" title="{q(spans, 2, "stitched")}"><i></i><i></i></span>')
    return stage(card(f'<div class="mock-rows">{"".join(rows)}</div>') + mini)


def m_retention_flow(spans, ov, base):
    arrow_svg = ('<svg viewBox="0 0 46 14" aria-hidden="true"><path d="M1 7h40M36 2l6 5-6 5"/></svg>')
    nodes = []
    for i in range(3):
        pl = '<span class="sol-flow__play" aria-hidden="true"></span>' if i in (1, 2) else ""
        nodes.append(f'<div class="sol-flow__node">{pl}<span>{q(spans, i)}</span></div>')
    return ('<div class="sol-flow">' + nodes[0] +
            f'<span class="sol-flow__arrow" aria-hidden="true">{arrow_svg}</span>' + nodes[1] +
            f'<span class="sol-flow__arrow" aria-hidden="true">{arrow_svg}</span>' + nodes[2] + '</div>')


MOCKS = {
    "conversation": m_conversation, "brief-card": m_brief_card, "hook-list": m_hook_list,
    "casting-board": m_casting_board, "phone-rec": m_phone_rec, "timeline": m_timeline,
    "spark-toggle": m_spark_toggle, "rights-sheet": m_rights_sheet, "report-grid": m_report_grid,
    "founder-take": m_founder_take, "trend-board": m_trend_board, "retention-flow": m_retention_flow,
}

MISSING_MOCKS: set[str] = set()


def build_panel(data: dict, visual: dict, ref: str, tile: bool = False) -> str:
    """A .page-panel holding the named mock. `ref` is the JSON path of the
    visual object, so overridden copy (sender/message/label) stays a
    {{content:…}} reference."""
    name = visual.get("mock", "")
    spec = (data.get("mocks", {}).get(name) or {})
    fn = MOCKS.get(name)
    if fn is None:
        MISSING_MOCKS.add(name or "?")
        inner = stage(card('<div class="mock-lines"><span class="mock-line"></span>'
                           '<span class="mock-line mock-line--w60"></span></div>'))
    else:
        base = {k: c(f"mocks.{name}.defaults.{k}") for k in (spec.get("defaults") or {})}
        ov = {k: c(f"{ref}.{k}") for k in visual if k in ("sender", "message", "label")}
        inner = fn(quoted(spec.get("spec", "")), ov, base)
    cls = "page-panel page-panel--tile" if tile else "page-panel"
    return f'<div class="{cls}">{inner}</div>'


# ---------------------------------------------------------------------------
# the HQ room line drawing (CONTRACT §8) for the goal pages' quote card
# ---------------------------------------------------------------------------

_ATTR_DROP = re.compile(r'\s(?:stroke|stroke-width|fill|stroke-linecap|stroke-linejoin)="[^"]*"')
_GROUP = re.compile(r"<g\b|</g>")


def room_group(svg: str, gid: str) -> str | None:
    start = svg.find(f'<g id="{gid}">')
    if start < 0:
        return None
    depth, pos = 0, start
    while True:
        m = _GROUP.search(svg, pos)
        if not m:
            return None
        if m.group(0) == "</g>":
            depth -= 1
            pos = m.end()
            if depth == 0:
                break
        else:
            depth += 1
            pos = m.end()
    frag = svg[start:pos]
    frag = frag[frag.index(">") + 1:frag.rindex("</g>")]     # inner markup only
    return _ATTR_DROP.sub("", frag)


_ROOM_CACHE: dict[int, str] = {}
MISSING_ROOMS: set[int] = set()


def room_svg(room: int, alt: str) -> str:
    """An inline SVG cropped to one room of src/drawing/hq.svg, restyled to a
    1px grey stroke. Falls back to the small footer drawing if the group is
    not there yet (the drawing agent may still be writing it)."""
    if room not in _ROOM_CACHE:
        body = None
        if DRAWING.exists() and room in ROOMS:
            try:
                body = room_group(DRAWING.read_text(encoding="utf-8", errors="ignore"), ROOMS[room][0])
            except Exception:
                body = None
        if not body:
            MISSING_ROOMS.add(room)
            _ROOM_CACHE[room] = ""
        else:
            _, x, y, w, h = ROOMS[room]
            pad = int(w * 0.03)
            vb = f"{x - pad} {y - pad} {w + pad * 2} {h + pad * 2}"
            _ROOM_CACHE[room] = (
                f'<svg class="sol-room" viewBox="{vb}" role="img" aria-label="{alt}" '
                f'preserveAspectRatio="xMidYMid meet">'
                f'<g fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" '
                f'stroke-linejoin="round">{body}</g></svg>')
    art = _ROOM_CACHE[room]
    if art:
        return art
    return (f'<img class="sol-room" src="/assets/img/hq-footer.svg" alt="{alt}" '
            f'width="420" height="180" loading="lazy" decoding="async">')


# ---------------------------------------------------------------------------
# shared page fragments
# ---------------------------------------------------------------------------

def head(meta: list[tuple[str, str]]) -> str:
    lines = [f"<!-- {k}: {v} -->" for k, v in meta]
    lines.append(GENERATED)
    lines += ["{{include:partials/head.html}}", "{{include:partials/nav.html}}", "{{include:partials/icons.html}}"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# structured data (SEO-CONTRACT.md — head-extra mechanism)
#
# Built from the real Python values already loaded from content/solutions.json
# (not {{content:…}} tokens) so json.dumps can escape them correctly — the
# same approach tools/render_blog.py and render_services.py use.
# ---------------------------------------------------------------------------

def jsonld(obj) -> str:
    return '<script type="application/ld+json">' + json.dumps(obj, ensure_ascii=False).replace("</", "<\\/") + "</script>"


def crumb_labels(data: dict) -> dict:
    """slug -> the short label the /solutions index itself links each card
    with ('Launches', 'For DTC & ecommerce', …) — the same text a visitor
    would follow from Home -> Solutions -> this page."""
    idx = data["index"]
    out = {}
    for grp in ("by_goal", "by_brand"):
        for cd in idx[grp]["cards"]:
            out[cd["slug"]] = cd["title"]
    return out


def solution_page_ld(data: dict, p: dict, label: str) -> str:
    """@graph for one /solutions/<slug> page: Service, BreadcrumbList, and
    (every solution page renders a real FAQ accordion) FAQPage matching it."""
    slug = p["slug"]
    url = f"{BASE_URL}/solutions/{slug}"
    graph = [
        {
            "@type": "Service",
            "@id": url + "#service",
            "name": p["hero"]["h1"],
            "description": p["meta"]["description"],
            "serviceType": label,
            "areaServed": "GB",
            "provider": {"@id": ORG_ID},
            "url": url,
        },
        {
            "@type": "BreadcrumbList",
            "@id": url + "#breadcrumb",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL + "/"},
                {"@type": "ListItem", "position": 2, "name": "Solutions", "item": BASE_URL + "/solutions"},
                {"@type": "ListItem", "position": 3, "name": label, "item": url},
            ],
        },
    ]
    faq_items = p.get("faq", {}).get("items") or []
    if faq_items:
        graph.append({
            "@type": "FAQPage",
            "@id": url + "#faq",
            "mainEntity": [
                {"@type": "Question", "name": it["q"], "acceptedAnswer": {"@type": "Answer", "text": it["a"]}}
                for it in faq_items
            ],
        })
    return jsonld({"@context": "https://schema.org", "@graph": graph})


def solutions_index_ld(data: dict) -> str:
    """@graph for /solutions: BreadcrumbList (Home → Solutions) plus an
    ItemList of the nine solutions (name + url only)."""
    url = BASE_URL + "/solutions"
    idx = data["index"]
    items = []
    pos = 1
    for grp in ("by_goal", "by_brand"):
        for cd in idx[grp]["cards"]:
            items.append({
                "@type": "ListItem",
                "position": pos,
                "name": cd["title"],
                "url": f"{BASE_URL}/solutions/{cd['slug']}",
            })
            pos += 1
    graph = [
        {
            "@type": "BreadcrumbList",
            "@id": url + "#breadcrumb",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL + "/"},
                {"@type": "ListItem", "position": 2, "name": "Solutions", "item": url},
            ],
        },
        {
            "@type": "ItemList",
            "@id": url + "#itemlist",
            "itemListElement": items,
        },
    ]
    return jsonld({"@context": "https://schema.org", "@graph": graph})


TAIL = "{{include:partials/page-cta.html}}\n</main>\n{{include:partials/footer.html}}\n{{include:partials/scripts.html}}\n"


def service_href(data: dict, sid: str) -> str:
    return c(f"services.{sid}.href", (data["services"].get(sid) or {}).get("href", "/services"))


def service_label(data: dict, sid: str) -> str:
    return c(f"services.{sid}.label", (data["services"].get(sid) or {}).get("label", "Services"))


def facts_block(data: dict, ref: str, facts: dict) -> str:
    out = ['<section class="page-section page-section--stats page-stats">',
           f'<h2 class="page-h2 page-stats__h2">{c(ref + ".h2")}</h2>',
           f'<p class="page-p sol-stats__p">{c(ref + ".p")}</p>',
           '<div class="page-stats__row sol-stats--3">']
    for k in range(len(facts["items"])):
        out.append(f'<div class="page-stat"><p class="page-stat__num">{c(f"{ref}.items.{k}.value")}</p>'
                   f'<p class="page-stat__label">{c(f"{ref}.items.{k}.label")}</p></div>')
    out.append("</div></section>")
    return "".join(out)


def steps_block(data: dict, ref: str, how: dict) -> str:
    out = ['<section class="page-section page-section--sand section--sand-s">',
           split(c(ref + ".eyebrow"), f'<h2 class="page-h2">{c(ref + ".h2")}</h2>', "page-split--steps"),
           '<ol class="page-steps">']
    for k in range(len(how["steps"])):
        out.append(f'<li class="page-step"><span class="page-step__n">{c(f"{ref}.steps.{k}.n")}</span>'
                   f'<h3 class="page-step__title">{c(f"{ref}.steps.{k}.title")}</h3>'
                   f'<p class="page-step__body">{c(f"{ref}.steps.{k}.body")}</p></li>')
    out.append("</ol></section>")
    return "".join(out)


def faq_block(data: dict, ref: str, faq: dict) -> str:
    items = []
    for k in range(len(faq["items"])):
        items.append(f'<details class="page-faq__item"{" open" if k == 0 else ""}>'
                     f'<summary class="page-faq__q"><span class="page-faq__mark" aria-hidden="true">↳</span>'
                     f'<span class="page-faq__label">{c(f"{ref}.items.{k}.q")}</span>'
                     f'<span class="page-faq__toggle" aria-hidden="true"></span></summary>'
                     f'<p class="page-faq__a">{c(f"{ref}.items.{k}.a")}</p></details>')
    return split(c(ref + ".eyebrow"),
                 f'<h2 class="page-h2">{c(ref + ".h2")}</h2><div class="page-faq">{"".join(items)}</div>')


def quote_block(data: dict, ref: str, quote: dict) -> str:
    if quote.get("kind") == "reserved":
        alt = esc((quote.get("visual") or {}).get("alt", "Reserved space for a brand story"))
        return ('<figure class="page-quote page-quote--reserved"><div class="page-quote__body">'
                f'<blockquote class="page-quote__text">{c(ref + ".text")}</blockquote>'
                f'<figcaption class="page-quote__attr"><span class="tag-soon">{c(ref + ".tag")}</span></figcaption></div>'
                f'<div class="page-quote__media" role="img" aria-label="{alt}">'
                '<span class="reserved__phone reserved__phone--lg" aria-hidden="true"></span></div></figure>')
    v = quote.get("visual") or {}
    art = room_svg(int(v.get("room", 1)), esc(v.get("alt", "Line drawing of a room at hypjam's HQ")))
    return ('<figure class="page-quote"><div class="page-quote__body">'
            f'<blockquote class="page-quote__text">“{c(ref + ".text")}”</blockquote>'
            f'<figcaption class="page-quote__attr"><p class="page-quote__name">{c(ref + ".name")}</p>'
            f'<p class="page-quote__role">{c(ref + ".role")}</p></figcaption></div>'
            f'<div class="page-quote__media sol-quote-media">{art}</div></figure>')


def related_block(data: dict, ref: str, related: dict) -> str:
    items = []
    for k, it in enumerate(related["items"]):
        if it.get("service"):
            href, label = service_href(data, it["service"]), service_label(data, it["service"])
        else:
            href, label = c(f"{ref}.items.{k}.href"), c(f"{ref}.items.{k}.label")
        items.append(f'<li class="sol-related__item"><a class="sol-related__link" href="{href}">{label}</a>'
                     f'<p class="sol-related__body">{c(f"{ref}.items.{k}.body")}</p></li>')
    return ('<section class="page-section sol-section--related">'
            '<hr class="sol-related-rule">'
            + split(c(ref + ".eyebrow"), f'<ul class="sol-related">{"".join(items)}</ul>')
            + '</section>')


def meta_common(data: dict, item: dict, i: int, body_class: str, nav: str, fill: str) -> list[tuple[str, str]]:
    label = crumb_labels(data).get(item["slug"], item["hero"]["h1"])
    return [
        ("title", c(f"pages.{i}.meta.title")),
        ("description", c(f"pages.{i}.meta.description")),
        ("nav", nav), ("nav-fill", fill), ("body-class", body_class),
        ("cta-h2", c(f"pages.{i}.cta.h2")), ("cta-p", c(f"pages.{i}.cta.p")),
        ("cta-label", c(f"pages.{i}.cta.button.label")), ("cta-href", c(f"pages.{i}.cta.button.href")),
        ("head-extra", solution_page_ld(data, item, label)),
    ]


# ---------------------------------------------------------------------------
# the index
# ---------------------------------------------------------------------------

def card_grid(data: dict, ref: str, group: dict, brand: bool) -> str:
    out = [f'<ul class="sol-cards{" sol-cards--brand" if brand else ""}">']
    for k, cd in enumerate(group["cards"]):
        v = cd.get("visual") or {}
        if v.get("kind") == "still":
            art = (f'<img class="sol-card__still" src="{c(f"{ref}.cards.{k}.visual.src")}" '
                   f'alt="{c(f"{ref}.cards.{k}.visual.alt")}" width="604" height="452" '
                   f'style="object-position: {c(f"{ref}.cards.{k}.visual.position", "50% 50%")}" '
                   f'loading="lazy" decoding="async">')
        else:
            art = (f'<div class="page-panel page-panel--tile sol-card__tile">'
                   f'{icon_svg(v.get("icon", ""), "sol-card__icon")}</div>')
        href = c(f"{ref}.cards.{k}.href", "/solutions/" + cd["slug"])
        out.append(f'<li><a class="sol-card" href="{href}">{art}'
                   f'<span class="sol-card__head"><span class="sol-card__title">{c(f"{ref}.cards.{k}.title")}</span>'
                   f'<span class="arrow-link arrow-link--nudge sol-card__explore">{c(f"{ref}.cards.{k}.cta", "Explore")}{ARROW_SM}</span></span>'
                   f'<span class="sol-card__blurb">{c(f"{ref}.cards.{k}.blurb")}</span></a></li>')
    out.append("</ul>")
    return "".join(out)


def render_index(data: dict) -> str:
    idx = data["index"]
    meta = [
        ("title", c("index.meta.title")),
        ("description", c("index.meta.description")),
        ("nav", "light"), ("nav-fill", "bg-white"), ("body-class", "sol sol--index"),
        ("cta-h2", c("index.cta.h2")), ("cta-p", c("index.cta.p")),
        ("cta-label", c("index.cta.button.label")), ("cta-href", c("index.cta.button.href")),
        ("head-extra", solutions_index_ld(data)),
    ]
    out = [head(meta), '<main class="page sol sol--index" data-theme="light">']
    # hero
    out.append('<section class="page-section page-section--hero"><div class="page-hero"><div class="page-hero__copy">'
               f'<p class="page-eyebrow page-eyebrow--caps page-hero__eyebrow">{c("index.hero.eyebrow")}</p>'
               f'<h1 class="page-hero__title">{c("index.hero.h1")}</h1>'
               f'<p class="page-hero__intro">{c("index.hero.intro")}</p>'
               f'<div class="page-hero__cta">{btn(c("index.hero.cta.label"), c("index.hero.cta.href"))}</div>'
               '</div></div></section>')
    # editorial image + platforms row
    out.append('<section class="page-section page-section--image">'
               f'<img class="page-image" src="{c("index.editorial.visual.src")}" alt="{c("index.editorial.visual.alt")}" '
               f'width="1864" height="1049" style="object-position: {c("index.editorial.visual.position", "50% 50%")}" '
               'decoding="async" fetchpriority="high">')
    if idx.get("platforms_row"):
        out.append("{{include:partials/platforms-row.html}}")
    out.append("</section>")
    # by goal
    out.append('<section class="page-section sol-section--goal">'
               + split(c("index.by_goal.eyebrow"), f'<h2 class="page-h2">{c("index.by_goal.h2")}</h2>', "sol-cards__head")
               + card_grid(data, "index.by_goal", idx["by_goal"], False)
               + "</section>")
    # by brand (sand)
    out.append('<section class="page-section page-section--sand section--sand-s">'
               + split(c("index.by_brand.eyebrow"), f'<h2 class="page-h2">{c("index.by_brand.h2")}</h2>', "sol-cards__head")
               + card_grid(data, "index.by_brand", idx["by_brand"], True)
               + "</section>")
    out.append(TAIL)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# a goal page (Lance's by-area template)
# ---------------------------------------------------------------------------

def render_goal(data: dict, i: int, p: dict) -> str:
    ref = f"pages.{i}"
    out = [head(meta_common(data, p, i, f"sol sol--goal sol--{p['slug']}", "light", "bg-white")),
           f'<main class="page sol sol--goal sol--{p["slug"]}" data-theme="light">']

    # hero ---------------------------------------------------------------
    out.append('<section class="page-section page-section--hero-split"><div class="page-hero page-hero--split">'
               '<div class="page-hero__copy">'
               f'<p class="page-hero__crumb"><a href="/solutions">{c(ref + ".hero.breadcrumb.0")}</a>'
               f'<span aria-hidden="true">/</span>'
               f'<span class="page-hero__crumb-current">{c(ref + ".hero.breadcrumb.1")}</span></p>'
               f'<h1 class="page-hero__title">{c(ref + ".hero.h1")}</h1>'
               f'<p class="page-hero__intro">{c(ref + ".hero.intro")}</p>'
               f'<div class="page-hero__cta">{btn(c(ref + ".hero.cta.label"), c(ref + ".hero.cta.href"))}</div>'
               '</div><div class="page-hero__visual" aria-hidden="true">'
               + build_panel(data, p["hero"]["visual"], f"{ref}.hero.visual") +
               '</div></div>')
    if p.get("platforms_row"):
        out.append('<div class="page-hero__platforms">{{include:partials/platforms-row.html}}</div>')
    out.append("</section>")

    # statement + three facts ---------------------------------------------
    out.append(facts_block(data, ref + ".facts", p["facts"]))

    # the services behind it (sand) ---------------------------------------
    b = p["behind"]
    cells = []
    for k, it in enumerate(b["items"]):
        sid = it["service"]
        anchor = esc(it.get("anchor", ""))
        cells.append('<li class="sol-behind__cell">'
                     f'<span class="sol-behind__n">{c(f"{ref}.behind.items.{k}.n")}</span>'
                     f'<a class="sol-behind__name" href="{anchor}">{service_label(data, sid)}</a>'
                     f'<p class="sol-behind__blurb">{c(f"{ref}.behind.items.{k}.blurb")}</p>'
                     f'<a class="page-link sol-behind__link" href="{service_href(data, sid)}">'
                     f'{c(f"{ref}.behind.items.{k}.link_label")}</a></li>')
    out.append('<section class="page-section page-section--sand section--sand-s">'
               + split(c(ref + ".behind.eyebrow"),
                       f'<h2 class="page-h2">{c(ref + ".behind.h2")}</h2><p class="page-p">{c(ref + ".behind.p")}</p>',
                       "page-split--steps")
               + f'<ul class="sol-behind">{"".join(cells)}</ul></section>')

    # feature blocks -------------------------------------------------------
    out.append('<section class="page-section page-section--features"><div class="page-features">')
    for k, f in enumerate(p["features"]):
        fr = f"{ref}.features.{k}"
        flip = " page-feature--flip" if f.get("layout") == "text-right" else ""
        anchor = f' id="{esc(f["anchor"])}"' if f.get("anchor") else ""
        bullets = []
        for m in range(len(f["points"])):
            bullets.append(f'<details class="page-bullet"{" open" if m == 0 else ""}>'
                           '<summary class="page-bullet__btn"><span class="page-bullet__mark" aria-hidden="true">↳</span>'
                           f'<span>{c(f"{fr}.points.{m}.title")}</span></summary>'
                           f'<p class="page-bullet__body">{c(f"{fr}.points.{m}.body")}</p></details>')
        link = ""
        if f.get("link_label"):
            link = (f'<div class="page-feature__related"><a class="page-link" href="{service_href(data, f["service"])}">'
                    f'{c(fr + ".link_label")}</a></div>')
        out.append(f'<div class="page-feature{flip}"{anchor}><div class="page-feature__text">'
                   f'<h2 class="page-h2 page-feature__h2">{c(fr + ".h2")}</h2>'
                   f'<p class="page-feature__p">{c(fr + ".p")}</p>'
                   f'<div class="page-feature__bullets">{"".join(bullets)}</div>{link}</div>'
                   '<div class="page-feature__visual" aria-hidden="true">'
                   + build_panel(data, f["visual"], f"{fr}.visual") + '</div></div>')
    out.append("</div></section>")

    # problems -------------------------------------------------------------
    tiles = []
    for k, it in enumerate(p["problems"]["items"]):
        v = it.get("visual") or {}
        tiles.append('<div class="page-problem">'
                     f'<div class="page-panel page-problem__tile">{icon_svg(v.get("icon", ""), "page-problem__icon")}</div>'
                     f'<h3 class="page-problem__title">{c(f"{ref}.problems.items.{k}.title")}</h3>'
                     f'<p class="page-problem__body">{c(f"{ref}.problems.items.{k}.body")}</p></div>')
    out.append('<section class="page-section page-section--problems"><div class="page-problems">'
               f'<div class="page-problems__head"><h2 class="page-h2">{c(ref + ".problems.h2")}</h2>'
               f'<p class="page-p">{c(ref + ".problems.p")}</p></div>'
               f'<div class="page-problems__grid">{"".join(tiles)}</div></div></section>')

    # how it runs (sand) ---------------------------------------------------
    out.append(steps_block(data, ref + ".how", p["how"]))

    # under the hood (sand) ------------------------------------------------
    hood = p["hood"]
    last = len(hood["items"]) - 1
    hcells = []
    for k in range(len(hood["items"])):
        link = ""
        if k == last and hood.get("link"):
            link = (f'<a class="page-link page-compare__link" href="{c(ref + ".hood.link.href")}">'
                    f'{c(ref + ".hood.link.label")}</a>')
        hcells.append('<div class="page-compare__cell">'
                      f'<p class="page-compare__label">{c(f"{ref}.hood.items.{k}.label")}</p>'
                      f'<p class="page-compare__value">{c(f"{ref}.hood.items.{k}.value")}</p>'
                      f'<p class="page-compare__body">{c(f"{ref}.hood.items.{k}.body")}</p>{link}</div>')
    out.append('<section class="page-section page-section--sand section--sand-s">'
               + split(c(ref + ".hood.eyebrow"),
                       f'<h2 class="page-h2">{c(ref + ".hood.h2")}</h2><p class="page-p">{c(ref + ".hood.p")}</p>',
                       "page-split--compare")
               + f'<div class="page-compare">{"".join(hcells)}</div></section>')

    # quote + FAQ ----------------------------------------------------------
    out.append('<section class="page-section page-section--faq">'
               + quote_block(data, ref + ".quote", p["quote"])
               + faq_block(data, ref + ".faq", p["faq"]) + "</section>")

    out.append(related_block(data, ref + ".related", p["related"]))
    out.append(TAIL)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# a brand page (Lance's by-type template)
# ---------------------------------------------------------------------------

def render_brand(data: dict, i: int, p: dict) -> str:
    ref = f"pages.{i}"
    out = [head(meta_common(data, p, i, f"sol sol--brand sol--{p['slug']}", "image", "bg-transparent")),
           f'<main class="page sol sol--brand sol--{p["slug"]}" data-theme="light">']

    # full-viewport still hero --------------------------------------------
    hv = p["hero"]["visual"]
    out.append('<section class="sol-hero-full section--black" data-nav="image" data-nav-fill="bg-transparent">'
               f'<img class="sol-hero-full__img" src="{c(ref + ".hero.visual.src")}" alt="{c(ref + ".hero.visual.alt")}" '
               f'width="1920" height="1080" style="object-position: {c(ref + ".hero.visual.position", "50% 50%")}" '
               'decoding="async" fetchpriority="high">'
               '<span class="sol-hero-full__scrim" aria-hidden="true"></span>'
               '<div class="sol-hero-full__inner">'
               '<img class="sol-hero-full__mark" src="/assets/brand/logos/hypjam-icon.svg" alt="" width="68" height="68" decoding="async">'
               f'<p class="sol-hero-full__eyebrow">{c(ref + ".hero.eyebrow")}</p>'
               f'<h1 class="sol-hero-full__title">{c(ref + ".hero.h1")}</h1>'
               f'<p class="sol-hero-full__intro">{c(ref + ".hero.intro")}</p>'
               f'<div class="sol-hero-full__cta">{btn_dark(c(ref + ".hero.cta.label"), c(ref + ".hero.cta.href"))}</div>'
               '</div></section>')

    out.append('<div class="sol-body" data-nav="light" data-nav-fill="bg-white">')

    # statement + three facts ---------------------------------------------
    out.append(facts_block(data, ref + ".facts", p["facts"]))

    # where hypjam fits ----------------------------------------------------
    cells = []
    for k, it in enumerate(p["fits"]["items"]):
        link = ""
        ln = it.get("link") or {}
        if ln:
            href = service_href(data, ln["service"]) if ln.get("service") else c(f"{ref}.fits.items.{k}.link.href")
            label = (service_label(data, ln["service"]) if ln.get("service") and not ln.get("label")
                     else c(f"{ref}.fits.items.{k}.link.label"))
            link = f'<a class="page-link sol-fits__link" href="{href}">{label}</a>'
        cells.append('<li class="sol-fits__cell">'
                     f'<h3 class="sol-fits__title">{c(f"{ref}.fits.items.{k}.title")}</h3>'
                     '<span class="sol-fits__dash" aria-hidden="true"></span>'
                     f'<p class="sol-fits__body">{c(f"{ref}.fits.items.{k}.body")}</p>{link}</li>')
    out.append('<section class="page-section page-section--problems">'
               + split(c(ref + ".fits.eyebrow"),
                       f'<h2 class="page-h2">{c(ref + ".fits.h2")}</h2><p class="page-p">{c(ref + ".fits.p")}</p>',
                       "page-split--steps")
               + f'<ul class="sol-fits">{"".join(cells)}</ul></section>')

    # the band -------------------------------------------------------------
    out.append('<section class="page-section page-section--faq"><div class="sol-band">'
               f'<img class="sol-band__img" src="{c(ref + ".band.visual.src")}" alt="{c(ref + ".band.visual.alt")}" '
               f'width="1864" height="517" style="object-position: {c(ref + ".band.visual.position", "50% 50%")}" '
               'loading="lazy" decoding="async">'
               '<span class="sol-band__scrim" aria-hidden="true"></span>'
               '<div class="sol-band__inner">'
               '<img class="sol-band__mark" src="/assets/brand/logos/hypjam-icon.svg" alt="" width="68" height="68" loading="lazy" decoding="async">'
               f'<h2 class="sol-band__h2">{c(ref + ".band.h2")}</h2>'
               f'<p class="sol-band__sub">{c(ref + ".band.sub")}</p>'
               '</div></div></section>')

    out.append(steps_block(data, ref + ".how", p["how"]))
    out.append('<section class="page-section page-section--faq">'
               + quote_block(data, ref + ".quote", p["quote"])
               + faq_block(data, ref + ".faq", p["faq"]) + "</section>")
    out.append(related_block(data, ref + ".related", p["related"]))
    out.append("{{include:partials/page-cta.html}}\n</div>\n</main>\n"
               "{{include:partials/footer.html}}\n{{include:partials/scripts.html}}\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------

def main() -> int:
    data = json.loads(CONTENT.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []

    target = OUT_DIR / "index.html"
    target.write_text(render_index(data), encoding="utf-8")
    written.append(target)

    for i, p in enumerate(data["pages"]):
        html = render_brand(data, i, p) if p.get("group") == "brand" else render_goal(data, i, p)
        target = OUT_DIR / f"{p['slug']}.html"
        target.write_text(html, encoding="utf-8")
        written.append(target)

    keep = {t.name for t in written}
    for old in OUT_DIR.glob("*.html"):
        if old.name not in keep and GENERATED in old.read_text(encoding="utf-8", errors="ignore"):
            old.unlink()
            print("removed", old.relative_to(ROOT))

    for t in written:
        print("wrote", t.relative_to(ROOT))
    if MISSING_ICONS:
        print("render_solutions: no drawing for icon(s):", ", ".join(sorted(MISSING_ICONS)))
    if MISSING_MOCKS:
        print("render_solutions: no builder for mock(s):", ", ".join(sorted(MISSING_MOCKS)))
    if MISSING_ROOMS:
        print("render_solutions: hq.svg room group(s) missing, used the footer drawing:",
              ", ".join(str(r) for r in sorted(MISSING_ROOMS)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
