#!/usr/bin/env python3
"""render_compare.py — writes src/partials/home/compare.html from content/home.json → compare.

"Playhead" comparison (research: ~/Desktop/UGC Agency/research/conversion-redesign/
07-comparison-checklist-design.md, treatment A). A real <table>, read like an edit
timeline: each criterion is a track and hypjam is where the playhead sits — the last
column, marked only by a 2px orange line topped with the play triangle from hypjam's
hook logo. Marks are black-ink Harvey balls (full = Included, half = Depends, empty =
Not included), identical in every column; every cell also carries a short note, and a
screen-reader label states the state in words. The foot row says who each route suits,
with hypjam's price and the Book a call button in its own column.

The content (content/home.json → compare) follows a strict rubric: Included = the route
normally provides it; Depends = mixed, ask them (never used for hypjam); Not included =
you would do it yourself or buy it separately. A note never contradicts its state.

Static ARIA table roles are emitted because phones re-lay the table out with CSS
display changes (which otherwise strips table semantics in some browsers).

    python3 tools/render_compare.py && python3 build.py
"""
import html, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "content/home.json")
OUT = os.path.join(ROOT, "src/partials/home/compare.html")
E = html.escape
ARROW = ('<span class="btn__ico"><svg viewBox="0 0 12 12" width="11" height="11" aria-hidden="true">'
         '<path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" fill="none" stroke="currentColor" stroke-width="1.3" '
         'stroke-linecap="round" stroke-linejoin="round"/></svg></span>')


def main():
    c = json.load(open(SRC, encoding="utf-8"))["compare"]
    cols, rows, labels = c["columns"], c["rows"], c["stateLabels"]
    order = list(range(1, len(cols))) + [0]          # alternatives first, hypjam last
    o = []
    o.append("<!-- GENERATED by tools/render_compare.py from content/home.json → compare. Do not edit by hand. -->")
    o.append('<section id="compare" class="cmp" data-nav="light" data-nav-fill="bg-sand-s" data-cmp aria-labelledby="cmp-h2">')
    o.append('  <div class="cmp-head">')
    o.append('    <div class="cmp-head-main">')
    o.append(f'      <p class="cmp-eyebrow t-eyebrow">{E(c["eyebrow"])}</p>')
    o.append(f'      <h2 class="cmp-h2 t-h2" id="cmp-h2">{E(c["heading"])}</h2>')
    o.append(f'      <p class="cmp-sub">{E(c["sub"])}</p>')
    o.append('    </div>')
    o.append('    <div class="cmp-key" aria-hidden="true">')
    o.append(f'      <p class="cmp-key-h">{E(c.get("keyLabel", "Key"))}</p>')
    o.append('      <ul>' + "".join(f'<li><span class="cmp-mk cmp-mk--{st}"></span>{E(labels[st])}</li>' for st in ("yes", "varies", "no")) + '</ul>')
    o.append('    </div>')
    o.append('  </div>')

    # phones: a helper line, then a sticky switch holding only the three buttons (short tab
    # labels so they fit one row at 360px). Without JavaScript the switch stays hidden and
    # the table shows all four columns as 2 x 2 cells under each row label (data-alt="all").
    o.append(f'  <p class="cmp-helper" aria-hidden="true">{E(c["helper"])}</p>')
    o.append(f'  <div class="cmp-switch" role="group" aria-label="{E(c["switchLabel"])}" data-cmp-switch hidden>')
    for i in range(1, len(cols)):
        o.append(f'    <button type="button" class="cmp-switch-b" aria-pressed="{"true" if i == 1 else "false"}" aria-controls="cmp-table" data-cmp-alt="{i}" data-name="{E(cols[i]["name"])}">{E(cols[i].get("tab") or cols[i]["short"])}</button>')
    o.append('  </div>')
    o.append('  <p class="u-sr-only" aria-live="polite" data-cmp-status></p>')

    o.append('  <div class="cmp-wrap" data-alt="all">')
    o.append('    <span class="cmp-playhead" aria-hidden="true"></span>')
    o.append('    <table class="cmp-table" id="cmp-table" role="table">')
    o.append(f'      <caption class="u-sr-only">{E(c["caption"])}</caption>')
    o.append('      <colgroup><col class="cmp-c-crit"><col class="cmp-c-alt" span="3"><col class="cmp-c-us"></colgroup>')
    o.append('      <thead role="rowgroup"><tr role="row">')
    o.append(f'        <td class="cmp-corner" role="cell"><span class="u-sr-only">{E(c["criterionLabel"])}</span></td>')
    for i in order:
        col = cols[i]
        if i == 0:
            inner = (f'<img class="cmp-logo" src="/assets/brand/logos/hook-wordmark-on-light.svg" alt="{E(col["name"])}" width="66" height="24">'
                     f'<span class="cmp-col-sub">{E(col["sub"])}</span>')
            o.append(f'        <th scope="col" role="columnheader" class="cmp-col cmp-col--us" data-col="0">{inner}</th>')
        else:
            o.append(f'        <th scope="col" role="columnheader" class="cmp-col" data-col="{i}"><span class="cmp-col-name">{E(col["name"])}</span><span class="cmp-col-sub">{E(col["sub"])}</span></th>')
    o.append('      </tr></thead>')
    o.append('      <tbody role="rowgroup">')
    for r, row in enumerate(rows):
        assert len(row["cells"]) == len(cols), f"row {r}: {len(row['cells'])} cells"
        assert row["cells"][0]["state"] != "varies", f"row {r}: hypjam never 'Depends' (rubric)"
        o.append('        <tr role="row">')
        o.append(f'          <th scope="row" role="rowheader" class="cmp-crit"><span class="cmp-n" aria-hidden="true">{r + 1:02d}</span>{E(row["label"])}</th>')
        for i in order:
            cell = row["cells"][i]
            us = " cmp-cell--us" if i == 0 else ""
            o.append(f'          <td role="cell" class="cmp-cell{us}" data-col="{i}"><span class="cmp-mk cmp-mk--{cell["state"]}" aria-hidden="true"></span>'
                     f'<span class="cmp-note"><span class="u-sr-only">{E(labels[cell["state"]])}: </span>{E(cell["note"])}</span></td>')
        o.append('        </tr>')
    o.append('      </tbody>')
    f = c["foot"]
    o.append('      <tfoot role="rowgroup"><tr role="row">')
    o.append(f'        <th scope="row" role="rowheader" class="cmp-crit cmp-crit--foot">{E(f["label"])}</th>')
    for i in order:
        if i == 0:
            o.append(f'        <td role="cell" class="cmp-cell cmp-cell--us cmp-cell--foot" data-col="0"><p class="cmp-fit">{E(f["cells"][0])}</p>'
                     f'<p class="cmp-price">{E(c["price"])}</p>'
                     f'<a class="btn btn--lg btn--cta cmp-cta" href="{E(c["cta"]["href"])}" data-cta="compare">{E(c["cta"]["label"])}{ARROW}</a>'
                     f'<p class="cmp-cta-note">{E(c["ctaNote"])}</p></td>')
        else:
            o.append(f'        <td role="cell" class="cmp-cell cmp-cell--foot" data-col="{i}"><p class="cmp-fit">{E(f["cells"][i])}</p></td>')
    o.append('      </tr></tfoot>')
    o.append('    </table>')
    o.append('  </div>')
    o.append(f'  <details class="cmp-method"><summary>{E(c["method"]["summary"])}</summary><p>{E(c["method"]["body"])}</p></details>')
    o.append('</section>')
    open(OUT, "w", encoding="utf-8").write("\n".join(o) + "\n")
    print(f"compare.html written: {len(rows)} rows x {len(cols)} columns (hypjam last)")


if __name__ == "__main__":
    main()
