#!/usr/bin/env python3
"""render_blog.py — stamps out the content-driven inner pages from content/*.json.

Writes (all under src/pages/):
  blog/index.html            the blog index (content/blog.json)         → /blog
  blog/<slug>.html ×8        the article template, one per article      → /blog/<slug>
  privacy.html, terms.html   the legal template (content/legal.json)    → /privacy, /terms
  process.html               the documentation-style page (process.json)→ /process
  faq.html                   two accordion groups (faq.json)            → /faq
  agency.html                the agency page (agency.json)              → /agency
  join.html                  the creator roster page (join.json)        → /join

Why one renderer for all of them: every one of these pages is a loop over
JSON arrays (eight articles, ten legal sections, fourteen FAQ items, three
weeks × four topics × blocks …). Hand-writing {{content:…}} tokens for each
index is brittle; generating them keeps content/*.json the single source of
truth (build.py runs this before it expands pages, so a JSON edit flows
through on the next build). Text nodes are still emitted as
{{content:file.path}} tokens wherever the value is a plain string; only
derived output (rendered Markdown, related-article picks, JSON-LD, escaped
attribute values) is written literally.

Markdown → HTML is tools/md.py. Standard library only. Idempotent.
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import md  # noqa: E402  (tools/md.py)

CONTENT = ROOT / "content"
PAGES = ROOT / "src" / "pages"
BASE_URL = "https://hypjam.vercel.app"
GEN = "<!-- generated by tools/render_blog.py — edit content/%s.json, not this file -->"

ARROW = ('<svg viewBox="0 0 12 12" width="11" height="11" aria-hidden="true"><path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" '
         'fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
ARROW_LEFT = ('<svg viewBox="0 0 12 12" width="11" height="11" aria-hidden="true"><path d="M10.5 6h-8M5.8 2.5 2.3 6l3.5 3.5" '
              'fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
CHECK = ('<svg viewBox="0 0 14 14" width="14" height="14" aria-hidden="true"><circle cx="7" cy="7" r="6" fill="none" '
         'stroke="currentColor" stroke-width="1.2"/><path d="M4.3 7.2l1.9 1.9 3.6-4" fill="none" stroke="currentColor" '
         'stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
BOOK = ('<svg viewBox="0 0 18 18" width="18" height="18" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.3" '
        'stroke-linecap="round" stroke-linejoin="round"><path d="M9 4.5c-1.6-1.2-3.8-1.5-6.5-1.2v11c2.7-.3 4.9 0 6.5 1.2 1.6-1.2 3.8-1.5 6.5-1.2v-11C12.8 3 10.6 3.3 9 4.5z"/><path d="M9 4.5v11"/></svg>')


def T(path: str) -> str:
    """A {{content:…}} token for a text node."""
    return "{{content:" + path + "}}"


def esc(s) -> str:
    return html.escape(str(s), quote=True)


def load(name: str):
    return json.loads((CONTENT / f"{name}.json").read_text(encoding="utf-8"))


def write(rel: str, text: str) -> None:
    target = PAGES / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and target.read_text(encoding="utf-8") == text:
        print("ok   ", f"src/pages/{rel}")
        return
    target.write_text(text, encoding="utf-8")
    print("wrote", f"src/pages/{rel}")


def meta_block(title: str, description: str, nav: str, fill: str, body_class: str, head_extra: str = "", robots: str = "") -> str:
    lines = [f"<!-- title: {esc(title)} -->", f"<!-- description: {esc(description)} -->"]
    if robots:
        lines.append(f"<!-- robots: {robots} -->")
    lines += [f"<!-- nav: {nav} -->", f"<!-- nav-fill: {fill} -->", f"<!-- body-class: {body_class} -->"]
    if head_extra:
        lines.append(f"<!-- head-extra: {head_extra} -->")
    return "\n".join(lines)


def jsonld(obj) -> str:
    return '<script type="application/ld+json">' + json.dumps(obj, ensure_ascii=False).replace("</", "<\\/") + "</script>"


def btn_html(label: str, href: str, cls: str = "") -> str:
    c = ("btn " + cls).strip()
    return f'<a class="{c}" href="{esc(href)}">{label}<span class="btn__ico">{ARROW}</span></a>'


# ---------------------------------------------------------------------------
# line-drawn motifs for the blog cards (viewBox 0 0 240 160, monoline, 1.25px)
# ---------------------------------------------------------------------------

GROUND = '<path d="M40 152h160" stroke-opacity=".4"/>'
MOTIFS = {
    "phone-on-tripod": (
        '<rect x="99" y="22" width="42" height="80" rx="7"/><rect x="104" y="30" width="32" height="64" rx="3"/>'
        '<path d="M114 26h12"/><circle class="art-jam-fill" cx="110" cy="38" r="2.2"/>'
        '<path d="M120 102v10M108 112h24M120 112 96 152M120 112l24 40M120 112v40M104 136h32"/>' + GROUND
    ),
    "two-phones": (
        '<rect x="62" y="30" width="46" height="94" rx="7"/><rect x="67" y="38" width="36" height="78" rx="3"/>'
        '<path class="art-jam-fill" d="M80 68v18l14-9z"/>'
        '<rect x="132" y="30" width="46" height="94" rx="7"/><rect x="137" y="38" width="36" height="78" rx="3"/>'
        '<path d="M155 98c-8-6-12-10-12-15a6 6 0 0 1 12-2 6 6 0 0 1 12 2c0 5-4 9-12 15z"/><path d="M146 54h18M146 62h12"/>' + GROUND
    ),
    "brief-sheet": (
        '<path d="M78 22h64l20 20v96H78z"/><path d="M142 22v20h20"/><path d="M92 56h40M92 68h52M92 80h30"/>'
        '<rect x="92" y="96" width="10" height="10" rx="2"/><path class="art-jam-stroke" d="M94 101l3 3 5-6"/>'
        '<rect x="92" y="114" width="10" height="10" rx="2"/><path d="M94 119l3 3 5-6"/><path d="M108 101h36M108 119h28"/>' + GROUND
    ),
    "hook-cards": (
        '<rect x="60" y="66" width="100" height="60" rx="5"/><rect x="72" y="52" width="100" height="60" rx="5"/>'
        '<rect x="84" y="38" width="100" height="60" rx="5"/><path d="M96 56h50M96 68h68M96 80h40"/>'
        '<path class="art-jam-stroke" d="M172 44v12a7 7 0 0 1-14 0"/>' + GROUND
    ),
    "invoice-strip": (
        '<path d="M84 22h72v122l-9-6-9 6-9-6-9 6-9-6-9 6-9-6-9 6z"/><path d="M98 44h44M98 58h30M98 72h44M98 86h24"/>'
        '<path d="M98 104h44" stroke-width="2"/><circle class="art-jam-stroke" cx="132" cy="122" r="9"/>' + GROUND
    ),
    "testing-grid": (
        "".join(f'<rect x="{x}" y="{y}" width="18" height="32" rx="3"/>' for y in (24, 66, 108) for x in (77, 111, 145))
        + '<path class="art-jam-stroke" d="M116 82l3 3 6-7M150 40l3 3 6-7"/>' + GROUND
    ),
    "handle-switch": (
        '<circle cx="76" cy="70" r="24"/><circle cx="76" cy="62" r="8"/><path d="M60 88c4-8 10-11 16-11s12 3 16 11"/>'
        '<circle cx="164" cy="70" r="24"/><rect x="152" y="58" width="24" height="24" rx="5"/><path d="M158 64h12M158 70h12M158 76h8"/>'
        '<path d="M108 64h24M126 58l6 6-6 6M132 76h-24M114 70l-6 6 6 6"/>'
        '<rect x="104" y="110" width="32" height="16" rx="8"/><circle class="art-jam-fill" cx="128" cy="118" r="5"/>' + GROUND
    ),
    "ring-light": (
        '<circle cx="120" cy="66" r="44"/><circle cx="120" cy="66" r="36"/><rect x="110" y="48" width="20" height="36" rx="3"/>'
        '<path d="M116 52h8"/><circle class="art-jam-fill" cx="114" cy="57" r="1.6"/>'
        '<path d="M120 110v34M100 144h40M120 128l-14 16M120 128l14 16"/>' + GROUND
    ),
}


def motif(key: str) -> str:
    inner = MOTIFS.get(key) or MOTIFS["phone-on-tripod"]
    return ('<svg class="blog-art" viewBox="0 0 240 160" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.25" '
            'stroke-linecap="round" stroke-linejoin="round"><g vector-effect="non-scaling-stroke">' + inner + "</g></svg>")


# ---------------------------------------------------------------------------
# blog
# ---------------------------------------------------------------------------

def render_blog() -> None:
    blog = load("blog")
    agency = load("agency")
    arts = blog["articles"]
    link_map = blog.get("link_map", {})
    ap = blog["article_page"]

    # ---- index -----------------------------------------------------------
    filters = blog["filters"]
    pills = []
    for i, f in enumerate(filters):
        key = "all" if i == 0 else f
        pressed = "true" if i == 0 else "false"
        pills.append(f'<button type="button" class="blog-filter" data-filter="{esc(key)}" aria-pressed="{pressed}">{T(f"blog.filters.{i}")}</button>')

    cards = []
    for i, a in enumerate(arts):
        cards.append(
            f'<a class="blog-card" href="{esc(a["href"])}" data-cat="{esc(a["category"])}">'
            f'<span class="blog-card-art" aria-hidden="true">{motif(a.get("art", ""))}</span>'
            f'<span class="blog-card-cap"><b class="blog-card-date">{T(f"blog.articles.{i}.date_label")}</b> '
            f'<span class="blog-card-title">{T(f"blog.articles.{i}.title")}</span></span></a>'
        )

    index_ld = jsonld({
        "@context": "https://schema.org",
        "@type": "Blog",
        "name": blog["hero"]["h1"],
        "url": BASE_URL + blog["meta"]["path"],
        "description": blog["meta"]["description"],
        "publisher": {"@type": "Organization", "name": "hypjam", "url": BASE_URL},
        "blogPost": [{"@type": "BlogPosting", "headline": a["title"], "url": BASE_URL + a["href"],
                      "datePublished": a["date"], "author": {"@type": "Person", "name": agency["founder"]["name"]}} for a in arts],
    })

    index_page = "\n".join([
        meta_block(blog["meta"]["title"], blog["meta"]["description"], "dark", "bg-transparent", "page-blog", index_ld),
        GEN % "blog",
        "{{include:partials/head.html}}",
        "{{include:partials/nav.html}}",
        '<main class="blog" data-theme="light">',
        '  <section class="blog-hero" data-nav="dark" data-nav-fill="bg-transparent">',
        '    <img class="blog-hero-bg" src="/assets/video/hero-poster.jpg" alt="" width="1280" height="720" decoding="async" fetchpriority="high">',
        '    <div class="blog-hero-shade" aria-hidden="true"></div>',
        '    <div class="blog-hero-body">',
        f'      <img class="blog-hero-mark" src="{esc(blog["hero"]["mark"])}" alt="" width="52" height="52">',
        f'      <h1 class="blog-hero-h1">{T("blog.hero.h1")}</h1>',
        f'      <p class="blog-hero-sub">{T("blog.hero.sub")}</p>',
        "    </div>",
        "  </section>",
        '  <section class="blog-list section--sand-m" data-nav="light" data-nav-fill="bg-sand-m">',
        '    <div class="blog-filters" role="group" aria-label="Filter articles">',
        "      " + "\n      ".join(pills),
        "    </div>",
        '    <div class="blog-grid">',
        "      " + "\n      ".join(cards),
        "    </div>",
        "  </section>",
        "</main>",
        "<script>(function(){var b=document.querySelectorAll('.blog-filter'),c=document.querySelectorAll('.blog-card');"
        "for(var i=0;i<b.length;i++){b[i].addEventListener('click',function(){var f=this.getAttribute('data-filter');"
        "for(var j=0;j<b.length;j++)b[j].setAttribute('aria-pressed',b[j]===this?'true':'false');"
        "for(var k=0;k<c.length;k++)c[k].hidden=!(f==='all'||c[k].getAttribute('data-cat')===f);"
        "if(window.ScrollTrigger&&ScrollTrigger.refresh)ScrollTrigger.refresh();});}})();</script>",
        "{{include:partials/footer.html}}",
        "{{include:partials/scripts.html}}",
        "",
    ])
    write("blog/index.html", index_page)

    # ---- articles --------------------------------------------------------
    for i, a in enumerate(arts):
        src_path = Path(a["body"])
        if not src_path.is_file():
            print(f"  ! missing article body: {src_path}", file=sys.stderr)
            continue
        body_html, toc = md.md_to_html(src_path.read_text(encoding="utf-8"), link_map=link_map, lede=True)
        # the article's own opening paragraph becomes the deck under the h1,
        # where ref/pages/hotels_aloft-dublin.jpg puts its four-line lede
        lede_html, body_html = md.take_lede(body_html)
        deck = lede_html or T(f"blog.articles.{i}.description")
        h2s = [(sid, txt) for sid, txt, lvl in toc if lvl == 2]

        # related: same category first, then editorial order, never itself
        same = [b for b in arts if b is not a and b["category"] == a["category"]]
        rest = [b for b in arts if b is not a and b["category"] != a["category"]]
        related = (same + rest)[: int(ap.get("related_count", 3))]

        canonical = BASE_URL + a["href"]
        ld = jsonld({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": a["title"],
            "description": a["description"],
            "datePublished": a["date"],
            "dateModified": a["date"],
            "articleSection": a["category"],
            "wordCount": a.get("words"),
            "inLanguage": "en-GB",
            "url": canonical,
            "mainEntityOfPage": {"@type": "WebPage", "@id": canonical},
            "image": BASE_URL + "/assets/brand/og.png",
            "author": {"@type": "Person", "name": agency["founder"]["name"], "jobTitle": agency["founder"]["role"], "url": BASE_URL + "/agency"},
            "publisher": {"@type": "Organization", "name": "hypjam", "url": BASE_URL,
                          "logo": {"@type": "ImageObject", "url": BASE_URL + "/assets/brand/og.png"}},
        })

        toc_html = "".join(f'<li class="blog-rail-toc-i"><a class="blog-rail-toc-a" href="#{esc(sid)}">{html.escape(txt, quote=False)}</a></li>' for sid, txt in h2s)

        more = []
        for b in related:
            j = arts.index(b)
            more.append(
                f'<a class="blog-story" href="{esc(b["href"])}">'
                f'<span class="blog-story-tile" aria-hidden="true">{motif(b.get("art", ""))}</span>'
                f'<span class="blog-story-quote">{T(f"blog.articles.{j}.title")}</span>'
                f'<span class="blog-story-foot"><span class="blog-story-meta"><span class="blog-story-cat">{T(f"blog.articles.{j}.category")}</span>'
                f'<span class="blog-story-sub">{T(f"blog.articles.{j}.date_label")} · {T(f"blog.articles.{j}.reading_minutes")} min read</span></span>'
                f'<span class="blog-story-read arrow-link">Read {ARROW}</span></span></a>'
            )

        page = "\n".join([
            meta_block(a["title"] + " | hypjam", a["description"], "light", "bg-white", "page-blog page-blog-article", ld),
            GEN % "blog",
            "{{include:partials/head.html}}",
            "{{include:partials/nav.html}}",
            '<main class="blog blog-article" data-theme="light">',
            '  <article>',
            '  <section class="blog-art-hero">',
            f'    <a class="blog-back" href="{esc(ap["back"]["href"])}">{ARROW_LEFT}{T("blog.article_page.back.label")}</a>',
            f'    <p class="blog-art-eyebrow t-eyebrow">{T(f"blog.articles.{i}.date_label")} · {T(f"blog.articles.{i}.reading_minutes")} min read · {T(f"blog.articles.{i}.category")}</p>',
            f'    <h1 class="blog-art-title t-h2">{T(f"blog.articles.{i}.title")}</h1>',
            f'    <p class="blog-art-desc">{deck}</p>',
            f'    <div class="blog-art-banner" aria-hidden="true">{motif(a.get("art", ""))}</div>',
            "  </section>",
            '  <section class="blog-art-body">',
            '    <aside class="blog-rail">',
            '      <dl class="blog-rail-list">',
            f'        <div class="blog-rail-item"><dt class="blog-rail-k">Written by</dt><dd class="blog-rail-v">{T("agency.founder.name")}<br><span class="blog-rail-dim">{T("agency.founder.role")}</span></dd></div>',
            f'        <div class="blog-rail-item"><dt class="blog-rail-k">Published</dt><dd class="blog-rail-v">{T(f"blog.articles.{i}.date_label")}</dd></div>',
            f'        <div class="blog-rail-item"><dt class="blog-rail-k">Category</dt><dd class="blog-rail-v">{T(f"blog.articles.{i}.category")}</dd></div>',
            f'        <div class="blog-rail-item"><dt class="blog-rail-k">Reading time</dt><dd class="blog-rail-v">{T(f"blog.articles.{i}.reading_minutes")} min</dd></div>',
            f'        <div class="blog-rail-item"><dt class="blog-rail-k">In this guide</dt><dd class="blog-rail-v"><ol class="blog-rail-toc">{toc_html}</ol></dd></div>',
            "      </dl>",
            "    </aside>",
            '    <div class="blog-col">',
            '      <div class="blog-prose">',
            body_html,
            "      </div>",
            '      <div class="blog-facts" aria-label="About this guide">',
            f'        <div class="blog-fact"><span class="blog-fact-n">{T(f"blog.articles.{i}.reading_minutes")}</span><span class="blog-fact-l">minute read, start to finish</span></div>',
            '        <span class="blog-fact-rule" aria-hidden="true"></span>',
            f'        <div class="blog-fact"><span class="blog-fact-n">{len(h2s)}</span><span class="blog-fact-l">sections, each one linked in the rail</span></div>',
            "      </div>",
            "    </div>",
            "  </section>",
            "  </article>",
            '  <section class="blog-more">',
            '    <div class="blog-more-head">',
            '      <h2 class="blog-more-h2">More guides</h2>',
            f'      <a class="arrow-link" href="{esc(ap["back"]["href"])}">{T("blog.article_page.back.label")} {ARROW}</a>',
            "    </div>",
            '    <div class="blog-more-grid">',
            "      " + "\n      ".join(more),
            "    </div>",
            "  </section>",
            '  <section class="blog-cta section--sand-s">',
            f'    <h2 class="blog-cta-h2 t-h2">{T("blog.article_page.cta.h2")}</h2>',
            f'    <p class="blog-cta-p">{T("blog.article_page.cta.p")}</p>',
            "    " + btn_html(T("blog.article_page.cta.button.label"), ap["cta"]["button"]["href"], "btn--lg"),
            "  </section>",
            "</main>",
            "{{include:partials/footer.html}}",
            "{{include:partials/scripts.html}}",
            "",
        ])
        write(f"blog/{a['slug']}.html", page)


# ---------------------------------------------------------------------------
# legal
# ---------------------------------------------------------------------------

def render_legal() -> None:
    legal = load("legal")
    related = legal.get("related", [])
    for key, pg in legal["pages"].items():
        src_path = Path(pg["source"])
        if not src_path.is_file():
            print(f"  ! missing legal source: {src_path}", file=sys.stderr)
            continue
        rendered, _toc = md.md_to_html(src_path.read_text(encoding="utf-8"), strip_last_updated=True)
        intro, secs = md.sections(rendered)

        rel_links = []
        for r in related:
            cur = ' aria-current="page"' if r["href"] == pg["path"] else ""
            rel_links.append(f'<a class="legal-rel-a" href="{esc(r["href"])}"{cur}>{html.escape(r["label"], quote=False)}</a>')

        sec_html = []
        for n, (head, body) in enumerate(secs, start=1):
            sec_html.append(
                '      <section class="legal-sec">\n'
                f'        <span class="legal-num" aria-hidden="true">{n}</span>\n'
                '        <div class="legal-sec-body">\n'
                f"          {head}\n{body}\n"
                "        </div>\n"
                "      </section>"
            )

        ld = jsonld({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": pg["h1"],
            "url": BASE_URL + pg["path"],
            "description": pg["description"],
            "dateModified": pg["last_updated"],
            "inLanguage": "en-GB",
            "publisher": {"@type": "Organization", "name": "hypjam", "url": BASE_URL},
        })

        page = "\n".join([
            meta_block(pg["title"], pg["description"], "light", "bg-sand-s", "page-legal", ld),
            GEN % "legal",
            "{{include:partials/head.html}}",
            "{{include:partials/nav.html}}",
            '<main class="legal" data-theme="sand">',
            '  <div class="legal-wrap">',
            f'    <a class="legal-back" href="/">{ARROW_LEFT}Back to home</a>',
            f'    <p class="legal-eyebrow t-eyebrow">{T(f"legal.pages.{key}.eyebrow")}</p>',
            f'    <h1 class="legal-h1">{T(f"legal.pages.{key}.h1")}</h1>',
            f'    <p class="legal-updated">Last updated {T(f"legal.pages.{key}.last_updated")}</p>',
            f'    <nav class="legal-related" aria-label="Legal pages">{" ".join(rel_links)}</nav>',
            f'    <div class="legal-intro">\n{intro}\n    </div>',
            '    <div class="legal-secs">',
            "\n".join(sec_html),
            "    </div>",
            "  </div>",
            "</main>",
            "{{include:partials/footer.html}}",
            "{{include:partials/scripts.html}}",
            "",
        ])
        write(f"{key}.html", page)


# ---------------------------------------------------------------------------
# process (documentation-style page)
# ---------------------------------------------------------------------------

ICONS = {
    "box": '<path d="M2 5.5 8 2.5l6 3v6l-6 3-6-3z"/><path d="M2 5.5l6 3 6-3M8 8.5v6"/>',
    "voice": '<path d="M8 2.5a2.5 2.5 0 0 1 2.5 2.5v3a2.5 2.5 0 0 1-5 0V5A2.5 2.5 0 0 1 8 2.5z"/><path d="M3.5 8a4.5 4.5 0 0 0 9 0M8 12.5v1.5"/>',
    "checklist": '<path d="M2.5 4.5l1.5 1.5 2.5-3M2.5 9.5l1.5 1.5 2.5-3M8.5 4.5h5M8.5 10h5"/>',
    "tick": '<circle cx="8" cy="8" r="5.5"/><path d="M5.3 8.2l1.9 1.9 3.6-4"/>',
    "key": '<circle cx="5.5" cy="10.5" r="3"/><path d="M7.6 8.4 13.5 2.5M11 5l2 2M9.5 6.5l1.5 1.5"/>',
    "calendar": '<rect x="2.5" y="3.5" width="11" height="10" rx="1.5"/><path d="M2.5 7h11M5.5 2v3M10.5 2v3"/>',
}


def icon(name: str, size: int = 16) -> str:
    inner = ICONS.get(name, ICONS["tick"])
    return (f'<svg viewBox="0 0 16 16" width="{size}" height="{size}" aria-hidden="true" fill="none" stroke="currentColor" '
            f'stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round">{inner}</svg>')


def proc_blocks(base: str, blocks: list) -> str:
    out = []
    for bi, b in enumerate(blocks):
        bp = f"{base}.blocks.{bi}"
        out.append(f'<h4 class="proc-h4">{T(bp + ".h4")}</h4>')
        kind = b.get("kind", "p")
        if kind == "p":
            out.append(f'<p class="proc-p">{T(bp + ".text")}</p>')
        elif kind == "ol":
            out.append('<ol class="proc-ol">' + "".join(
                f'<li class="proc-ol-i"><span class="proc-n" aria-hidden="true">{k + 1}</span><span>{T(f"{bp}.items.{k}")}</span></li>'
                for k in range(len(b.get("items", [])))) + "</ol>")
        else:
            out.append('<ul class="proc-ul">' + "".join(
                f'<li class="proc-ul-i"><span class="proc-check" aria-hidden="true">{CHECK}</span><span>{T(f"{bp}.items.{k}")}</span></li>'
                for k in range(len(b.get("items", [])))) + "</ul>")
    return "\n".join(out)


def proc_topics(base: str, topics: list) -> str:
    rows = []
    for ti, t in enumerate(topics):
        tp = f"{base}.topics.{ti}"
        link = ""
        if t.get("link"):
            link = f'<a class="proc-topic-link" href="{esc(t["link"]["href"])}">{T(tp + ".link.label")} {ARROW}</a>'
        rows.append(
            '        <div class="proc-topic">\n'
            f'          <div class="proc-topic-l"><h3 class="proc-h3">{T(tp + ".h3")}</h3><p class="proc-topic-sub">{T(tp + ".sub")}</p>{link}</div>\n'
            f'          <div class="proc-topic-r">\n{proc_blocks(tp, t.get("blocks", []))}\n          </div>\n'
            "        </div>"
        )
    return "\n".join(rows)


def proc_week_section(base: str, w: dict, count_label_token: str) -> str:
    return "\n".join([
        f'    <section class="proc-week" id="{esc(w["id"])}">',
        '      <div class="proc-week-card">',
        '        <header class="proc-week-head">',
        f'          <div class="proc-week-text"><span class="proc-tag proc-tag--jam">{T(base + ".tag")}</span><h2 class="proc-week-h2">{T(base + ".h2")}</h2><p class="proc-lead">{T(base + ".p")}</p></div>',
        f'          <div class="proc-count"><span class="proc-count-ico">{BOOK}</span><b class="proc-count-n">{len(w.get("topics", []))}</b><span class="proc-count-l">{count_label_token}</span></div>',
        "        </header>",
        '        <div class="proc-topics">',
        proc_topics(base, w.get("topics", [])),
        "        </div>",
        "      </div>",
        "    </section>",
    ])


def render_process() -> None:
    p = load("process")
    hero = load("hero")
    stop0 = (hero.get("stops") or [{}])[0]
    panel = hero and stop0.get("panel", "brief") or "brief"

    side = []
    for gi, g in enumerate(p["sidebar"]):
        side.append(f'<p class="proc-side-group">{T(f"process.sidebar.{gi}.group")}</p>')
        for ii, it in enumerate(g["items"]):
            side.append(f'<a class="proc-side-link" href="{esc(it["href"])}">{T(f"process.sidebar.{gi}.items.{ii}.label")}</a>')

    hero_links = "".join(
        f'<a class="proc-pill" href="{esc(l["href"])}">{T(f"process.hero.links.{i}.label")}</a>' for i, l in enumerate(p["hero"]["links"]))

    lib_cards = []
    for ci, c in enumerate(p["library"]["cards"]):
        cp = f"process.library.cards.{ci}"
        lib_cards.append(
            f'<a class="proc-card" href="{esc(c["link"]["href"])}"><span class="proc-tag">{T(cp + ".tag")}</span>'
            f'<h3 class="proc-card-h3">{T(cp + ".h3")}</h3><p class="proc-card-p">{T(cp + ".p")}</p>'
            f'<span class="proc-card-link">{T(cp + ".link.label")} {ARROW}</span></a>')

    weeks = [proc_week_section(f"process.weeks.{wi}", w, T(f"process.weeks.{wi}.guides_label")) for wi, w in enumerate(p["weeks"])]
    after = proc_week_section("process.after", p["after"], T("process.weeks.0.guides_label"))

    fb = p["first_brief"]
    table = ['<div class="proc-tbl"><table class="proc-table"><thead><tr>' + "".join(
        f'<th class="proc-th">{T(f"process.first_brief.columns.{ci}")}</th>' for ci in range(len(fb["columns"]))) + "</tr></thead><tbody>"]
    for ri, row in enumerate(fb["rows"]):
        table.append("<tr>" + "".join(f'<td class="proc-td">{T(f"process.first_brief.rows.{ri}.{ci}")}</td>' for ci in range(len(row))) + "</tr>")
    table.append("</tbody></table></div>")

    needs = "".join(
        f'<div class="proc-ref-card"><span class="proc-ref-ico">{icon(c.get("icon", "tick"))}</span><h3 class="proc-ref-h3">{T(f"process.needs.cards.{ci}.h3")}</h3><p class="proc-ref-p">{T(f"process.needs.cards.{ci}.p")}</p></div>'
        for ci, c in enumerate(p["needs"]["cards"]))

    pkgs = []
    for pi, pk in enumerate(p["packages"]["items"]):
        pp = f"process.packages.items.{pi}"
        inc = "".join(f'<li class="proc-ul-i"><span class="proc-check" aria-hidden="true">{CHECK}</span><span>{T(f"{pp}.includes.{k}")}</span></li>' for k in range(len(pk["includes"])))
        pkgs.append(
            f'<div class="proc-pkg"><h3 class="proc-pkg-name">{T(pp + ".name")}</h3><p class="proc-pkg-price">{T(pp + ".price")}</p>'
            f'<p class="proc-pkg-videos">{T(pp + ".videos")}</p><ul class="proc-ul proc-pkg-list">{inc}</ul>'
            f'<p class="proc-pkg-best"><span class="proc-pkg-best-k">Best for</span>{T(pp + ".best_for")}</p></div>')

    faqs = "".join(
        f'<div class="proc-faq"><h3 class="proc-faq-q">{T(f"process.faqs.items.{qi}.q")}</h3><p class="proc-faq-a">{T(f"process.faqs.items.{qi}.a")}</p></div>'
        for qi in range(len(p["faqs"]["items"])))

    ld = jsonld({
        "@context": "https://schema.org",
        "@type": "HowTo",
        "name": p["hero"]["h1"],
        "description": p["meta"]["description"],
        "inLanguage": "en-GB",
        "step": [{"@type": "HowToStep", "name": w["h2"], "text": w["p"], "url": BASE_URL + "/process#" + w["id"]} for w in p["weeks"]],
    })

    page = "\n".join([
        meta_block(p["meta"]["title"], p["meta"]["description"], "light", "bg-sand-s", "page-process", ld),
        GEN % "process",
        "{{include:partials/head.html}}",
        '<main class="proc" data-theme="sand">',
        '  <header class="proc-head">',
        f'    <a class="proc-home" href="{esc(p["docs_header"]["home"]["href"])}"><img src="/assets/brand/logos/hypjam-icon.svg" alt="" width="32" height="32"><span>{T("process.docs_header.home.label")}</span></a>',
        '    <nav class="proc-head-links" aria-label="Process links">',
        "      " + "".join(
            f'<a class="proc-head-link{" proc-head-link--solid" if li == len(p["docs_header"]["links"]) - 1 else ""}" href="{esc(l["href"])}">{T(f"process.docs_header.links.{li}.label")}</a>'
            for li, l in enumerate(p["docs_header"]["links"])),
        "    </nav>",
        "  </header>",
        '  <div class="proc-shell">',
        '    <aside class="proc-side"><nav class="proc-side-nav" aria-label="On this page">',
        "      " + "\n      ".join(side),
        "    </nav></aside>",
        '    <div class="proc-main">',
        '    <section class="proc-hero" id="home">',
        '      <div class="proc-hero-text">',
        f'        <p class="proc-eyebrow">{T("process.hero.eyebrow")}</p>',
        f'        <h1 class="proc-h1">{T("process.hero.h1")}</h1>',
        f'        <p class="proc-lead">{T("process.hero.p")}</p>',
        f'        <div class="proc-pills">{hero_links}</div>',
        "      </div>",
        f'      <div class="proc-hero-art" role="img" aria-label="{esc(p["hero"]["image"]["alt"])}">',
        '        <div class="proc-hud">',
        f'          <p class="proc-hud-title">{T("hero.stops.0.title")}</p>',
        f'          <p class="proc-hud-desc">{T("hero.stops.0.description")}</p>',
        '          <div class="proc-hud-hr" aria-hidden="true"></div>',
        f'          <div class="proc-hud-panel">{{{{panel:{panel}}}}}</div>',
        "        </div>",
        "      </div>",
        "    </section>",
        '    <section class="proc-library" id="library">',
        f'      <p class="proc-eyebrow">{T("process.library.eyebrow")}</p>',
        f'      <h2 class="proc-h2">{T("process.library.h2")}</h2>',
        f'      <p class="proc-lead">{T("process.library.p")}</p>',
        f'      <div class="proc-cards">{"".join(lib_cards)}</div>',
        "    </section>",
        "\n".join(weeks),
        after,
        f'    <section class="proc-band" id="{esc(fb["id"])}">',
        f'      <p class="proc-eyebrow">{T("process.first_brief.eyebrow")}</p>',
        f'      <h2 class="proc-h2">{T("process.first_brief.h2")}</h2>',
        f'      <p class="proc-lead">{T("process.first_brief.p")}</p>',
        "      " + "".join(table),
        "    </section>",
        f'    <section class="proc-ref" id="{esc(p["needs"]["id"])}">',
        f'      <p class="proc-eyebrow">{T("process.needs.eyebrow")}</p>',
        f'      <h2 class="proc-h2">{T("process.needs.h2")}</h2>',
        f'      <p class="proc-lead">{T("process.needs.p")}</p>',
        f'      <div class="proc-ref-grid">{needs}</div>',
        "    </section>",
        f'    <section class="proc-band" id="{esc(p["packages"]["id"])}">',
        f'      <p class="proc-eyebrow">{T("process.packages.eyebrow")}</p>',
        f'      <h2 class="proc-h2">{T("process.packages.h2")}</h2>',
        f'      <p class="proc-lead">{T("process.packages.p")}</p>',
        f'      <div class="proc-pkgs">{"".join(pkgs)}</div>',
        f'      <p class="proc-note">{T("process.packages.note")}</p>',
        "    </section>",
        f'    <section class="proc-faqs" id="{esc(p["faqs"]["id"])}">',
        f'      <p class="proc-eyebrow">{T("process.faqs.eyebrow")}</p>',
        f'      <h2 class="proc-h2">{T("process.faqs.h2")}</h2>',
        f'      <div class="proc-faq-grid">{faqs}</div>',
        "    </section>",
        f'    <section class="proc-support" id="{esc(p["support"]["id"])}">',
        f'      <p class="proc-eyebrow">{T("process.support.eyebrow")}</p>',
        f'      <h2 class="proc-h2">{T("process.support.h2")}</h2>',
        f'      <p class="proc-lead">{T("process.support.p")}</p>',
        f'      <div class="proc-support-card"><a class="proc-support-mail" href="{esc(p["support"]["href"])}">{T("process.support.email")}</a><p class="proc-support-note">{T("process.support.note")}</p></div>',
        "    </section>",
        "    </div>",
        "  </div>",
        '  <footer class="proc-foot">',
        f'    <p class="proc-foot-line">{T("process.footer_line")}</p>',
        '    <a class="proc-foot-home" href="/">hypjam.com {ARROW}</a>'.replace("{ARROW}", ARROW),
        "  </footer>",
        "</main>",
        # sidebar highlight + smooth anchors (Lenis-aware)
        "<script>(function(){var links=[].slice.call(document.querySelectorAll('.proc-side-link, .proc-pill, .proc-card, .proc-head-link'));"
        "var side=[].slice.call(document.querySelectorAll('.proc-side-link'));var head=document.querySelector('.proc-head');"
        "function off(){return (head?head.offsetHeight:64)+16;}"
        "links.forEach(function(a){var h=a.getAttribute('href')||'';if(h.charAt(0)!=='#')return;a.addEventListener('click',function(e){var t=document.getElementById(h.slice(1));if(!t)return;e.preventDefault();"
        "var y=t.getBoundingClientRect().top+window.pageYOffset-off();if(window.scrollToY){window.scrollToY(y);}else{window.scrollTo({top:y,behavior:'smooth'});}"
        "if(history.replaceState)history.replaceState(null,'',h);});});"
        "var targets=side.map(function(a){return document.getElementById((a.getAttribute('href')||'').slice(1));}).filter(Boolean);"
        "function mark(){var y=window.pageYOffset+off()+8,cur=null;targets.forEach(function(t){if(t.offsetTop<=y)cur=t;});"
        "side.forEach(function(a){a.classList.toggle('is-active',!!cur&&a.getAttribute('href')==='#'+cur.id);});}"
        "window.addEventListener('scroll',mark,{passive:true});window.addEventListener('resize',mark);mark();})();</script>",
        "{{include:partials/scripts.html}}",
        "",
    ])
    write("process.html", page)


# ---------------------------------------------------------------------------
# faq
# ---------------------------------------------------------------------------

def faq_items(base: str, items: list, cls: str) -> str:
    out = []
    for qi, it in enumerate(items):
        ip = f"{base}.items.{qi}"
        link = ""
        if it.get("link"):
            link = f'<a class="arrow-link {cls}-a-link" href="{esc(it["link"]["href"])}">{T(ip + ".link.label")} {ARROW}</a>'
        out.append(
            f'<details class="{cls}-item"><summary class="{cls}-q"><span class="{cls}-q-text">{T(ip + ".q")}</span><span class="{cls}-plus" aria-hidden="true"></span></summary>'
            f'<div class="{cls}-a"><p class="{cls}-a-p">{T(ip + ".a")}</p>{link}</div></details>')
    return "\n        ".join(out)


ACCORDION_JS = ("<script>(function(){var groups=document.querySelectorAll('[data-accordion]');for(var g=0;g<groups.length;g++){(function(grp){"
                "var items=grp.querySelectorAll('details');for(var i=0;i<items.length;i++){items[i].addEventListener('toggle',function(){if(!this.open)return;"
                "for(var j=0;j<items.length;j++)if(items[j]!==this)items[j].open=false;if(window.ScrollTrigger&&ScrollTrigger.refresh)ScrollTrigger.refresh();});}})(groups[g]);}})();</script>")


def render_faq() -> None:
    f = load("faq")
    groups = f["groups"]

    side = "".join(
        f'<a class="faq-side-link" href="#{esc(g["id"])}">{T(f"faq.groups.{gi}.label")}<span class="faq-side-n">{len(g["items"])}</span></a>'
        for gi, g in enumerate(groups))

    blocks = []
    for gi, g in enumerate(groups):
        blocks.append(
            f'      <div class="faq-group" id="{esc(g["id"])}" data-accordion>\n'
            f'        <h2 class="faq-h2">{T(f"faq.groups.{gi}.h2")}</h2>\n'
            f'        {faq_items(f"faq.groups.{gi}", g["items"], "faq")}\n'
            "      </div>")

    buttons = []
    for bi, b in enumerate(f["cta"]["buttons"]):
        cls = "btn--lg" if b.get("primary") else "btn--lg btn--ghost"
        buttons.append(btn_html(T(f"faq.cta.buttons.{bi}.label"), b["href"], cls))

    ld = jsonld({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [{"@type": "Question", "name": it["q"], "acceptedAnswer": {"@type": "Answer", "text": it["a"]}}
                       for g in groups for it in g["items"]],
    })

    page = "\n".join([
        meta_block(f["meta"]["title"], f["meta"]["description"], "light", "bg-white", "page-faq", ld),
        GEN % "faq",
        "{{include:partials/head.html}}",
        "{{include:partials/nav.html}}",
        '<main class="faq" data-theme="light">',
        '  <section class="faq-hero">',
        f'    <p class="faq-eyebrow t-eyebrow">{T("faq.hero.eyebrow")}</p>',
        f'    <h1 class="faq-h1 t-title">{T("faq.hero.h1")}</h1>',
        f'    <p class="faq-lead">{T("faq.hero.p")}</p>',
        "  </section>",
        '  <section class="faq-body">',
        f'    <aside class="faq-side"><nav class="faq-side-nav" aria-label="Question groups">{side}</nav></aside>',
        '    <div class="faq-groups">',
        "\n".join(blocks),
        "    </div>",
        "  </section>",
        '  <section class="faq-cta section--sand-s">',
        f'    <h2 class="faq-cta-h2 t-h2">{T("faq.cta.h2")}</h2>',
        f'    <p class="faq-cta-p">{T("faq.cta.p")}</p>',
        f'    <div class="faq-cta-btns">{"".join(buttons)}</div>',
        "  </section>",
        "</main>",
        ACCORDION_JS,
        "<script>(function(){var links=[].slice.call(document.querySelectorAll('.faq-side-link'));var groups=links.map(function(a){return document.getElementById((a.getAttribute('href')||'').slice(1));});"
        "function mark(){var y=window.pageYOffset+140,cur=0;groups.forEach(function(g,i){if(g&&g.offsetTop<=y)cur=i;});links.forEach(function(a,i){a.classList.toggle('is-active',i===cur);});}"
        "window.addEventListener('scroll',mark,{passive:true});mark();})();</script>",
        "{{include:partials/footer.html}}",
        "{{include:partials/scripts.html}}",
        "",
    ])
    write("faq.html", page)


# ---------------------------------------------------------------------------
# agency
# ---------------------------------------------------------------------------

def numbered_rows(base: str, items: list, cls: str) -> str:
    rows = []
    for ii, it in enumerate(items):
        ip = f"{base}.items.{ii}"
        rows.append(
            f'<li class="{cls}-row"><span class="{cls}-row-n">{T(ip + ".n")}</span>'
            f'<span class="{cls}-row-name">{T(ip + ".name")}</span><span class="{cls}-row-blurb">{T(ip + ".blurb")}</span></li>')
    return f'<ol class="{cls}-rows">' + "".join(rows) + "</ol>"


def render_agency() -> None:
    a = load("agency")
    facts = "".join(
        f'<div class="agency-fact"><span class="agency-fact-k">{T(f"agency.editorial.facts.{fi}.label")}</span>'
        + (f'<a class="agency-fact-v" href="{esc(fc["href"])}">{T(f"agency.editorial.facts.{fi}.value")}</a>' if fc.get("href")
           else f'<span class="agency-fact-v">{T(f"agency.editorial.facts.{fi}.value")}</span>')
        + "</div>"
        for fi, fc in enumerate(a["editorial"]["facts"]))

    secs = []
    for si, s in enumerate(a["sections"]):
        sp = f"agency.sections.{si}"
        right = [f'<h2 class="agency-h2">{T(sp + ".h2")}</h2>']
        if s.get("paragraphs"):
            right += [f'<p class="agency-p">{T(f"{sp}.paragraphs.{pi}")}</p>' for pi in range(len(s["paragraphs"]))]
        if s.get("p"):
            right.append(f'<p class="agency-p">{T(sp + ".p")}</p>')
        rows = numbered_rows(sp, s["items"], "agency") if s.get("items") else ""
        secs.append(
            f'  <section class="agency-sec" id="{esc(s["id"])}">\n'
            f'    <p class="eyebrow agency-eyebrow">{T(sp + ".eyebrow")}</p>\n'
            f'    <div class="agency-sec-body">{"".join(right)}</div>\n'
            + (f"    {rows}\n" if rows else "")
            + "  </section>")

    buttons = []
    for bi, b in enumerate(a["cta"]["buttons"]):
        buttons.append(btn_html(T(f"agency.cta.buttons.{bi}.label"), b["href"], "btn--lg" if b.get("primary") else "btn--lg btn--ghost"))
    primary = next((b for b in a["cta"]["buttons"] if b.get("primary")), a["cta"]["buttons"][0])
    pidx = a["cta"]["buttons"].index(primary)

    ld = jsonld({
        "@context": "https://schema.org",
        "@type": "AboutPage",
        "name": a["hero"]["h1"],
        "url": BASE_URL + a["meta"]["path"],
        "description": a["meta"]["description"],
        "inLanguage": "en-GB",
        "mainEntity": {"@type": "Organization", "name": "hypjam", "url": BASE_URL, "email": "hello@hypjam.com",
                       "founder": {"@type": "Person", "name": a["founder"]["name"], "jobTitle": a["founder"]["role"]},
                       "address": {"@type": "PostalAddress", "addressLocality": "London", "addressCountry": "GB"}},
    })

    page = "\n".join([
        meta_block(a["meta"]["title"], a["meta"]["description"], "light", "bg-white", "page-agency", ld),
        GEN % "agency",
        "{{include:partials/head.html}}",
        "{{include:partials/nav.html}}",
        '<main class="agency" data-theme="light">',
        '  <section class="agency-hero">',
        f'    <p class="agency-hero-eyebrow t-eyebrow">{T("agency.hero.eyebrow")}</p>',
        f'    <h1 class="agency-h1 t-title">{T("agency.hero.h1")}</h1>',
        f'    <p class="agency-intro">{T("agency.hero.intro")}</p>',
        "    " + btn_html(T(f"agency.cta.buttons.{pidx}.label"), primary["href"]),
        "  </section>",
        '  <section class="agency-editorial">',
        f'    <div class="agency-drawing" role="img" aria-label="{esc(a["editorial"]["image"]["alt"])}">{{{{drawing}}}}</div>',
        '    <div class="agency-facts-row">',
        f'      <p class="agency-caption">{T("agency.editorial.caption")}</p>',
        f'      <div class="agency-facts">{facts}</div>',
        "    </div>",
        "  </section>",
        "\n".join(secs),
        '  <section class="agency-founder section--sand-s">',
        f'    <p class="eyebrow agency-eyebrow">{T("agency.founder.eyebrow")}</p>',
        '    <figure class="agency-founder-body">',
        f'      <blockquote class="agency-quote t-quote t-hanging">“{T("agency.founder.quote")}”</blockquote>',
        f'      <figcaption class="agency-founder-cap"><span class="agency-founder-name">{T("agency.founder.name")}</span><span class="agency-founder-role">{T("agency.founder.role")}</span></figcaption>',
        "    </figure>",
        "  </section>",
        '  <section class="agency-cta">',
        f'    <img class="agency-cta-art" src="/assets/img/hq-footer.svg" alt="{esc(a["cta"]["art"]["alt"])}" width="280" height="120" loading="lazy" decoding="async" onerror="this.classList.add(\'is-missing\')">',
        f'    <h2 class="agency-cta-h2 t-h2">{T("agency.cta.h2")}</h2>',
        f'    <p class="agency-cta-p">{T("agency.cta.p")}</p>',
        f'    <div class="agency-cta-btns">{"".join(buttons)}</div>',
        "  </section>",
        "</main>",
        "{{include:partials/footer.html}}",
        "{{include:partials/scripts.html}}",
        "",
    ])
    write("agency.html", page)


# ---------------------------------------------------------------------------
# join
# ---------------------------------------------------------------------------

def render_join() -> None:
    j = load("join")
    looking = "".join(f'<li class="join-look-i"><span class="join-dot" aria-hidden="true"></span><span>{T(f"join.looking_for.items.{i}")}</span></li>'
                      for i in range(len(j["looking_for"]["items"])))
    steps = "".join(
        f'<li class="join-row"><span class="join-row-n">{T(f"join.how.steps.{i}.n")}</span><span class="join-row-name">{T(f"join.how.steps.{i}.name")}</span>'
        f'<span class="join-row-blurb">{T(f"join.how.steps.{i}.blurb")}</span></li>' for i in range(len(j["how"]["steps"])))
    checklist = "".join(f'<li class="join-check-i"><span class="join-check" aria-hidden="true">{CHECK}</span><span>{T(f"join.apply.checklist.{i}")}</span></li>'
                        for i in range(len(j["apply"]["checklist"])))
    mailto = j["apply"]["button"]["href"]

    ld = jsonld({
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": j["hero"]["h1"],
        "url": BASE_URL + j["meta"]["path"],
        "description": j["meta"]["description"],
        "inLanguage": "en-GB",
        "publisher": {"@type": "Organization", "name": "hypjam", "url": BASE_URL},
    })

    page = "\n".join([
        meta_block(j["meta"]["title"], j["meta"]["description"], "light", "bg-white", "page-join", ld),
        GEN % "join",
        "{{include:partials/head.html}}",
        "{{include:partials/nav.html}}",
        '<main class="join" data-theme="light">',
        '  <section class="join-hero">',
        f'    <p class="join-hero-eyebrow t-eyebrow">{T("join.hero.eyebrow")}</p>',
        f'    <h1 class="join-h1 t-title">{T("join.hero.h1")}</h1>',
        f'    <p class="join-sub">{T("join.hero.sub")}</p>',
        "    " + btn_html(T("join.hero.cta.label"), j["hero"]["cta"]["href"]),
        "  </section>",
        '  <section class="join-sec" id="looking-for">',
        f'    <p class="eyebrow join-eyebrow">{T("join.looking_for.eyebrow")}</p>',
        f'    <div class="join-sec-body"><h2 class="join-h2">{T("join.looking_for.h2")}</h2><ul class="join-look">{looking}</ul></div>',
        "  </section>",
        '  <section class="join-sec" id="how-it-works">',
        f'    <p class="eyebrow join-eyebrow">{T("join.how.eyebrow")}</p>',
        f'    <div class="join-sec-body"><h2 class="join-h2">{T("join.how.h2")}</h2></div>',
        f'    <ol class="join-rows">{steps}</ol>',
        "  </section>",
        '  <section class="join-sec join-pay section--sand-s" id="pay">',
        f'    <p class="eyebrow join-eyebrow">{T("join.pay.eyebrow")}</p>',
        f'    <div class="join-sec-body"><h2 class="join-h2">{T("join.pay.h2")}</h2><p class="join-p">{T("join.pay.p")}</p></div>',
        "  </section>",
        '  <section class="join-sec" id="questions">',
        '    <p class="eyebrow join-eyebrow">FAQ</p>',
        f'    <div class="join-sec-body" data-accordion><h2 class="join-h2">{T("join.faq.h2")}</h2>',
        "        " + faq_items("join.faq", j["faq"]["items"], "join"),
        "    </div>",
        "  </section>",
        '  <section class="join-sec join-apply" id="apply">',
        f'    <p class="eyebrow join-eyebrow">{T("join.apply.eyebrow")}</p>',
        '    <div class="join-sec-body">',
        f'      <h2 class="join-h2">{T("join.apply.h2")}</h2>',
        f'      <p class="join-p">{T("join.apply.p")}</p>',
        f'      <ul class="join-checklist">{checklist}</ul>',
        "      " + btn_html(T("join.apply.button.label"), mailto, "btn--lg"),
        f'      <p class="join-privacy">{T("join.apply.privacy.text")} <a class="join-privacy-a" href="{esc(j["apply"]["privacy"]["href"])}">{T("join.apply.privacy.link_label")}</a>.</p>',
        "    </div>",
        "  </section>",
        "</main>",
        ACCORDION_JS,
        "{{include:partials/footer.html}}",
        "{{include:partials/scripts.html}}",
        "",
    ])
    write("join.html", page)


def main() -> int:
    render_blog()
    render_legal()
    render_process()
    render_faq()
    render_agency()
    render_join()
    return 0


if __name__ == "__main__":
    sys.exit(main())
