#!/usr/bin/env python3
"""
render_rights_work_book.py — writes the /rights, /work and /book page
templates from content/rights.json, work.json and book.json.

The templates reference copy with {{content:…}} placeholders so the JSON
stays the single source of truth; the renderer only decides *how many* cells,
questions, tiles and cards to stamp out (build.py has no loops) and which
line-drawn icon / platform glyph each item gets. Two strings are copied
literally because build.py cannot split them: the two-line /work heading
(work.hero.h1 split after work.hero.h1_break_after) — everything else is a
reference. Idempotent; run by build.py before the pages are expanded.

Reference pages: ref/pages/security.jpg (→ rights), hotels.jpg (→ work),
get-started.jpg (→ book). Every number in the CSS comments is measured there.
"""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
PAGES = ROOT / "src" / "pages"
ASSETS = ROOT / "assets"

GENERATED = "<!-- generated by tools/render_rights_work_book.py — edit content/{name}.json -->"


def T(path: str, fallback=None) -> str:
    """A {{content:…}} placeholder for build.py."""
    if fallback is not None:
        return "{{content:%s|%s}}" % (path, fallback)
    return "{{content:%s}}" % path


def load(name: str) -> dict:
    return json.loads((CONTENT / f"{name}.json").read_text(encoding="utf-8"))


ARROW = ('<svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true">'
         '<path d="M1.5 6h8M6.2 2.5 9.7 6l-3.5 3.5" fill="none" stroke="currentColor" '
         'stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
ARROW_11 = ARROW.replace('width="12" height="12"', 'width="11" height="11"')
EXTERNAL = ('<svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true">'
            '<path d="M4.5 2H2v8h8V7.5M7 2h3v3M10 2 5.5 6.5" fill="none" stroke="currentColor" '
            'stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>')
CHEVRON = ('<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">'
           '<path d="M6 3.2 10.6 8 6 12.8" fill="none" stroke="currentColor" stroke-width="1.4" '
           'stroke-linecap="round" stroke-linejoin="round"/></svg>')
PLUS = ('<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">'
        '<path d="M8 2.5v11M2.5 8h11" fill="none" stroke="currentColor" stroke-width="1.2" '
        'stroke-linecap="round"/></svg>')
PHONE = ('<svg class="sto-phone-svg" viewBox="0 0 100 212" aria-hidden="true" focusable="false">'
         '<g fill="none" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round">'
         '<rect x="1.5" y="1.5" width="97" height="209" rx="16"/>'
         '<rect class="sto-phone-screen" x="8" y="9" width="84" height="194" rx="10"/>'
         '<path d="M40 16h20" stroke-width="1.6"/><path d="M42 106.5v-13l11 6.5z"/><path d="M38 194h24"/>'
         '<path class="sto-phone-side" d="M99.75 46v14M-.25 52v10M-.25 66v10"/></g></svg>')


def btn(label: str, href: str, cls: str = "btn", ico: str = ARROW_11) -> str:
    return f'<a href="{href}" class="{cls}">{label}<span class="btn__ico">{ico}</span></a>'


# 24px monoline icons for the rights grid (rights.json grid.cells[].icon)
ICONS = {
    "document":  '<path d="M6 2.5h8l4.5 4.5v14.5H6z"/><path d="M14 2.5V7h4.5"/><path d="M9 12h6M9 15.5h6M9 19h4"/>',
    "signature": '<path d="M3 17.5c2.4-6.2 4-9.5 5.4-9.5 1.6 0 .6 7.5 2.1 7.5 1.6 0 2.9-8.5 4.4-8.5 1.5 0 .5 7.5 2.4 7.5 1.4 0 2.5-1.7 3.7-3.2"/><path d="M3 21h18"/>',
    "tag":       '<path d="M3.5 12.5v-8a1 1 0 0 1 1-1h8l8 8-9 9z"/><circle cx="8" cy="8" r="1.5"/>',
    "checklist": '<rect x="3" y="3.5" width="6" height="6" rx="1"/><path d="m4.8 6.6 1.3 1.3L8.4 5.4"/><path d="M12 6.5h9"/><rect x="3" y="14.5" width="6" height="6" rx="1"/><path d="m4.8 17.6 1.3 1.3 2.3-2.5"/><path d="M12 17.5h9"/>',
    "lock":      '<rect x="4.5" y="10.5" width="15" height="10.5" rx="1.5"/><path d="M8 10.5V7.5a4 4 0 0 1 8 0v3"/><circle cx="12" cy="16" r="1.2"/>',
    "folder":    '<path d="M3 6.5A1.5 1.5 0 0 1 4.5 5H9l2 2h8.5A1.5 1.5 0 0 1 21 8.5v10a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 18.5z"/><path d="M3 10.5h18"/>',
}

# platform ids used in work.json / book.json → sprite glyph (src/partials/icons.html #p-*)
GLYPH = {
    "tiktok": "p-tiktok", "reels": "p-instagram", "ig-reels": "p-instagram", "ig-stories": "p-instagram",
    "shorts": "p-youtube", "yt-shorts": "p-youtube", "snapchat": "p-snapchat", "snap-ads": "p-snapchat",
    "pinterest": "p-pinterest", "pinterest-video": "p-pinterest", "meta-ads": "p-meta", "meta-partnership": "p-meta",
    "tiktok-in-feed": "p-tiktok", "tiktok-spark": "p-tiktok",
}
SEAL = {  # book.json rights badge ids → sprite seal
    "usage": "seal-usage-rights", "release": "seal-releases", "disclosure": "seal-disclosure", "gdpr": "seal-uk-gdpr",
}


def glyph(pid: str, cls: str = "") -> str:
    sym = GLYPH.get(pid)
    if not sym:
        return ""
    return f'<svg class="{cls}" viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><use href="#{sym}"/></svg>'


# ---------------------------------------------------------------------------
# /rights  (ref/pages/security.jpg)
# ---------------------------------------------------------------------------

def rights_page(d: dict) -> str:
    hero, grid, q = d["hero"], d["grid"], d["questions"]

    seals = []
    for i, b in enumerate(hero["badges"]):
        seal_file = b.get("seal_file", "")
        exists = (ASSETS / seal_file.lstrip("/").removeprefix("assets/")).is_file() if seal_file else False
        if exists:
            seals.append(
                f'      <li class="rights-hero-seal" title="{T(f"rights.hero.badges.{i}.label")}">'
                f'<img src="{T(f"rights.hero.badges.{i}.seal_file")}" alt="{T(f"rights.hero.badges.{i}.alt")}" '
                f'width="240" height="240" loading="eager" decoding="async" draggable="false"></li>')
        else:  # schema fallback: the engraved text inside a 1px circle
            first, _, second = b.get("seal_text", "").partition(" · ")
            seals.append(
                f'      <li class="rights-hero-seal rights-hero-seal--text" role="img" aria-label="{T(f"rights.hero.badges.{i}.alt")}">'
                f'<span class="rights-hero-seal-ring"><span>{first}</span><span>{second}</span></span></li>')

    cells = []
    for i, c in enumerate(grid["cells"]):
        icon = ICONS.get(c.get("icon", ""), ICONS["document"])
        cells.append(f'''      <li class="rights-how-cell">
        <div class="rights-how-text">
          <h3 class="rights-how-title t-eyebrow-lg">{T(f"rights.grid.cells.{i}.title")}</h3>
          <span class="dash" aria-hidden="true"></span>
          <p class="rights-how-body">{T(f"rights.grid.cells.{i}.body")}</p>
        </div>
        <svg class="rights-how-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">{icon}</svg>
      </li>''')

    items = []
    for i, it in enumerate(q["items"]):
        link = ""
        if it.get("link"):
            link = (f'\n            <a class="arrow-link rights-acc-link" href="{T(f"rights.questions.items.{i}.link.href")}">'
                    f'{T(f"rights.questions.items.{i}.link.label")}{ARROW}</a>')
        items.append(f'''      <div class="rights-acc-item" data-acc-item>
        <h3 class="rights-acc-h"><button type="button" class="rights-acc-btn" id="rights-acc-b{i}" aria-expanded="false" aria-controls="rights-acc-p{i}" data-acc-btn><span class="rights-acc-q">{T(f"rights.questions.items.{i}.q")}</span><span class="rights-acc-ico" aria-hidden="true">{PLUS}</span></button></h3>
        <div class="rights-acc-panel" id="rights-acc-p{i}" role="region" aria-labelledby="rights-acc-b{i}" data-acc-panel>
          <div class="rights-acc-panel-in">
            <p class="rights-acc-a">{T(f"rights.questions.items.{i}.a")}</p>{link}
          </div>
        </div>
      </div>''')

    nl = "\n"
    return f'''<!-- title: {T("rights.meta.title")} -->
<!-- description: {T("rights.meta.description")} -->
<!-- nav: light -->
<!-- nav-fill: bg-sand-m -->
<!-- body-class: page-rights -->
{GENERATED.format(name="rights")}
{{{{include:partials/head.html}}}}
{{{{include:partials/nav.html}}}}
{{{{include:partials/icons.html}}}}
<main class="rights-page">

  <!-- hero · Lance: section.security-hero flex h-svh min-h-[500px] flex-col items-center justify-center bg-sand-m px-page
       h1 56px/1 two lines · p 18/24 grey max-w 600 · pill · seals 120px, gap 120 -->
  <section class="rights-hero" data-nav="light" data-nav-fill="bg-sand-m" data-theme="sand-m">
    <div class="rights-hero-inner">
      <h1 class="rights-hero-h1 t-display t-balance">{T("rights.hero.h1")}</h1>
      <p class="rights-hero-sub">{T("rights.hero.sub")}</p>
      {btn(T("rights.hero.cta.label"), T("rights.hero.cta.href"), "btn btn--lg rights-hero-cta", ARROW)}
      <ul class="rights-hero-seals" aria-label="hypjam's four rights and safety commitments">
{nl.join(seals)}
      </ul>
    </div>
  </section>

  <!-- how · Lance: flex flex-col gap-20 bg-black px-page pb-7 pt-16 · 3×2 hairline grid, cells 327 tall -->
  <section id="rights-how" class="rights-how" data-nav="dark" data-nav-fill="bg-black" data-theme="dark">
    <h2 class="rights-how-h2 t-h2">{T("rights.grid.h2")}</h2>
    <ul class="rights-how-grid">
{nl.join(cells)}
    </ul>
  </section>

  <!-- questions · Lance: flex gap-12 bg-black px-page py-[120px] max-bp:flex-col · left h2 + p + pill, right accordion -->
  <section class="rights-q" data-nav="dark" data-nav-fill="bg-black" data-theme="dark">
    <div class="rights-q-intro">
      <h2 class="rights-q-h2 t-h2">{T("rights.questions.h2")}</h2>
      <p class="rights-q-p t-body">{T("rights.questions.p")}</p>
      {btn(T("rights.questions.cta.label"), T("rights.questions.cta.href"), "btn btn--dark rights-q-cta", ARROW_11)}
    </div>
    <div class="rights-acc" data-rights-acc>
{nl.join(items)}
    </div>
  </section>

  <!-- the closing CTA strip ("{T("rights.cta.h2")}" + "{T("rights.cta.button.label")}") is carried by the footer partial (foot-top), as on Lance -->
</main>
<script>
/* /rights accordion · one item open at a time · height animates via grid-template-rows (43-rights.css) */
(function () {{
  var root = document.querySelector('[data-rights-acc]');
  if (!root) return;
  var items = Array.prototype.slice.call(root.querySelectorAll('[data-acc-item]'));
  function set(item, open) {{
    var b = item.querySelector('[data-acc-btn]');
    if (open) item.classList.add('is-open'); else item.classList.remove('is-open');
    if (b) b.setAttribute('aria-expanded', open ? 'true' : 'false');
  }}
  items.forEach(function (item) {{
    var b = item.querySelector('[data-acc-btn]');
    if (!b) return;
    b.addEventListener('click', function () {{
      var open = !item.classList.contains('is-open');
      items.forEach(function (o) {{ if (o !== item) set(o, false); }});
      set(item, open);
    }});
  }});
}})();
</script>
{{{{include:partials/footer.html}}}}
{{{{include:partials/scripts.html}}}}
'''


# ---------------------------------------------------------------------------
# /work  (ref/pages/hotels.jpg)
# ---------------------------------------------------------------------------

def work_page(d: dict) -> str:
    hero, facts, wall, plat, fm, cta = d["hero"], d["facts"], d["wall"], d["platforms"], d["formats"], d["cta"]

    # the two-line heading: split literally after h1_break_after (build.py cannot split a string)
    h1 = hero["h1"]
    brk = hero.get("h1_break_after", "")
    if brk and f" {brk} " in f" {h1} ":
        head, _, tail = h1.partition(f"{brk} ")
        line1, line2 = (head + brk).strip(), tail.strip()
    else:
        line1, line2 = h1, ""
    # the two spans are blocks on desktop (the reference's two-line heading) and inline below
    # 1024px, where forcing the break would chop the line badly (44-work.css: .work-hero-l)
    h1_html = f'<span class="sto-h2-l1 work-hero-l">{line1}</span>' + (
        f' <span class="sto-h2-l1 work-hero-l">{line2}</span>' if line2 else "")

    cards = []
    for i, c in enumerate(hero["cards"]):
        p = f"work.hero.cards.{i}"
        alt = c.get("image", {}).get("alt", "")
        phone_attrs = f'role="img" aria-label="{T(p + ".image.alt")}"' if alt else 'aria-hidden="true"'
        cards.append(f'''      <li class="sto-card work-story" data-sto-card data-slot="{T(p + ".id")}">
        <div class="sto-media">
          <div class="sto-media-in">
            <div class="sto-read-row"><span class="sto-read" aria-disabled="true">{T(p + ".read.label", "Read")}{ARROW}</span></div>
            <div class="sto-phone" {phone_attrs}>{PHONE}</div>
            <div class="sto-text">
              <p class="sto-quote t-story-quote">{T(p + ".quote")}</p>
              <p class="sto-attr"><span class="tag-soon">{T(p + ".attribution")}</span></p>
            </div>
          </div>
        </div>
        <div class="sto-foot">
          <img class="sto-mark" src="/assets/brand/logos/hypjam-icon.svg" alt="hypjam" width="24" height="24" loading="lazy" decoding="async" draggable="false">
          <p class="sto-meta">{T(p + ".meta")}</p>
        </div>
      </li>''')

    fact_cells = []
    for i, c in enumerate(facts["cells"]):
        p = f"work.facts.cells.{i}"
        animate = ' data-count="%s"' % c["value"] if facts.get("animate") else ""
        fact_cells.append(f'''      <li class="work-fact">
        <p class="work-fact-num t-display"><span class="work-fact-n"{animate}>{T(p + ".value")}</span><span class="work-fact-suffix">{T(p + ".suffix")}</span></p>
        <p class="work-fact-label">{T(p + ".label")}</p>
      </li>''')

    quotes = []
    for i, c in enumerate(wall["cards"]):
        p = f"work.wall.cards.{i}"
        quotes.append(f'''      <li class="work-quote reserved reserved--card">
        <p class="work-quote-text t-hanging">“{T(p + ".quote")}”</p>
        <div class="work-quote-by">
          <span class="tag-soon">{T(p + ".name")}</span>
          <p class="work-quote-role t-meta">{T(p + ".role")}</p>
        </div>
      </li>''')

    groups = []
    for gi, g in enumerate(plat["groups"]):
        tiles = []
        large = gi == 0
        for ti, t in enumerate(g["tiles"]):
            p = f"work.platforms.groups.{gi}.tiles.{ti}"
            gl = glyph(t.get("id", ""), "work-plat-glyph") if large else ""
            tiles.append(f'        <li class="work-plat-tile{"" if large else " work-plat-tile--sm"}"><span class="work-plat-tile-in">{gl}<span class="work-plat-text">{T(p + ".text")}</span></span></li>')
        groups.append(f'''    <div class="work-plat-group">
      <p class="work-plat-label">{T(f"work.platforms.groups.{gi}.label")}</p>
      <ul class="{"work-plat-row" if large else "work-plat-grid"}">
{chr(10).join(tiles)}
      </ul>
    </div>''')

    formats = []
    for i, f in enumerate(fm["formats"]):
        p = f"work.formats.formats.{i}"
        tags = "".join(f'<li class="work-tag">{T(p + f".tags.{k}")}</li>' for k in range(len(f.get("tags", []))))
        formats.append(f'''      <li class="work-format" id="format-{f["id"]}">
        <h3 class="work-format-name t-h3">{T(p + ".name")}</h3>
        <p class="work-format-blurb">{T(p + ".blurb")}</p>
        <ul class="work-format-tags" aria-label="Tags">{tags}</ul>
      </li>''')

    fmt_index = {f["id"]: k for k, f in enumerate(fm["formats"])}
    samples = []
    for i, s in enumerate(fm["samples"]):
        p = f"work.formats.samples.{i}"
        k = fmt_index.get(s.get("format_id"))
        fmt_link = (f'<a class="arrow-link work-sample-format" href="#format-{s["format_id"]}">{T(f"work.formats.formats.{k}.name")}{ARROW}</a>'
                    if k is not None else "")
        samples.append(f'''      <li class="work-sample">
        <div class="work-sample-top"><span class="work-sample-brand">{T(p + ".brand")}</span><span class="tag-soon tag-soon--static tag-soon--caps">{T(p + ".status")}</span></div>
        <p class="work-sample-hook t-story-quote t-hanging">“{T(p + ".hook")}”</p>
        <p class="work-sample-creator">{T(p + ".creator_brief")}</p>
        <p class="work-sample-note">{T(p + ".note")}</p>
        {fmt_link}
      </li>''')

    nl = "\n"
    return f'''<!-- title: {T("work.meta.title")} -->
<!-- description: {T("work.meta.description")} -->
<!-- nav: dark -->
<!-- nav-fill: bg-black -->
<!-- body-class: page-work -->
{GENERATED.format(name="work")}
{{{{include:partials/head.html}}}}
{{{{include:partials/nav.html}}}}
{{{{include:partials/icons.html}}}}
<main class="work-page">

  <!-- hero · Lance's story carousel with the hotels-page paddings (pt-[220px] pb-[90px]); the four cards are the
       reserved slots of CONTRACT §10 in the home partial's anatomy (.sto-*, 32-stories.css + 32-stories.js) -->
  <section class="sto work-hero" data-nav="image" data-nav-fill="bg-black" data-sto>
    <div class="sto-head">
      <div class="work-hero-head">
        <h1 class="sto-h2 work-hero-h1 t-h2">{h1_html}</h1>
        <p class="sto-h2-l2 work-hero-dim t-h2 t-h2-dim">{T("work.hero.sub_dim")}</p>
      </div>
      <div class="sto-nav">
        <button type="button" class="sto-arrow sto-arrow--prev" aria-label="{T("work.hero.controls.prev", "Previous story")}" data-sto-prev>{CHEVRON}</button>
        <button type="button" class="sto-arrow sto-arrow--next" aria-label="{T("work.hero.controls.next", "Next story")}" data-sto-next>{CHEVRON}</button>
      </div>
    </div>
    <div class="sto-mask" data-sto-mask aria-roledescription="carousel" aria-label="Brand stories, held open">
      <ul class="sto-track" data-sto-track>
{nl.join(cards)}
      </ul>
    </div>
  </section>

  <!-- facts · Lance: flex flex-col items-center gap-20 bg-sand-s px-page py-[120px] · 3×2 tiles, 80px numerals -->
  <section class="work-facts" data-nav="light" data-nav-fill="bg-sand-s" data-theme="sand">
    <div class="work-sec-head">
      <h2 class="t-h2">{T("work.facts.h2")}</h2>
      <p class="work-sec-p t-body">{T("work.facts.p")}</p>
    </div>
    <ul class="work-facts-grid">
{nl.join(fact_cells)}
    </ul>
  </section>

  <!-- wall · Lance: flex flex-col items-center gap-[84px] bg-white px-page pb-[72px] pt-[120px] · three reserved cards -->
  <section class="work-wall" data-nav="light" data-nav-fill="bg-white" data-theme="light">
    <div class="work-sec-head">
      <h2 class="t-h2">{T("work.wall.h2")}</h2>
      <p class="work-sec-p work-sec-p--wide t-body">{T("work.wall.p")}</p>
    </div>
    <ul class="work-wall-grid">
{nl.join(quotes)}
    </ul>
  </section>

  <!-- platforms · Lance: flex flex-col gap-10 px-page pb-[120px] pt-[72px] · label + row of large tiles, label + grid -->
  <section class="work-platforms" data-nav="light" data-nav-fill="bg-white" data-theme="light">
{nl.join(groups)}
  </section>

  <!-- photo CTA · Lance: relative flex h-svh min-h-[580px] flex-col justify-center overflow-hidden · still + h2 + p + pill -->
  <section class="work-cta" data-nav="image" data-nav-fill="bg-transparent" data-theme="dark">
    <img class="work-cta-bg" src="/assets/img/stills/aerial-close.jpg" alt="{T("work.cta.background.alt", "")}" loading="lazy" decoding="async">
    <div class="work-cta-shade" aria-hidden="true"></div>
    <div class="work-cta-row">
      <div class="work-cta-text">
        <h2 class="work-cta-h2 t-h2">{T("work.cta.h2")}</h2>
        <p class="work-cta-p t-body">{T("work.cta.p")}</p>
      </div>
      {btn(T("work.cta.button.label"), T("work.cta.button.href"), "btn btn--lg btn--dark work-cta-btn", ARROW)}
    </div>
  </section>

  <!-- formats · hypjam's own wall (carried over from the existing /work): the disclosure, six formats, eight sample tiles -->
  <section class="work-formats" data-nav="light" data-nav-fill="bg-sand-s" data-theme="sand">
    <div class="work-formats-head">
      <p class="eyebrow">{T("work.formats.eyebrow")}</p>
      <h2 class="work-formats-h2 t-h2">{T("work.formats.h2")}</h2>
      <p class="work-formats-intro t-body">{T("work.formats.intro")}</p>
    </div>
    <ul class="work-format-grid">
{nl.join(formats)}
    </ul>
    <div class="work-samples">
      <p class="work-plat-label">{T("work.formats.samples_label")}</p>
      <ul class="work-sample-grid">
{nl.join(samples)}
      </ul>
    </div>
  </section>
</main>
<script>
/* /work facts · count up from 0 when the grid scrolls into view (work.facts.animate); reduced motion = final value */
(function () {{
  var nums = Array.prototype.slice.call(document.querySelectorAll('.work-fact-n[data-count]'));
  if (!nums.length) return;
  var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  function run(el) {{
    var to = parseFloat(el.getAttribute('data-count')) || 0;
    if (reduce || !window.requestAnimationFrame) {{ el.textContent = String(to); return; }}
    var t0 = null, dur = 1400;
    function frame(t) {{
      if (t0 === null) t0 = t;
      var p = Math.min(1, (t - t0) / dur);
      var e = 1 - Math.pow(1 - p, 3);
      el.textContent = String(Math.round(to * e));
      if (p < 1) window.requestAnimationFrame(frame);
    }}
    window.requestAnimationFrame(frame);
  }}
  if (!('IntersectionObserver' in window)) {{ nums.forEach(run); return; }}
  var io = new IntersectionObserver(function (entries) {{
    entries.forEach(function (en) {{ if (en.isIntersecting) {{ io.unobserve(en.target); run(en.target); }} }});
  }}, {{ threshold: .4 }});
  nums.forEach(function (n) {{ if (!reduce) n.textContent = '0'; io.observe(n); }});
}})();
</script>
{{{{include:partials/footer.html}}}}
{{{{include:partials/scripts.html}}}}
'''


# ---------------------------------------------------------------------------
# /book  (ref/pages/get-started.jpg)
# ---------------------------------------------------------------------------

def book_page(d: dict) -> str:
    left, right = d["left"], d["right"]

    expect = "".join(f'\n            <li>{T(f"book.left.expect.items.{i}")}</li>' for i in range(len(left["expect"]["items"])))

    ships = []
    for i, s in enumerate(right["ships_to"]["items"]):
        ships.append(f'<div class="marquee__cell" role="listitem"><span class="book-ship">{glyph(s.get("id", ""), "book-ship-glyph")}<span>{T(f"book.right.ships_to.items.{i}.text")}</span></span></div>')
    ships_dup = [c.replace(' role="listitem"', "") for c in ships]

    seals = []
    for i, b in enumerate(right["rights"]["badges"]):
        sym = SEAL.get(b.get("id", ""))
        if sym:
            seals.append(f'          <li><svg class="book-seal" viewBox="0 0 240 240" role="img" aria-label="{T(f"book.right.rights.badges.{i}.label")}"><use href="#{sym}"/></svg></li>')
        else:
            seals.append(f'          <li><img class="book-seal" src="{T(f"book.right.rights.badges.{i}.seal_file")}" alt="{T(f"book.right.rights.badges.{i}.label")}" width="40" height="40" loading="lazy" decoding="async"></li>')

    nl = "\n"
    return f'''<!-- title: {T("book.meta.title")} -->
<!-- description: {T("book.meta.description")} -->
<!-- nav: light -->
<!-- nav-fill: bg-sand-s -->
<!-- body-class: page-book -->
{GENERATED.format(name="book")}
{{{{include:partials/head.html}}}}
{{{{include:partials/icons.html}}}}
<main class="book-page" data-theme="sand">

  <!-- Lance's get-started header: lockup left, one small line right, 60px, no nav -->
  <header class="book-header">
    <a href="{T("book.header.logo.href", "/")}" class="book-logo" aria-label="hypjam home"><img src="{T("book.header.logo.file")}" alt="{T("book.header.logo.alt", "hypjam")}" width="860" height="262" decoding="async"></a>
    <a href="{T("book.header.right.href")}" class="book-header-link">{T("book.header.right.label")}</a>
  </header>

  <section class="book-split">

    <!-- left · Lance: flex items-center justify-center bg-sand-s px-page py-6 · 440px column · h1 36px -->
    <div class="book-left">
      <div class="book-form">
        <h1 class="book-h1 t-display">{T("book.left.h1")}</h1>
        <p class="book-sub">{T("book.left.sub")}</p>

        <!-- the cal.com embed takes the form's place; it loads only after a click (CONTRACT §11), never colour-inverted -->
        <div class="book-embed" data-book-embed data-src="{T("book.left.embed.src")}" data-title="{T("book.meta.title")}" data-height="{T("book.left.embed.height_min", "640")}">
          <button type="button" class="btn btn--solid book-open" data-book-open aria-expanded="false">{T("book.left.embed.open_label", "Open the calendar")}<span class="btn__ico">{ARROW}</span></button>
          <div class="book-frame" data-book-frame data-lenis-prevent hidden></div>
          <p class="book-fallback"><a href="{T("book.left.embed.fallback.href")}" target="_blank" rel="noopener">{T("book.left.embed.fallback.label")}{EXTERNAL}</a></p>
        </div>

        <div class="book-expect">
          <p class="book-expect-label t-eyebrow">{T("book.left.expect.label")}</p>
          <ul class="book-expect-list">{expect}
          </ul>
        </div>

        <p class="book-note">{T("book.left.privacy.text")} <a href="{T("book.left.privacy.href")}">{T("book.left.privacy.link_label")}</a>.</p>
      </div>
    </div>

    <!-- right · Lance: the photo column with the frosted quote card (420px), the logo row inside it, seals at the bottom -->
    <div class="book-right" data-theme="dark">
      <div class="book-right-sticky">
        <img class="book-still" src="/assets/img/stills/studio-creator.jpg" alt="{T("book.right.background.alt", "")}" decoding="async">
        <div class="book-shade" aria-hidden="true"></div>
        <div class="book-right-in">
          <figure class="book-card">
            <blockquote class="book-quote t-card-title t-hanging">“{T("book.right.quote.text")}”</blockquote>
            <figcaption class="book-cap">
              <span class="book-sig" aria-hidden="true">{T("book.right.quote.name")}</span>
              <div class="book-cap-row">
                <div>
                  <p class="book-name">{T("book.right.quote.name")}</p>
                  <p class="book-role">{T("book.right.quote.role")}</p>
                </div>
                <img class="book-mark" src="{T("book.right.quote.mark")}" alt="" width="40" height="40" loading="lazy" decoding="async">
              </div>
            </figcaption>
            <div class="book-card-foot">
              <p class="book-ships-label">{T("book.right.ships_to.label")}</p>
              <div class="marquee marquee--compact book-ships" role="list" aria-label="{T("book.right.ships_to.label")}">
                <div class="marquee__track">
                  <div class="marquee__group">{"".join(ships)}</div>
                  <div class="marquee__group" aria-hidden="true">{"".join(ships_dup)}</div>
                </div>
              </div>
            </div>
          </figure>
          <div class="book-rights">
            <p class="book-rights-label">{T("book.right.rights.label")}</p>
            <ul class="book-seals">
{nl.join(seals)}
            </ul>
          </div>
        </div>
      </div>
    </div>

  </section>
</main>
{{{{include:partials/scripts.html}}}}
'''


def main() -> int:
    PAGES.mkdir(parents=True, exist_ok=True)
    for name, fn in (("rights", rights_page), ("work", work_page), ("book", book_page)):
        html = fn(load(name))
        target = PAGES / f"{name}.html"
        if not target.is_file() or target.read_text(encoding="utf-8") != html:
            target.write_text(html, encoding="utf-8")
        print("wrote", target.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
